In [1]:
import sys
import copy
import pandas as pd
import statistics
import datetime

In [2]:
grp_dad = pd.read_excel('one.xlsx',header=[1], index_col=[1])
print(grp_dad.head(20),grp_dad.shape)

C:\Users\USER\miniconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                                 Unnamed: 0       Дата Подрядчик  \
Номер скважины
99              Проблемы при построении ГРП 2019-10-20        КН
980             Проблемы при построении ГРП 2015-10-22        КН
980             Проблемы при построении ГРП 2015-10-21        КН
980             Проблемы при построении ГРП 2015-10-21        КН
980             Проблемы при построении ГРП 2015-10-20        КН
980             Проблемы при построении ГРП 2015-10-20        КН
980             Проблемы при построении ГРП 2015-10-11        КН
980             Проблемы при построении ГРП 2015-10-11        КН
98              Проблемы при построении ГРП 2019-07-31        КН
98              Проблемы при построении ГРП 2019-07-30        КН
98              Проблемы при построении ГРП 2019-07-30        КН
98              Проблемы при построении ГРП 2019-07-29        КН
98              Проблемы при построении ГРП 2019-07-29        КН
98              Проблемы при построении ГРП 2019-07-28        КН
98              Проблемы при построении ГРП 2019-07-28        КН
98              Проблемы при построении ГРП 2019-07-27        КН
98              Проблемы при построении ГРП 2019-07-27        КН
978             Проблемы при построении ГРП 2015-10-31        КН
977             Проблемы при построении ГРП 2015-08-29        КН
977             Проблемы при построении ГРП 2015-08-29        КН

                                                      Комментарии Страница  \
Номер скважины
99              Оборудование:  НКТ, ПРО, АМТ-  ООО "КАТКонефть...      -1_
980             Замещение проводилось 21.10.2015 г. По результ...      -1_
980             Замещение проводилось 21.10.2015 г. По результ...      -1_
980             По результатам замещения была проведена повтор...      -1_
980             Замещение проводилось 19.10.2015 г. По результ...      -1_
980             замещение проводилось 19.10.2015 г. По результ...      -1_
980             На стадии замещения при активации муфты ГРП №1...      -1_
980             По результату замещения принято решение о сокр...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
978             Мини ГРП проводился 31.10.2015 г. По результат...      -1_
977             По результатам замещения были внесены изменени...      -1_
977             По результату Мини ГРП были внесены изменения ...      -1_

                Unnamed: 6 Пласт  Наклон  Азимут     k  ...  \
Номер скважины                                          ...
99                     NaN    Ю3   17.00   245.0  24.6  ...
980                    NaN    Ю2   87.70   184.0  15.0  ...
980                    NaN    Ю2   90.90   184.0  15.0  ...
980                    NaN    Ю2   90.30   184.0  15.0  ...
980                    NaN    Ю2   89.90   183.0  15.0  ...
980                    NaN    Ю2   90.90   184.0  15.0  ...
980                    NaN    Ю2   90.90   184.0  15.0  ...
980                    NaN    Ю2   92.50   183.0  15.0  ...
98                     NaN    Ю2   76.83   312.0   7.7  ...
98                     NaN    Ю2   91.14   311.1   7.7  ...
98                     NaN    Ю2   93.64   310.9   7.7  ...
98                     NaN    Ю2   89.71   304.4   7.7  ...
98                     NaN    Ю2   87.69   302.4   7.7  ...
98                     NaN    Ю2   87.69   302.4   7.7  ...
98                     NaN    Ю2   88.70   300.3   7.7  ...
98                     NaN    Ю2   87.82    93.5   7.7  ...
98                     NaN    Ю2   90.14   298.9   7.7  ...
978                    NaN    Ю2    8.90   191.0  11.3  ...
977                    NaN    Ю2   88.40   160.0  23.3  ...
977                    NaN    Ю2   90.50   163.0  23.3  ...

                                                Проппант  Рпл Хорнер   Эфф  \
Номер скважины
99                             NIKA (Ptprop)+Fores+Fores        48.0  71.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  59.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  80.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  56.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  85.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  66.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN   NaN
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  75.0
98                                    ForeProp+PT Prop+0        41.0  50.0
98                            ForeProp+PT Prop+PT Prop+0        33.0  52.0
98                                            ForeProp+0        32.0  37.0
98                                    ForeProp+PT Prop+0        32.0  43.0
98                                    ForeProp+PT Prop+0        35.0  48.0
98                                    ForeProp+PT Prop+0        32.0  51.0
98                                     ForeProp+PTProp+0        35.0  39.0
98                                   ForeProp+ForeProp+0        53.0  53.0
98                                   ForeProp+ForeProp+0        23.0  33.0
978              Bor 20/40+Welltech 16/20+Welltech 12/18         NaN  52.0
977              Bor 20/40+Welltech 16/20+Welltech 12/18         NaN  85.0
977              Bor 20/40+Welltech 16/20+Welltech 12/18         NaN  59.0

                Расход    Конц  Гель   М бр  V под   V без под  V гель
Номер скважины
99                 3.2   900.0   NaN   41.1    9.0         NaN    53.0
980                3.6   900.0   NaN  190.0   75.0  272.700000     NaN
980                3.6   900.0   NaN  182.0   65.0  260.400000     NaN
980                3.6   900.0   NaN  192.0   70.0  331.200000     NaN
980                3.6   900.0   NaN  183.0   65.0  262.000000     NaN
980                3.6   900.0   NaN  180.0   65.0  252.800000     NaN
980                NaN   800.0   NaN   15.0    NaN   30.042131     NaN
980                3.6   800.0   NaN  145.0   40.0  215.751469     NaN
98                 3.4   800.0   NaN  140.4    NaN   45.000000   151.0
98                 3.4   800.0   NaN  143.1    NaN   45.000000   151.0
98                 3.4   800.0   NaN  152.8    NaN   45.000000   151.0
98                 3.4   800.0   NaN  149.5    NaN   45.000000   151.0
98                 3.4   800.0   NaN  149.8    NaN   45.000000   151.0
98                 3.4   800.0   NaN  149.5    NaN   45.000000   151.0
98                 3.4   800.0   NaN  226.7    NaN   45.000000   120.0
98                 3.4   800.0   NaN  163.6    NaN   42.000000   144.0
98                 3.4   800.0   NaN  161.1    NaN   45.000000   151.0
978                3.4  1200.0   NaN  121.5   50.0  188.699945     NaN
977                3.6  1000.0   NaN  208.0   95.0  334.404409     NaN
977                3.4   900.0   NaN  165.0   63.0  267.207626     NaN

[20 rows x 35 columns] (2944, 35)

In [3]:
grp_gtm = pd.read_excel('two.xlsx',header=[1], index_col=[1])
print(grp_gtm.head(10),grp_gtm.shape)

C:\Users\USER\miniconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                   Unnamed: 0 Скважина Куст  \
Месторождение
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское   Нагнетательная        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN

                                                         Тип  \
Месторождение
Тайлаковское                                 ВНС из др. фонд
Тайлаковское                                             ГРП
Тайлаковское                                   Перевод в ППД
Тайлаковское   Выравнивание профиля притока или приёмистости
Тайлаковское                                 Проведение ГДИС
Тайлаковское   Выравнивание профиля притока или приёмистости
Тайлаковское                              Запуск без ремонта
Тайлаковское                              Запуск без ремонта
Тайлаковское                              Запуск без ремонта
Тайлаковское                          Промывка гибкой трубой

              Объект разработки до ГТМ  Объект разработки после ГТМ Страница  \
Месторождение
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_

               Dэк                       Краткое описание мероприятий  \
Месторождение
Тайлаковское   NaN                 КР9-5 Перевод скважин в добывающие
Тайлаковское   NaN                               КР7-2 Проведение ГРП
Тайлаковское   NaN  КР9-6 Перевод под нагнетание из других категор...
Тайлаковское   NaN                                     Проведение ВПП
Тайлаковское   NaN                     Гидродинамические исследования
Тайлаковское   NaN                                     Проведение ВПП
Тайлаковское   NaN                        Запуск в работу без ремонта
Тайлаковское   NaN                        Запуск в работу без ремонта
Тайлаковское   NaN                        Запуск в работу без ремонта
Тайлаковское   NaN                             Промывка гибкой трубой

               Unnamed: 10  ...  Напор.1  Производительность.1  Комментарий  \
Месторождение               ...
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN

               План  Факт  Пл-ть нефти  Коб  В-ть жидк.  P нас  Unnamed: 65
Месторождение
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN

[10 rows x 65 columns] (17163, 65)

In [4]:
coordinates = pd.read_excel('three.xlsx')
print(coordinates.head(10),coordinates.shape)

  № скважины  Координата X  Координата Y  Координата забоя Х (по траектории)  \
0          1        430902       6562954                              430903
1         10        437823       6547130                              437826
2        100        434596       6559294                              434070
3       1000        435618       6555935                              435597
4       1004        455990       6565368                              456033
5       1005        455105       6565028                              455102
6       1006        456303       6565179                              456326
7       1007        455815       6565717                              455823
8      100ПЛ        434353       6559493                              434352
9        101        434378       6559105                              433680

   Координата забоя Y (по траектории)
0                             6562958
1                             6547128
2                             6559895
3                             6555955
4                             6565408
5                             6565045
6                             6565200
7                             6565751
8                             6559493
9                             6559690   (1560, 5)

In [5]:
grp_dad.reset_index(drop=True)
grp_dad.reset_index(inplace=True)

In [6]:
#вставка 22.02.22
grp_dad['Номер скважины'] = grp_dad.apply(
            lambda x:
            str(x['Номер скважины']), axis=1)
grp_gtm['Скважина'] = grp_gtm.apply(
            lambda x:
            str(x['Скважина']), axis=1)
        #вставка 22.02.22

In [7]:
plasttt = 'Ю3'
grp_dad['удалю'] = grp_dad.apply(
            lambda x:
            'нет' if plasttt in str(x['Пласт'])
            else 'да', axis=1)
grp_dad = grp_dad.drop(grp_dad[grp_dad['удалю'] == 'да'].index).reset_index(drop=True)
grp_dad = grp_dad.drop(['удалю'], axis=1)
grp_gtm.reset_index(drop=True)
grp_gtm.reset_index(inplace=True)
grp_gtm = grp_gtm[grp_gtm['Объект разработки до ГТМ'].notna()]
grp_dad.head(10)

,Номер скважины,Unnamed: 0,Дата,Подрядчик,Комментарии,Страница,Unnamed: 6,Пласт,Наклон,Азимут,...,Проппант,Рпл Хорнер,Эфф,Расход,Конц,Гель,М бр,V под,V без под,V гель
0,99,Проблемы при построении ГРП,2019-10-20,КН,"Оборудование: НКТ, ПРО, АМТ- ООО ""КАТКонефть...",-1_,NaN,Ю3,17.0,245.0,...,NIKA (Ptprop)+Fores+Fores,48.0,71.0,3.2,900.0,NaN,41.10000,9.0,NaN,53.0
1,96,Проблемы при построении ГРП,2019-06-20,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,7.0,152.0,...,НИК20/40+НИК16/20+НИК12/18,45.0,63.0,3.6,800.0,NaN,241.37000,32.0,NaN,165.0
2,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Fores+Nika+Nika+0+0,60.0,37.0,3.6,1000.0,NaN,45.95220,NaN,NaN,71.5
3,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Fores+Nika+Nika+0+0,62.0,31.5,3.6,1000.0,NaN,40.47128,NaN,NaN,54.8
4,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Fores+Nika+Nika+0+0,58.0,36.0,3.6,1000.0,NaN,41.01312,NaN,NaN,53.8
5,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Fores+Nika+0+0+0,42.5,48.7,3.4,1000.0,NaN,39.30424,NaN,NaN,50.8
6,949,Проблемы при построении ГРП,2021-09-14,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Nika+Fores+Nika+0+0,44.5,56.6,3.4,800.0,NaN,70.37668,NaN,NaN,59.6
7,924,Проблемы при построении ГРП,2012-09-09,МКН,"По миниГРП: увеличили стадию ""подушка"" до 5...",-1_,NaN,Ю3,15.1,9.0,...,16/20+12/18+12/18,256.0,45.0,3.5,1200.0,NaN,NaN,52.0,210.9,NaN
8,923,NaN,2011-01-12,ШЛБ,NaN,-1_,NaN,Ю3,20.0,NaN,...,16/20Fore \n12/18Fore \n12/18ForeRCP,228.0,38.2,2.6,1024.0,NaN,NaN,60.0,216.3,NaN
9,911,Проблемы при построении ГРП,2015-03-11,КН,Мини ГРП проводился 12.03.2015 г. По результат...,-1_,NaN,Ю3,89.4,1.0,...,Bor 20/40+Welltech-Bor 16/20+Welltech-Bo,NaN,28.0,3.8,900.0,NaN,232.00000,100.0,392.4,NaN

In [8]:
plastt = 'Ю3'
grp_gtm = grp_gtm.drop(grp_gtm[grp_gtm['Объект разработки до ГТМ'] != plastt].index).reset_index(drop=True)
grp_gtm.head(10)

,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,Краткое описание мероприятий,...,Напор.1,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65
0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,КР9-5 Перевод скважин в добывающие,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,КР7-2 Проведение ГРП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,КР9-6 Перевод под нагнетание из других категор...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,Гидродинамические исследования,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Тайлаковское,Добывающая,1,NaN,Промывка гибкой трубой,Ю3,NaN,-1_,NaN,Промывка гибкой трубой,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
coordinates['Length'] = coordinates.apply(
            lambda x: ((x['Координата забоя Х (по траектории)'] - x['Координата X']) ** (2) +
                       (x['Координата забоя Y (по траектории)'] - x['Координата Y']) ** (2)) ** (0.5)
            , axis=1)
coordinates['№ скважины'] = coordinates.apply(
            lambda x:
            str(x['№ скважины']), axis=1)
grp = copy.deepcopy(grp_dad)
coordinates.head(10)

,№ скважины,Координата X,Координата Y,Координата забоя Х (по траектории),Координата забоя Y (по траектории),Length
0,1,430902,6562954,430903,6562958,4.123106
1,10,437823,6547130,437826,6547128,3.605551
2,100,434596,6559294,434070,6559895,798.672023
3,1000,435618,6555935,435597,6555955,29.000000
4,1004,455990,6565368,456033,6565408,58.728187
5,1005,455105,6565028,455102,6565045,17.262677
6,1006,456303,6565179,456326,6565200,31.144823
7,1007,455815,6565717,455823,6565751,34.928498
8,100ПЛ,434353,6559493,434352,6559493,1.000000
9,101,434378,6559105,433680,6559690,910.729927

In [10]:
grp_now_we_go = copy.deepcopy(grp_gtm)
grp_now_we_go['Скважина'] = grp_now_we_go.apply(
            lambda x:
            str(x['Скважина']), axis=1)
grp_now_we_go.head(10)

,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,Краткое описание мероприятий,...,Напор.1,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65
0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,КР9-5 Перевод скважин в добывающие,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,КР7-2 Проведение ГРП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,КР9-6 Перевод под нагнетание из других категор...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,Гидродинамические исследования,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Тайлаковское,Добывающая,1,NaN,Промывка гибкой трубой,Ю3,NaN,-1_,NaN,Промывка гибкой трубой,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
grp['Номер скважины'] = grp.apply(
            lambda x:
            str(x['Номер скважины']), axis=1)
        # координаты скважин для нашего объекта
my_wells = grp['Номер скважины'].tolist()
my_wells_no_repeat = []
for x in my_wells:
    if x not in my_wells_no_repeat:
        my_wells_no_repeat.append(x)
my_wells_no_repeat

['99',
 '96',
 '949',
 '924',
 '923',
 '911',
 '909',
 '906Л',
 '905',
 '9',
 '898',
 '897',
 '890',
 '883',
 '882',
 '881',
 '880',
 '878',
 '876',
 '874',
 '870',
 '87',
 '85Л1',
 '84',
 '820',
 '806',
 '80',
 '8',
 '773',
 '771',
 '770Л',
 '770',
 '77',
 '768',
 '767',
 '766',
 '764',
 '763Л',
 '763',
 '762',
 '761',
 '760',
 '76',
 '757',
 '755',
 '74',
 '739',
 '738Л2',
 '738',
 '737',
 '732',
 '731',
 '729',
 '728',
 '727',
 '726',
 '725',
 '724',
 '723',
 '722',
 '721',
 '720',
 '72',
 '714',
 '713',
 '711',
 '71',
 '708',
 '70',
 '7',
 '68Л',
 '686',
 '681',
 '680',
 '68',
 '679',
 '678',
 '675',
 '673',
 '665',
 '663',
 '662',
 '66',
 '655',
 '650',
 '649',
 '648',
 '647',
 '640',
 '637',
 '636',
 '635',
 '63',
 '629',
 '628',
 '627',
 '626',
 '622',
 '621',
 '620',
 '619Л2',
 '619',
 '617',
 '616',
 '613',
 '612',
 '61',
 '606',
 '604',
 '603',
 '602',
 '601',
 '60',
 '6',
 '5Л',
 '591',
 '585',
 '584',
 '582Л2',
 '582',
 '581',
 '577',
 '574',
 '573',
 '572',
 '571',
 '570',
 '57',
 '569',
 '567Л',
 '5676',
 '567',
 '56',
 '550',
 '549',
 '542',
 '541',
 '539',
 '537',
 '534',
 '53',
 '529',
 '527Л',
 '526',
 '515',
 '509',
 '507',
 '505',
 '503',
 '500',
 '498',
 '497',
 '496',
 '494',
 '492',
 '491',
 '489Л2',
 '489',
 '488',
 '487',
 '486',
 '485',
 '484',
 '483',
 '480',
 '48',
 '479',
 '478',
 '472',
 '471',
 '470',
 '469',
 '465',
 '464',
 '4630',
 '4627',
 '4625',
 '459',
 '458',
 '457',
 '455',
 '454',
 '451',
 '449',
 '441',
 '437',
 '436',
 '434',
 '433Л',
 '433',
 '431',
 '4306',
 '4305',
 '4302',
 '4301',
 '429',
 '428',
 '425',
 '424',
 '421',
 '415Л',
 '415',
 '412',
 '410',
 '40',
 '4',
 '39',
 '385',
 '383',
 '3825',
 '3821',
 '3781',
 '3780',
 '3742',
 '3702',
 '3701',
 '37',
 '3635',
 '3630',
 '36',
 '3552',
 '35',
 '33ПЛ',
 '31',
 '306',
 '300ПЛ',
 '30',
 '3',
 '2818Л',
 '28',
 '276',
 '27',
 '2640',
 '26',
 '258',
 '25',
 '24',
 '23Л',
 '2310',
 '2306',
 '2305',
 '2304',
 '2303',
 '2302',
 '2301',
 '2300',
 '23',
 '22',
 '21',
 '207',
 '202',
 '20',
 '1980',
 '1977',
 '1972',
 '197',
 '195',
 '194',
 '1910',
 '1909',
 '1908',
 '1906',
 '1903',
 '1902',
 '1901Л',
 '1901',
 '1900',
 '186',
 '18',
 '17Л',
 '1758',
 '1756',
 '173РЛ',
 '17',
 '1641',
 '1640',
 '1639',
 '1638',
 '1637Л',
 '1637',
 '1636',
 '1635Л',
 '1635',
 '1634',
 '1633',
 '1632',
 '1628',
 '1626',
 '1625',
 '1623',
 '1622Л',
 '1622',
 '1621',
 '1620',
 '162',
 '1610',
 '1608',
 '1607',
 '1606',
 '1605',
 '1603Л',
 '1602',
 '16',
 '158',
 '1562',
 '1561',
 '1560',
 '1559',
 '1557',
 '1556',
 '1551',
 '1549Л',
 '1549',
 '154',
 '153',
 '1523',
 '151Л',
 '1513',
 '1511',
 '151',
 '1507',
 '1503',
 '1502',
 '1501',
 '1500',
 '150',
 '15',
 '149',
 '148',
 '1468',
 '146',
 '144',
 '1433',
 '143',
 '142Л',
 '142',
 '141',
 '140',
 '14',
 '139',
 '1385',
 '1383',
 '1367',
 '1366',
 '1349',
 '1345',
 '1344',
 '1341',
 '133',
 '1320',
 '1311',
 '131',
 '1304',
 '1300',
 '130',
 '13',
 '128',
 '1259',
 '123Л',
 '123',
 '1223',
 '1220',
 '12',
 '119',
 '1160',
 '1129',
 '1128',
 '1126',
 '1124',
 '1123',
 '1122',
 '1114',
 '1113',
 '1112',
 '1111',
 '11',
 '1082',
 '1006',
 '1004',
 '10',
 '1']

In [12]:
my_wells_gtm = grp_now_we_go['Скважина'].tolist()
my_wells_no_repeat_gtm = []
for x in my_wells_gtm:
    if x not in my_wells_no_repeat_gtm:
        my_wells_no_repeat_gtm.append(x)

my_wells_only_gtm = []
for i in my_wells_no_repeat_gtm:
    if i not in my_wells_no_repeat:
            my_wells_only_gtm.append(i)
my_wells_only_gtm

['1005',
 '1007',
 '1018',
 '105',
 '1081',
 '1092',
 '110',
 '1125',
 '1176',
 '122',
 '1221',
 '1224',
 '1230',
 '1232',
 '124',
 '126',
 '1260',
 '1270',
 '1272',
 '1279',
 '1289',
 '1290',
 '1291',
 '1302',
 '1303',
 '1312',
 '1334',
 '137',
 '1381',
 '1384',
 '1386',
 '145',
 '147',
 '1504',
 '1505',
 '1506',
 '1508',
 '1521',
 '1522',
 '1544',
 '155',
 '1550',
 '1555',
 '1556Л',
 '1576',
 '1595',
 '1603',
 '1609',
 '1611',
 '1630',
 '1631',
 '173Р',
 '181',
 '183',
 '19',
 '190',
 '196',
 '1970',
 '1973',
 '1974',
 '1976',
 '1978',
 '1979',
 '198',
 '199',
 '201',
 '204',
 '2056',
 '206',
 '209',
 '211Р',
 '215Р',
 '2309',
 '256Р',
 '2600',
 '2686',
 '2688',
 '2818',
 '29',
 '2969',
 '300',
 '304',
 '3093',
 '32',
 '33',
 '34',
 '3551',
 '3632',
 '3633',
 '3700',
 '3703',
 '38',
 '3817',
 '382',
 '3820',
 '3822',
 '3827',
 '3828',
 '3829',
 '3864',
 '395',
 '405',
 '406',
 '4100',
 '4101',
 '413',
 '417',
 '419',
 '42',
 '420',
 '4221',
 '423',
 '426',
 '427',
 '430',
 '4300',
 '432',
 '435',
 '438',
 '439',
 '440',
 '444',
 '445',
 '446',
 '447',
 '45',
 '450',
 '453',
 '456',
 '460',
 '462',
 '463',
 '466',
 '467',
 '468',
 '47',
 '473',
 '474',
 '475',
 '476',
 '477',
 '481',
 '482',
 '490',
 '493',
 '495',
 '499',
 '5',
 '501',
 '502',
 '504',
 '506',
 '540',
 '544',
 '55',
 '552',
 '554',
 '557',
 '563',
 '575',
 '578',
 '579',
 '580',
 '583',
 '588',
 '596',
 '598',
 '599',
 '608',
 '609',
 '610',
 '611',
 '614',
 '615',
 '618',
 '62',
 '632',
 '638',
 '641',
 '644',
 '65',
 '651',
 '656',
 '667',
 '682',
 '683',
 '69',
 '705',
 '707',
 '710',
 '712',
 '715',
 '73',
 '730',
 '733',
 '734',
 '735',
 '741',
 '743',
 '748',
 '752',
 '754',
 '756',
 '758',
 '769',
 '781',
 '79',
 '83',
 '85',
 '86',
 '896',
 '901',
 '904',
 '906',
 '907',
 '908',
 '910',
 '916',
 '918',
 '919',
 '922',
 '926',
 '927',
 '936',
 '942',
 '971']

In [13]:
wells_GTM = pd.DataFrame({"Номер скважины": my_wells_only_gtm
                                  })
coordinates_f = coordinates[
            coordinates['№ скважины'].isin(my_wells_no_repeat)].reset_index(drop=True)
coordinates_f = coordinates_f.drop(['Координата X', 'Координата Y', 'Координата забоя Х (по траектории)',
                                            'Координата забоя Y (по траектории)'], axis=1)
new = coordinates_f['№ скважины'].tolist()
coordinates_f['Номер скважины'] = new
coordinates_f = coordinates_f.drop(['№ скважины'], axis=1)
final = grp.merge(coordinates_f, on='Номер скважины')
final

,Номер скважины,Unnamed: 0,Дата,Подрядчик,Комментарии,Страница,Unnamed: 6,Пласт,Наклон,Азимут,...,Рпл Хорнер,Эфф,Расход,Конц,Гель,М бр,V под,V без под,V гель,Length
0,99,Проблемы при построении ГРП,2019-10-20,КН,"Оборудование: НКТ, ПРО, АМТ- ООО ""КАТКонефть...",-1_,NaN,Ю3,17.0,245.0,...,48.0,71.0,3.2,900.0,NaN,41.10000,9.0,NaN,53.0,34.365681
1,96,Проблемы при построении ГРП,2019-06-20,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,7.0,152.0,...,45.0,63.0,3.6,800.0,NaN,241.37000,32.0,NaN,165.0,14.560220
2,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,60.0,37.0,3.6,1000.0,NaN,45.95220,NaN,NaN,71.5,343.052474
3,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,62.0,31.5,3.6,1000.0,NaN,40.47128,NaN,NaN,54.8,343.052474
4,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,58.0,36.0,3.6,1000.0,NaN,41.01312,NaN,NaN,53.8,343.052474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,1082,Проблемы при построении ГРП,2020-02-07,МКМ,"ГРП по плану (+), 42 т. Выполнена стадия Запо...",-1_,NaN,Ю3,20.0,305.0,...,49.0,74.8,3.6,800.0,NaN,50.00000,35.0,NaN,145.0,36.769553
1044,1006,Проблемы при построении ГРП,2019-07-26,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,22.0,40.0,...,61.0,43.0,3.4,800.0,NaN,133.24063,NaN,5.0,73.0,31.144823
1045,1004,Проблемы при построении ГРП,2013-01-03,ШЛБ,По результатам МиниГРП масса пропанта по перво...,-1_,NaN,Ю3,40.0,34.0,...,200.0,32.0,3.8,890.0,NaN,NaN,110.0,367.3,NaN,58.728187
1046,10,NaN,2013-02-16,ШЛБ,При проведении работ по ГРП 16/02/2013 закачка...,-1_,NaN,Ю3,2.0,NaN,...,235.0,73.0,2.6,1056.0,NaN,NaN,14.0,100.0,NaN,3.605551
1047,1,Проблемы при построении ГРП,2016-02-23,КН,Мини ГРП проводился 23.02.2016 г. По результат...,-1_,NaN,Ю3,1.0,NaN,...,NaN,43.0,3.4,1200.0,NaN,85.00000,30.0,154.4,NaN,4.123106

In [14]:
coordinates_f = coordinates[
            coordinates['№ скважины'].isin(my_wells_no_repeat)].reset_index(drop=True)
coordinates_f = coordinates_f.drop(['Координата X', 'Координата Y', 'Координата забоя Х (по траектории)',
                                        'Координата забоя Y (по траектории)'], axis=1)
new = coordinates_f['№ скважины'].tolist()
coordinates_f['Номер скважины'] = new
coordinates_f = coordinates_f.drop(['№ скважины'], axis=1)
final = grp.merge(coordinates_f, on='Номер скважины')
final

,Номер скважины,Unnamed: 0,Дата,Подрядчик,Комментарии,Страница,Unnamed: 6,Пласт,Наклон,Азимут,...,Рпл Хорнер,Эфф,Расход,Конц,Гель,М бр,V под,V без под,V гель,Length
0,99,Проблемы при построении ГРП,2019-10-20,КН,"Оборудование: НКТ, ПРО, АМТ- ООО ""КАТКонефть...",-1_,NaN,Ю3,17.0,245.0,...,48.0,71.0,3.2,900.0,NaN,41.10000,9.0,NaN,53.0,34.365681
1,96,Проблемы при построении ГРП,2019-06-20,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,7.0,152.0,...,45.0,63.0,3.6,800.0,NaN,241.37000,32.0,NaN,165.0,14.560220
2,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,60.0,37.0,3.6,1000.0,NaN,45.95220,NaN,NaN,71.5,343.052474
3,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,62.0,31.5,3.6,1000.0,NaN,40.47128,NaN,NaN,54.8,343.052474
4,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,58.0,36.0,3.6,1000.0,NaN,41.01312,NaN,NaN,53.8,343.052474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,1082,Проблемы при построении ГРП,2020-02-07,МКМ,"ГРП по плану (+), 42 т. Выполнена стадия Запо...",-1_,NaN,Ю3,20.0,305.0,...,49.0,74.8,3.6,800.0,NaN,50.00000,35.0,NaN,145.0,36.769553
1044,1006,Проблемы при построении ГРП,2019-07-26,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,22.0,40.0,...,61.0,43.0,3.4,800.0,NaN,133.24063,NaN,5.0,73.0,31.144823
1045,1004,Проблемы при построении ГРП,2013-01-03,ШЛБ,По результатам МиниГРП масса пропанта по перво...,-1_,NaN,Ю3,40.0,34.0,...,200.0,32.0,3.8,890.0,NaN,NaN,110.0,367.3,NaN,58.728187
1046,10,NaN,2013-02-16,ШЛБ,При проведении работ по ГРП 16/02/2013 закачка...,-1_,NaN,Ю3,2.0,NaN,...,235.0,73.0,2.6,1056.0,NaN,NaN,14.0,100.0,NaN,3.605551
1047,1,Проблемы при построении ГРП,2016-02-23,КН,Мини ГРП проводился 23.02.2016 г. По результат...,-1_,NaN,Ю3,1.0,NaN,...,NaN,43.0,3.4,1200.0,NaN,85.00000,30.0,154.4,NaN,4.123106

In [15]:
final['Длиина ГС, м'] = final.apply(
            lambda x:
            x['Length'] if x['Наклон'] >= 70
            else 0, axis=1)
final = final.drop(['Наклон', 'Length'], axis=1)
final_number = final.groupby('Номер скважины').agg(
            {'Дата': lambda x:
            x.tolist()}
        )
final_number

                                                             Дата
Номер скважины
1                                           [2016-02-23 00:00:00]
10                                          [2013-02-16 00:00:00]
1004                                        [2013-01-03 00:00:00]
1006                                        [2019-07-26 00:00:00]
1082                                        [2020-02-07 00:00:00]
...                                                           ...
923                                         [2011-01-12 00:00:00]
924                                         [2012-09-09 00:00:00]
949             [2021-09-15 00:00:00, 2021-09-15 00:00:00, 202...
96                                          [2019-06-20 00:00:00]
99                                          [2019-10-20 00:00:00]

[381 rows x 1 columns]

In [16]:
final

,Номер скважины,Unnamed: 0,Дата,Подрядчик,Комментарии,Страница,Unnamed: 6,Пласт,Азимут,k,...,Рпл Хорнер,Эфф,Расход,Конц,Гель,М бр,V под,V без под,V гель,"Длиина ГС, м"
0,99,Проблемы при построении ГРП,2019-10-20,КН,"Оборудование: НКТ, ПРО, АМТ- ООО ""КАТКонефть...",-1_,NaN,Ю3,245.0,24.6,...,48.0,71.0,3.2,900.0,NaN,41.10000,9.0,NaN,53.0,0.000000
1,96,Проблемы при построении ГРП,2019-06-20,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,152.0,17.4,...,45.0,63.0,3.6,800.0,NaN,241.37000,32.0,NaN,165.0,0.000000
2,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,305.1,5.1,...,60.0,37.0,3.6,1000.0,NaN,45.95220,NaN,NaN,71.5,343.052474
3,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,305.1,5.1,...,62.0,31.5,3.6,1000.0,NaN,40.47128,NaN,NaN,54.8,343.052474
4,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,305.1,5.1,...,58.0,36.0,3.6,1000.0,NaN,41.01312,NaN,NaN,53.8,343.052474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,1082,Проблемы при построении ГРП,2020-02-07,МКМ,"ГРП по плану (+), 42 т. Выполнена стадия Запо...",-1_,NaN,Ю3,305.0,17.2,...,49.0,74.8,3.6,800.0,NaN,50.00000,35.0,NaN,145.0,0.000000
1044,1006,Проблемы при построении ГРП,2019-07-26,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,40.0,15.0,...,61.0,43.0,3.4,800.0,NaN,133.24063,NaN,5.0,73.0,0.000000
1045,1004,Проблемы при построении ГРП,2013-01-03,ШЛБ,По результатам МиниГРП масса пропанта по перво...,-1_,NaN,Ю3,34.0,4.0,...,200.0,32.0,3.8,890.0,NaN,NaN,110.0,367.3,NaN,0.000000
1046,10,NaN,2013-02-16,ШЛБ,При проведении работ по ГРП 16/02/2013 закачка...,-1_,NaN,Ю3,NaN,10.0,...,235.0,73.0,2.6,1056.0,NaN,NaN,14.0,100.0,NaN,0.000000
1047,1,Проблемы при построении ГРП,2016-02-23,КН,Мини ГРП проводился 23.02.2016 г. По результат...,-1_,NaN,Ю3,NaN,5.0,...,NaN,43.0,3.4,1200.0,NaN,85.00000,30.0,154.4,NaN,0.000000

In [17]:
coordinates_gtm = coordinates[
            coordinates['№ скважины'].isin(my_wells_only_gtm)].reset_index(drop=True)
        #!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
coordinates_gtm = coordinates_gtm.drop(['Координата X', 'Координата Y', 'Координата забоя Х (по траектории)',
                                                'Координата забоя Y (по траектории)'], axis=1)
new_g = coordinates_gtm['№ скважины'].tolist()
coordinates_gtm['Номер скважины'] = new_g
coordinates_gtm = coordinates_gtm.drop(['№ скважины'], axis=1)
coordinates_gtm

         Length Номер скважины
0     17.262677           1005
1     34.928498           1007
2     31.144823           1018
3     17.204651            105
4     34.655447           1081
..          ...            ...
221   19.235384            926
222   13.152946            927
223    2.236068            936
224   21.931712            942
225  762.377859            971

[226 rows x 2 columns]

In [18]:
wells_GTM = wells_GTM.merge(coordinates_gtm, on='Номер скважины')
wells_GTM['Длина ГС, м'] = wells_GTM.apply(
        lambda x:
        x['Length'] if x['Length'] >= 110
        else 0, axis=1)
wells_GTM = wells_GTM.drop(['Length'], axis=1)
wells_GTM

    Номер скважины  Длина ГС, м
0             1005     0.000000
1             1007     0.000000
2             1018     0.000000
3              105     0.000000
4             1081     0.000000
..             ...          ...
221            926     0.000000
222            927     0.000000
223            936     0.000000
224            942     0.000000
225            971   762.377859

[226 rows x 2 columns]

In [19]:
grp_ggtm = copy.deepcopy(grp_gtm)
grp_ggtm.reset_index(drop=True)
grp_ggtm.reset_index(inplace=True)
grp_ggtm['Скважина'] = grp_ggtm.apply(
            lambda x:
            str(x['Скважина']), axis=1)
grp_ggtm = grp_ggtm[grp_ggtm['Скважина'].isin(my_wells_only_gtm)].reset_index(drop=True)
grp_ggtm

,index,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,...,Напор.1,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65
0,35,Тайлаковское,Добывающая,1005,КУСТ-62,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,36,Тайлаковское,Добывающая,1005,КУСТ-62,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,37,Тайлаковское,Нагнетательная,1005,КУСТ-62,Перевод в ППД,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38,Тайлаковское,Добывающая,1005,КУСТ-62,ОПЗ,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,39,Тайлаковское,Добывающая,1005,КУСТ-62,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1976,4909,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1977,4910,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1978,4911,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1979,4917,Тайлаковское,Добывающая,971,КУСТ-10,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,4918,Тайлаковское,Добывающая,971,КУСТ-10,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
grp_ggtm['ВНР.1']

0      2011-08-31
1      2011-08-31
2      2011-10-09
3      2017-08-21
4      2019-01-06
          ...
1976   2021-03-30
1977   2021-03-31
1978   2021-05-30
1979   2012-04-19
1980   2013-01-23
Name: ВНР.1, Length: 1981, dtype: datetime64[ns]

In [21]:
grp_gang = copy.deepcopy(grp_ggtm)
grp_gang['Дата ВНР после'] = grp_gang.apply(
            lambda x:
            x['ВНР.1'] if 'КР7-2' in str(x['Краткое описание мероприятий'])
            else x['ВНР.1'] if 'Ввод добывающих сква' in str(x['Краткое описание мероприятий'])
            else 'нет', axis=1)
grp_gang

,index,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,...,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65,Дата ВНР после
0,35,Тайлаковское,Добывающая,1005,КУСТ-62,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-31 00:00:00
1,36,Тайлаковское,Добывающая,1005,КУСТ-62,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-31 00:00:00
2,37,Тайлаковское,Нагнетательная,1005,КУСТ-62,Перевод в ППД,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет
3,38,Тайлаковское,Добывающая,1005,КУСТ-62,ОПЗ,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-08-21 00:00:00
4,39,Тайлаковское,Добывающая,1005,КУСТ-62,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1976,4909,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет
1977,4910,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет
1978,4911,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет
1979,4917,Тайлаковское,Добывающая,971,КУСТ-10,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-04-19 00:00:00
1980,4918,Тайлаковское,Добывающая,971,КУСТ-10,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-01-23 00:00:00

In [22]:
grp_gang['Тип ГТМ'] = grp_gang.apply(
            lambda x:
            'ГРП' if 'КР7-2' in str(x['Краткое описание мероприятий'])
            else 'ВНС' if 'Ввод добывающих сква' in str(x['Краткое описание мероприятий'])
            else 'нет', axis=1)
grp_gang

,index,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,...,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65,Дата ВНР после,Тип ГТМ
0,35,Тайлаковское,Добывающая,1005,КУСТ-62,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-31 00:00:00,ГРП
1,36,Тайлаковское,Добывающая,1005,КУСТ-62,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-31 00:00:00,ВНС
2,37,Тайлаковское,Нагнетательная,1005,КУСТ-62,Перевод в ППД,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет,нет
3,38,Тайлаковское,Добывающая,1005,КУСТ-62,ОПЗ,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-08-21 00:00:00,ГРП
4,39,Тайлаковское,Добывающая,1005,КУСТ-62,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет,нет
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1976,4909,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет,нет
1977,4910,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет,нет
1978,4911,Тайлаковское,Добывающая,942,КУСТ-8,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,нет,нет
1979,4917,Тайлаковское,Добывающая,971,КУСТ-10,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-04-19 00:00:00,ВНС
1980,4918,Тайлаковское,Добывающая,971,КУСТ-10,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-01-23 00:00:00,ГРП

In [23]:
grp_gang = grp_gang.drop(grp_gang[grp_gang['Дата ВНР после'] == 'нет'].index)
grp_gang

,index,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,...,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65,Дата ВНР после,Тип ГТМ
0,35,Тайлаковское,Добывающая,1005,КУСТ-62,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-31 00:00:00,ГРП
1,36,Тайлаковское,Добывающая,1005,КУСТ-62,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-31 00:00:00,ВНС
3,38,Тайлаковское,Добывающая,1005,КУСТ-62,ОПЗ,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-08-21 00:00:00,ГРП
9,52,Тайлаковское,Добывающая,1007,КУСТ-62,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-28 00:00:00,ВНС
27,70,Тайлаковское,Добывающая,105,КУСТ-7,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-08-27 00:00:00,ВНС
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1955,4888,Тайлаковское,Добывающая,936,КУСТ-7,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-09-27 00:00:00,ГРП
1956,4889,Тайлаковское,Добывающая,936,КУСТ-7,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-09-27 00:00:00,ВНС
1959,4892,Тайлаковское,Добывающая,942,КУСТ-8,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-06-19 00:00:00,ГРП
1979,4917,Тайлаковское,Добывающая,971,КУСТ-10,ВНС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-04-19 00:00:00,ВНС
1980,4918,Тайлаковское,Добывающая,971,КУСТ-10,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-01-23 00:00:00,ГРП

In [24]:
grp_gang = grp_gang.groupby(by=['Скважина', 'Дата ВНР после']).agg(
            {'Тип ГТМ': lambda x:
            x.tolist()[0]}
        )
grp_gang.reset_index(inplace=True)

In [25]:
grp_gang

    Скважина Дата ВНР после Тип ГТМ
0       1005     2011-08-31     ГРП
1       1005     2017-08-21     ГРП
2       1007     2010-10-28     ВНС
3        105     2008-08-27     ВНС
4        105     2010-10-23     ГРП
..       ...            ...     ...
230      927     2014-10-26     ГРП
231      936     2008-09-27     ГРП
232      942     2013-06-19     ГРП
233      971     2012-04-19     ВНС
234      971     2013-01-23     ГРП

[235 rows x 3 columns]

In [26]:
grp_gang['index'] = grp_gang.index
grp_vnski_double = grp_gang.drop(grp_gang[grp_gang['Тип ГТМ'] != 'ВНС'].index)
grp_vnski_double['index'] = grp_vnski_double.index
grp_vnski_double = grp_vnski_double.groupby('Скважина').agg(
            {'index': lambda x:
            x.tolist()[1:]}
        )
sveta = []
for i in grp_vnski_double['index']:
    sveta += i
grp_gang = grp_gang[~grp_gang['index'].isin(sveta)].reset_index(drop=True)
grp_gang = grp_gang.drop(['index'], axis=1)
grp_gang

    Скважина Дата ВНР после Тип ГТМ
0       1005     2011-08-31     ГРП
1       1005     2017-08-21     ГРП
2       1007     2010-10-28     ВНС
3        105     2008-08-27     ВНС
4        105     2010-10-23     ГРП
..       ...            ...     ...
228      927     2014-10-26     ГРП
229      936     2008-09-27     ГРП
230      942     2013-06-19     ГРП
231      971     2012-04-19     ВНС
232      971     2013-01-23     ГРП

[233 rows x 3 columns]

In [27]:
        # GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
vvvvv = grp_gang['Скважина'].tolist()

grp_gang['Номер скважины'] = vvvvv
grp_gang = grp_gang.drop(['Скважина'], axis=1)
        # !!!!!!!!!!!!!!!!!!!!!!!!
grp_gang['Полудлина трещины, м'] = grp_gang.apply(
            lambda x:
            100, axis=1)
grp_gang['Ширина трещины, мм'] = grp_gang.apply(
            lambda x:
            4, axis=1)
grp_gang['Проницаемость проппанта, Д'] = grp_gang.apply(
            lambda x:
            100, axis=1)
grp_gang['Полудлина трещины, м'] = grp_gang.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Полудлина трещины, м']
            , axis=1)
grp_gang['Ширина трещины, мм'] = grp_gang.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Ширина трещины, мм']
            , axis=1)
grp_gang['Проницаемость проппанта, Д'] = grp_gang.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Проницаемость проппанта, Д']
            , axis=1)
        # ДОБАВИТЬ В ВНС
grp_gang['Число стадий ГРП'] = grp_gang.apply(
            lambda x:
            1, axis=1)
grp_gang['Число стадий ГРП'] = grp_gang.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Число стадий ГРП']
            , axis=1)
grp_gang

,Дата ВНР после,Тип ГТМ,Номер скважины,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Число стадий ГРП
0,2011-08-31,ГРП,1005,100,4,100,1
1,2017-08-21,ГРП,1005,100,4,100,1
2,2010-10-28,ВНС,1007,0,0,0,0
3,2008-08-27,ВНС,105,0,0,0,0
4,2010-10-23,ГРП,105,100,4,100,1
...,...,...,...,...,...,...,...
228,2014-10-26,ГРП,927,100,4,100,1
229,2008-09-27,ГРП,936,100,4,100,1
230,2013-06-19,ГРП,942,100,4,100,1
231,2012-04-19,ВНС,971,0,0,0,0
232,2013-01-23,ГРП,971,100,4,100,1

In [28]:
wells_GTM = wells_GTM.merge(grp_gang, on='Номер скважины')
wells_GTM

,Номер скважины,"Длина ГС, м",Дата ВНР после,Тип ГТМ,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Число стадий ГРП
0,1005,0.000000,2011-08-31,ГРП,100,4,100,1
1,1005,0.000000,2017-08-21,ГРП,100,4,100,1
2,1007,0.000000,2010-10-28,ВНС,0,0,0,0
3,105,0.000000,2008-08-27,ВНС,0,0,0,0
4,105,0.000000,2010-10-23,ГРП,100,4,100,1
...,...,...,...,...,...,...,...,...
228,927,0.000000,2014-10-26,ГРП,100,4,100,1
229,936,0.000000,2008-09-27,ГРП,100,4,100,1
230,942,0.000000,2013-06-19,ГРП,100,4,100,1
231,971,762.377859,2012-04-19,ВНС,0,0,0,0
232,971,762.377859,2013-01-23,ГРП,100,4,100,1

In [29]:
wells_GTM['ГС/ННС'] = wells_GTM.apply(
            lambda x:
            'ННС' if x['Длина ГС, м'] == 0
            else 'ГС', axis=1)
        # редактируем его в зависимости от наличия грп
wells_GTM['ГС/ННС'] = wells_GTM.apply(
            lambda x:
            str(x['ГС/ННС']) + '+ГРП' if str(x['Тип ГТМ']) == 'ГРП'
            else x['ГС/ННС'], axis=1)
new_400 = wells_GTM['Номер скважины'].tolist()
wells_GTM['Скважина №'] = new_400
wells_GTM = wells_GTM.drop(['Номер скважины'], axis=1)
wells_GTM['Пласт'] = wells_GTM.apply(
            lambda x:
            plastt, axis=1)
wells_GTM = wells_GTM.reindex(
            columns=['Скважина №', 'Длина ГС, м', 'Число стадий ГРП', 'Полудлина трещины, м', 'Ширина трещины, мм',
                     'Проницаемость проппанта, Д', 'Дата ВНР после ГС \ ГРП \ЗБГС', 'ГС/ННС', 'Тип ГТМ', 'Пласт'])

In [30]:
wells_GTM

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после ГС \ ГРП \ЗБГС,ГС/ННС,Тип ГТМ,Пласт
0,1005,0.000000,1,100,4,100,NaN,ННС+ГРП,ГРП,Ю3
1,1005,0.000000,1,100,4,100,NaN,ННС+ГРП,ГРП,Ю3
2,1007,0.000000,0,0,0,0,NaN,ННС,ВНС,Ю3
3,105,0.000000,0,0,0,0,NaN,ННС,ВНС,Ю3
4,105,0.000000,1,100,4,100,NaN,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
228,927,0.000000,1,100,4,100,NaN,ННС+ГРП,ГРП,Ю3
229,936,0.000000,1,100,4,100,NaN,ННС+ГРП,ГРП,Ю3
230,942,0.000000,1,100,4,100,NaN,ННС+ГРП,ГРП,Ю3
231,971,762.377859,0,0,0,0,NaN,ГС,ВНС,Ю3
232,971,762.377859,1,100,4,100,NaN,ГС+ГРП,ГРП,Ю3

In [31]:
grp_1 = copy.deepcopy(grp_gtm)
grp_1.reset_index(drop=True)
grp_1.reset_index(inplace=True)
grp_1['Скважина'] = grp_1.apply(
            lambda x:
            str(x['Скважина']), axis=1)
grp_1 = grp_1[grp_1['Скважина'].isin(my_wells_no_repeat)].reset_index(drop=True)
grp_1

,index,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,...,Напор.1,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65
0,0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2942,4923,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2943,4924,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2944,4925,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2945,4926,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2946,4927,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
grp_3 = copy.deepcopy(grp_1)
grp_3['Дата ВНР после'] = grp_3.apply(
            lambda x:
            x['ВНР.1'] if 'КР7-2' in str(x['Краткое описание мероприятий'])
            else x['ВНР.1'] if 'Ввод добывающих сква' in str(x['Краткое описание мероприятий'])
            else 'нет', axis=1)
grp_3['Тип ГТМ'] = grp_3.apply(
            lambda x:
            'ГРП' if 'КР7-2' in str(x['Краткое описание мероприятий'])
            else 'ВНС' if 'Ввод добывающих сква' in str(x['Краткое описание мероприятий'])
            else 'нет', axis=1)
grp_3 = grp_3.drop(grp_3[grp_3['Дата ВНР после'] == 'нет'].index)
grp_3 = grp_3.groupby(by=['Скважина', 'Дата ВНР после']).agg(
            {'Тип ГТМ': lambda x:
            x.tolist()[0]}
        )
grp_3.reset_index(inplace=True)
vvv = grp_3['Скважина'].tolist()

grp_3['Номер скважины'] = vvv
grp_3 = grp_3.drop(['Скважина'], axis=1)
grp_3

    Дата ВНР после Тип ГТМ Номер скважины
0       2016-03-12     ГРП              1
1       2008-10-12     ВНС             10
2       2013-03-03     ГРП             10
3       2011-02-04     ГРП           1004
4       2013-01-31     ГРП           1004
..             ...     ...            ...
650     2011-01-22     ГРП            923
651     2010-11-28     ВНС            924
652     2012-09-19     ГРП            924
653     2019-07-31     ГРП             96
654     2019-11-01     ГРП             99

[655 rows x 3 columns]

In [33]:
grp_3['index'] = grp_3.index
grp_vnski_d = grp_3.drop(grp_3[grp_3['Тип ГТМ'] != 'ВНС'].index)
grp_vnski_d['index'] = grp_vnski_d.index
grp_vnski_d = grp_vnski_d.groupby('Номер скважины').agg(
            {'index': lambda x:
            x.tolist()[1:]}
        )
svetka = []
for i in grp_vnski_d['index']:
    svetka += i
grp_3 = grp_3[~grp_3['index'].isin(svetka)].reset_index(drop=True)
grp_3 = grp_3.drop(['index'], axis=1)
grp_3

    Дата ВНР после Тип ГТМ Номер скважины
0       2016-03-12     ГРП              1
1       2008-10-12     ВНС             10
2       2013-03-03     ГРП             10
3       2011-02-04     ГРП           1004
4       2013-01-31     ГРП           1004
..             ...     ...            ...
645     2011-01-22     ГРП            923
646     2010-11-28     ВНС            924
647     2012-09-19     ГРП            924
648     2019-07-31     ГРП             96
649     2019-11-01     ГРП             99

[650 rows x 3 columns]

In [34]:
grp_2 = copy.deepcopy(grp_1)
grp_2['ГРП'] = grp_2.apply(
            lambda x:
            'грп' if 'КР7-2' in str(x['Краткое описание мероприятий'])
            else 'вдс' if 'Ввод добывающих сква' in str(x['Краткое описание мероприятий'])
            else 'нет', axis=1)
grp_2 = grp_2.drop(grp_2[grp_2['ГРП'] == 'нет'].index)
grp_2 = grp_2.groupby('Скважина').agg(
            {'ГРП': lambda x:
            x.tolist()}
        )
grp_2.reset_index(inplace=True)
        # for i in grp_2['ГРП']:
        #    if 'вдс' in i:
        #        i.remove('вдс')
new_1 = grp_2['Скважина'].tolist()
grp_2['Номер скважины'] = new_1
grp_2 = grp_2.drop(['Скважина'], axis=1)
grp_2

                      ГРП Номер скважины
0                   [грп]              1
1              [вдс, грп]             10
2    [грп, вдс, грп, грп]           1004
3                   [грп]           1006
4              [грп, вдс]             11
..                    ...            ...
337            [вдс, грп]            911
338            [вдс, грп]            923
339            [вдс, грп]            924
340            [грп, вдс]             96
341            [грп, вдс]             99

[342 rows x 2 columns]

In [35]:
final = final.merge(grp_3, on='Номер скважины', how='right')
final

,Номер скважины,Unnamed: 0,Дата,Подрядчик,Комментарии,Страница,Unnamed: 6,Пласт,Азимут,k,...,Расход,Конц,Гель,М бр,V под,V без под,V гель,"Длиина ГС, м",Дата ВНР после,Тип ГТМ
0,1,Проблемы при построении ГРП,2016-02-23,КН,Мини ГРП проводился 23.02.2016 г. По результат...,-1_,NaN,Ю3,NaN,5.0,...,3.4,1200.0,NaN,85.00,30.0,154.4,NaN,0.0,2016-03-12,ГРП
1,10,NaN,2013-02-16,ШЛБ,При проведении работ по ГРП 16/02/2013 закачка...,-1_,NaN,Ю3,NaN,10.0,...,2.6,1056.0,NaN,NaN,14.0,100.0,NaN,0.0,2008-10-12,ВНС
2,10,NaN,2013-02-16,ШЛБ,При проведении работ по ГРП 16/02/2013 закачка...,-1_,NaN,Ю3,NaN,10.0,...,2.6,1056.0,NaN,NaN,14.0,100.0,NaN,0.0,2013-03-03,ГРП
3,1004,Проблемы при построении ГРП,2013-01-03,ШЛБ,По результатам МиниГРП масса пропанта по перво...,-1_,NaN,Ю3,34.0,4.0,...,3.8,890.0,NaN,NaN,110.0,367.3,NaN,0.0,2011-02-04,ГРП
4,1004,Проблемы при построении ГРП,2013-01-03,ШЛБ,По результатам МиниГРП масса пропанта по перво...,-1_,NaN,Ю3,34.0,4.0,...,3.8,890.0,NaN,NaN,110.0,367.3,NaN,0.0,2013-01-31,ГРП
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1760,923,NaN,2011-01-12,ШЛБ,NaN,-1_,NaN,Ю3,NaN,4.9,...,2.6,1024.0,NaN,NaN,60.0,216.3,NaN,0.0,2011-01-22,ГРП
1761,924,Проблемы при построении ГРП,2012-09-09,МКН,"По миниГРП: увеличили стадию ""подушка"" до 5...",-1_,NaN,Ю3,9.0,7.9,...,3.5,1200.0,NaN,NaN,52.0,210.9,NaN,0.0,2010-11-28,ВНС
1762,924,Проблемы при построении ГРП,2012-09-09,МКН,"По миниГРП: увеличили стадию ""подушка"" до 5...",-1_,NaN,Ю3,9.0,7.9,...,3.5,1200.0,NaN,NaN,52.0,210.9,NaN,0.0,2012-09-19,ГРП
1763,96,Проблемы при построении ГРП,2019-06-20,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,152.0,17.4,...,3.6,800.0,NaN,241.37,32.0,NaN,165.0,0.0,2019-07-31,ГРП
1764,99,Проблемы при построении ГРП,2019-10-20,КН,"Оборудование: НКТ, ПРО, АМТ- ООО ""КАТКонефть...",-1_,NaN,Ю3,245.0,24.6,...,3.2,900.0,NaN,41.10,9.0,NaN,53.0,0.0,2019-11-01,ГРП

In [36]:
final['Число стадий ГРП'] = final.apply(
            lambda x:
            3, axis=1)
        #final = final.drop(['ГРП'], axis=1)
        #WARNINGS??????????????????????
        # число стадий грп по фраклисту
final = final.drop(['Дата'], axis=1)
final_re = final.groupby(by=['Номер скважины']).agg(
            {'Число стадий ГРП': lambda x:
            statistics.mean(x)}
        )
final_re.reset_index(inplace=True)
final_re

    Номер скважины  Число стадий ГРП
0                1                 3
1               10                 3
2             1004                 3
3             1006                 3
4               11                 3
..             ...               ...
337            911                 3
338            923                 3
339            924                 3
340             96                 3
341             99                 3

[342 rows x 2 columns]

In [37]:
final_go = final.groupby(by=['Номер скважины']).agg(
            {'Длиина ГС, м': lambda x:
            max(x)}
        )
final_go.reset_index(inplace=True)
final_go

    Номер скважины  Длиина ГС, м
0                1       0.00000
1               10       0.00000
2             1004       0.00000
3             1006       0.00000
4               11       0.00000
..             ...           ...
337            911     686.38546
338            923       0.00000
339            924       0.00000
340             96       0.00000
341             99       0.00000

[342 rows x 2 columns]

In [38]:
final_re = final_re.merge(final_go, on='Номер скважины')
final_re['Число стадий ГРП'] = final_re.apply(
            lambda x:
            1 if x['Длиина ГС, м'] == 0 and x['Число стадий ГРП'] >= 1
            else x['Число стадий ГРП'], axis=1)
final_re1 = copy.deepcopy(final_re)
final_re1

    Номер скважины  Число стадий ГРП  Длиина ГС, м
0                1                 1       0.00000
1               10                 1       0.00000
2             1004                 1       0.00000
3             1006                 1       0.00000
4               11                 1       0.00000
..             ...               ...           ...
337            911                 3     686.38546
338            923                 1       0.00000
339            924                 1       0.00000
340             96                 1       0.00000
341             99                 1       0.00000

[342 rows x 3 columns]

In [39]:
final_re1 = final_re1.drop(final_re1[final_re1['Длиина ГС, м'] == 0].index).reset_index(drop=True)
spisok = final_re1['Номер скважины'].tolist()
        # берем число строк из фраклиста для скважины
final = final.groupby('Номер скважины').agg(
            {'Число стадий ГРП': lambda x:
            x.tolist()}
        )

final['Количество'] = final.apply(
            lambda x:
            len(x['Число стадий ГРП'])
            , axis=1)
final.reset_index(inplace=True)
final

    Номер скважины Число стадий ГРП  Количество
0                1              [3]           1
1               10           [3, 3]           2
2             1004        [3, 3, 3]           3
3             1006              [3]           1
4               11              [3]           1
..             ...              ...         ...
337            911           [3, 3]           2
338            923           [3, 3]           2
339            924           [3, 3]           2
340             96              [3]           1
341             99              [3]           1

[342 rows x 3 columns]

In [40]:
spisok

['1111',
 '1112',
 '1113',
 '1122',
 '1123',
 '1124',
 '1126',
 '1128',
 '1129',
 '123',
 '128',
 '1304',
 '133',
 '1345',
 '1349',
 '141',
 '142',
 '146',
 '149',
 '1500',
 '1501',
 '1503',
 '1507',
 '151',
 '1511',
 '1513',
 '1523',
 '1549',
 '1551',
 '1556',
 '1557',
 '158',
 '1602',
 '1606',
 '1607',
 '1608',
 '1620',
 '1622',
 '1626',
 '1628',
 '1633',
 '1637',
 '1640',
 '17',
 '1900',
 '1901',
 '1902',
 '1903',
 '1906',
 '1909',
 '1910',
 '1977',
 '23',
 '2300',
 '2302',
 '2304',
 '2306',
 '2310',
 '306',
 '35',
 '3552',
 '3630',
 '3635',
 '37',
 '3821',
 '3825',
 '410',
 '412',
 '415',
 '421',
 '429',
 '4301',
 '4302',
 '4306',
 '431',
 '433',
 '451',
 '454',
 '458',
 '459',
 '4630',
 '465',
 '488',
 '491',
 '496',
 '509',
 '515',
 '527Л',
 '529',
 '537',
 '541',
 '542',
 '567',
 '569',
 '581',
 '582',
 '591',
 '601',
 '612',
 '619',
 '626',
 '636',
 '648',
 '649',
 '655',
 '662',
 '663',
 '665',
 '675',
 '68',
 '680',
 '686',
 '711',
 '720',
 '729',
 '738',
 '739',
 '762',
 '763',
 '766',
 '770',
 '8',
 '84',
 '87',
 '874',
 '876',
 '878',
 '881',
 '882',
 '898',
 '909',
 '911']

In [41]:
final = final[final['Номер скважины'].isin(spisok)].reset_index(drop=True)
final = final.drop(['Число стадий ГРП'], axis=1)
final

    Номер скважины  Количество
0             1111           6
1             1112           6
2             1113           6
3             1122           9
4             1123           8
..             ...         ...
127            881           9
128            882           8
129            898           1
130            909          10
131            911           2

[132 rows x 2 columns]

In [42]:
final_re2 = final_re.merge(final, on='Номер скважины', how='left')
final_re2 = final_re2.drop(['Число стадий ГРП'], axis=1)
cv = final_re2['Количество'].tolist()
final_re2['Число стадий ГРП'] = cv
final_re2 = final_re2.drop(['Количество'], axis=1)
final_re2

    Номер скважины  Длиина ГС, м  Число стадий ГРП
0                1       0.00000               NaN
1               10       0.00000               NaN
2             1004       0.00000               NaN
3             1006       0.00000               NaN
4               11       0.00000               NaN
..             ...           ...               ...
337            911     686.38546               2.0
338            923       0.00000               NaN
339            924       0.00000               NaN
340             96       0.00000               NaN
341             99       0.00000               NaN

[342 rows x 3 columns]

In [43]:
final_re = final_re[~final_re['Номер скважины'].isin(spisok)].reset_index(drop=True)
final_re

    Номер скважины  Число стадий ГРП  Длиина ГС, м
0                1                 1           0.0
1               10                 1           0.0
2             1004                 1           0.0
3             1006                 1           0.0
4               11                 1           0.0
..             ...               ...           ...
205            905                 1           0.0
206            923                 1           0.0
207            924                 1           0.0
208             96                 1           0.0
209             99                 1           0.0

[210 rows x 3 columns]

In [44]:
new_file = pd.concat([final_re, final_re2])
new_file

    Номер скважины  Число стадий ГРП  Длиина ГС, м
0                1               1.0       0.00000
1               10               1.0       0.00000
2             1004               1.0       0.00000
3             1006               1.0       0.00000
4               11               1.0       0.00000
..             ...               ...           ...
337            911               2.0     686.38546
338            923               NaN       0.00000
339            924               NaN       0.00000
340             96               NaN       0.00000
341             99               NaN       0.00000

[552 rows x 3 columns]

In [45]:
grp = grp.groupby('Номер скважины').agg(
            {'Пласт': lambda x:
            x.tolist()[0]}
        )
grp.reset_index(inplace=True)
grp

    Номер скважины Пласт
0                1    Ю3
1               10    Ю3
2             1004    Ю3
3             1006    Ю3
4             1082    Ю3
..             ...   ...
376            923    Ю3
377            924    Ю3
378            949    Ю3
379             96    Ю3
380             99    Ю3

[381 rows x 2 columns]

In [46]:
new_file = new_file.merge(grp, on='Номер скважины')
new_file

    Номер скважины  Число стадий ГРП  Длиина ГС, м Пласт
0                1               1.0      0.000000    Ю3
1                1               NaN      0.000000    Ю3
2               10               1.0      0.000000    Ю3
3               10               NaN      0.000000    Ю3
4             1004               1.0      0.000000    Ю3
..             ...               ...           ...   ...
547            881               9.0    962.422984    Ю3
548            882               8.0    598.820507    Ю3
549            898               1.0    444.542461    Ю3
550            909              10.0    294.803324    Ю3
551            911               2.0    686.385460    Ю3

[552 rows x 4 columns]

In [47]:
new_file['Полудлина трещины, м'] = new_file.apply(
            lambda x:
            100, axis=1)
new_file['Ширина трещины, мм'] = new_file.apply(
            lambda x:
            4, axis=1)
new_file['Проницаемость проппанта, Д'] = new_file.apply(
            lambda x:
            100, axis=1)
new_file

,Номер скважины,Число стадий ГРП,"Длиина ГС, м",Пласт,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д"
0,1,1.0,0.000000,Ю3,100,4,100
1,1,NaN,0.000000,Ю3,100,4,100
2,10,1.0,0.000000,Ю3,100,4,100
3,10,NaN,0.000000,Ю3,100,4,100
4,1004,1.0,0.000000,Ю3,100,4,100
...,...,...,...,...,...,...,...
547,881,9.0,962.422984,Ю3,100,4,100
548,882,8.0,598.820507,Ю3,100,4,100
549,898,1.0,444.542461,Ю3,100,4,100
550,909,10.0,294.803324,Ю3,100,4,100
551,911,2.0,686.385460,Ю3,100,4,100

In [48]:
sotired = grp_3.merge(new_file, on='Номер скважины')
sotired

,Дата ВНР после,Тип ГТМ,Номер скважины,Число стадий ГРП,"Длиина ГС, м",Пласт,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д"
0,2016-03-12,ГРП,1,1.0,0.0,Ю3,100,4,100
1,2016-03-12,ГРП,1,NaN,0.0,Ю3,100,4,100
2,2008-10-12,ВНС,10,1.0,0.0,Ю3,100,4,100
3,2008-10-12,ВНС,10,NaN,0.0,Ю3,100,4,100
4,2013-03-03,ГРП,10,1.0,0.0,Ю3,100,4,100
...,...,...,...,...,...,...,...,...,...
1033,2012-09-19,ГРП,924,NaN,0.0,Ю3,100,4,100
1034,2019-07-31,ГРП,96,1.0,0.0,Ю3,100,4,100
1035,2019-07-31,ГРП,96,NaN,0.0,Ю3,100,4,100
1036,2019-11-01,ГРП,99,1.0,0.0,Ю3,100,4,100
1037,2019-11-01,ГРП,99,NaN,0.0,Ю3,100,4,100

In [49]:
        # добавляем последнй столбец
        sotired['ГС/ННС'] = sotired.apply(
            lambda x:
            'ННС' if x['Длиина ГС, м'] == 0
            else 'ГС', axis=1)
        # редактируем его в зависимости от наличия грп
        sotired['ГС/ННС'] = sotired.apply(
            lambda x:
            str(x['ГС/ННС']) + '+ГРП' if str(x['Тип ГТМ']) == 'ГРП'
            else x['ГС/ННС'], axis=1)
        # перемещаем столбцы в нужном порядке
        r = sotired.pop('Дата ВНР после')
        sotired1 = pd.concat([sotired, r], 1)
        # перемещаем столбцы в нужном порядке
        q = sotired1.pop('ГС/ННС')
        sotired2 = pd.concat([sotired1, q], 1)
        # перемещаем столбцы в нужном порядке
        z = sotired2.pop('Тип ГТМ')
        sotired3 = pd.concat([sotired2, z], 1)
        # перемещаем столбцы в нужном порядке
        d = sotired3.pop('Пласт')
        sotired4 = pd.concat([sotired3, d], 1)
        i = sotired4['Номер скважины'].tolist()
        sotired4['Скважина №'] = i
        sotired4 = sotired4.drop(['Номер скважины'], axis=1)
        sotired_final = sotired4.reindex(
            columns=['Скважина №', 'Длиина ГС, м', 'Число стадий ГРП', 'Полудлина трещины, м', 'Ширина трещины, мм',
                     'Проницаемость проппанта, Д', 'Дата ВНР после', 'ГС/ННС', 'Тип ГТМ', 'Пласт'])
        sotired_final['Число стадий ГРП'] = sotired.apply(
            lambda x:
            0 if str(x['Тип ГТМ']) == 'ВНС'
            else x['Число стадий ГРП'], axis=1)

C:\Users\USER\miniconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  del sys.path[0]
C:\Users\USER\miniconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  app.launch_new_instance()
C:\Users\USER\miniconda3\lib\site-packages\ipykernel_launcher.py:19: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
C:\Users\USER\miniconda3\lib\site-packages\ipykernel_launcher.py:22: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only

In [50]:
sotired_final

,Скважина №,"Длиина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.0,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,1,0.0,NaN,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
2,10,0.0,0.0,100,4,100,2008-10-12,ННС,ВНС,Ю3
3,10,0.0,0.0,100,4,100,2008-10-12,ННС,ВНС,Ю3
4,10,0.0,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
1033,924,0.0,NaN,100,4,100,2012-09-19,ННС+ГРП,ГРП,Ю3
1034,96,0.0,1.0,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
1035,96,0.0,NaN,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
1036,99,0.0,1.0,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3
1037,99,0.0,NaN,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3

In [51]:
plast = 'Ю3'
sotired_final = sotired_final.drop(sotired_final[sotired_final['Пласт'] != plast].index).reset_index(drop=True)
zzz = sotired_final['Длиина ГС, м'].tolist()
sotired_final['Длина ГС, м'] = zzz

sotired_final = sotired_final.drop(['Длиина ГС, м'], axis=1)
sotired_final = sotired_final.reindex(
    columns=['Скважина №', 'Длина ГС, м', 'Число стадий ГРП', 'Полудлина трещины, м', 'Ширина трещины, мм',
                     'Проницаемость проппанта, Д', 'Дата ВНР после', 'ГС/ННС', 'Тип ГТМ', 'Пласт'])
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.0,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,1,0.0,NaN,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
2,10,0.0,0.0,100,4,100,2008-10-12,ННС,ВНС,Ю3
3,10,0.0,0.0,100,4,100,2008-10-12,ННС,ВНС,Ю3
4,10,0.0,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
1030,924,0.0,NaN,100,4,100,2012-09-19,ННС+ГРП,ГРП,Ю3
1031,96,0.0,1.0,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
1032,96,0.0,NaN,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
1033,99,0.0,1.0,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3
1034,99,0.0,NaN,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3

In [52]:
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.0,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,1,0.0,NaN,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
2,10,0.0,0.0,100,4,100,2008-10-12,ННС,ВНС,Ю3
3,10,0.0,0.0,100,4,100,2008-10-12,ННС,ВНС,Ю3
4,10,0.0,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
1030,924,0.0,NaN,100,4,100,2012-09-19,ННС+ГРП,ГРП,Ю3
1031,96,0.0,1.0,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
1032,96,0.0,NaN,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
1033,99,0.0,1.0,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3
1034,99,0.0,NaN,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3

In [53]:
sotired_final['Дата ВНР после'] = sotired_final.apply(
            lambda x:
            str(x['Дата ВНР после']), axis=1)
sotired_final['месяц с грп'] = sotired_final.apply(
            lambda x:
            x['Дата ВНР после'][:4],
            axis=1
        )
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп
0,1,0.0,1.0,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016
1,1,0.0,NaN,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016
2,10,0.0,0.0,100,4,100,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008
3,10,0.0,0.0,100,4,100,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008
4,10,0.0,1.0,100,4,100,2013-03-03 00:00:00,ННС+ГРП,ГРП,Ю3,2013
...,...,...,...,...,...,...,...,...,...,...,...
1030,924,0.0,NaN,100,4,100,2012-09-19 00:00:00,ННС+ГРП,ГРП,Ю3,2012
1031,96,0.0,1.0,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019
1032,96,0.0,NaN,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019
1033,99,0.0,1.0,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019
1034,99,0.0,NaN,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019

In [54]:
grp_number = copy.deepcopy(grp_dad)

In [55]:
grp_number['Номер скважины'] = grp_number.apply(
            lambda x:
            str(x['Номер скважины']), axis=1)
grp_number['Дата'] = grp_number.apply(
            lambda x:
            str(x['Дата']), axis=1)
grp_number['месяц с грп'] = grp_number.apply(
            lambda x:
            x['Дата'][:4],
            axis=1
        )
grp_number

,Номер скважины,Unnamed: 0,Дата,Подрядчик,Комментарии,Страница,Unnamed: 6,Пласт,Наклон,Азимут,...,Рпл Хорнер,Эфф,Расход,Конц,Гель,М бр,V под,V без под,V гель,месяц с грп
0,99,Проблемы при построении ГРП,2019-10-20 00:00:00,КН,"Оборудование: НКТ, ПРО, АМТ- ООО ""КАТКонефть...",-1_,NaN,Ю3,17.0,245.0,...,48.0,71.0,3.2,900.0,NaN,41.10000,9.0,NaN,53.0,2019
1,96,Проблемы при построении ГРП,2019-06-20 00:00:00,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,7.0,152.0,...,45.0,63.0,3.6,800.0,NaN,241.37000,32.0,NaN,165.0,2019
2,949,Проблемы при построении ГРП,2021-09-15 00:00:00,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,60.0,37.0,3.6,1000.0,NaN,45.95220,NaN,NaN,71.5,2021
3,949,Проблемы при построении ГРП,2021-09-15 00:00:00,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,62.0,31.5,3.6,1000.0,NaN,40.47128,NaN,NaN,54.8,2021
4,949,Проблемы при построении ГРП,2021-09-15 00:00:00,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,58.0,36.0,3.6,1000.0,NaN,41.01312,NaN,NaN,53.8,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,1082,Проблемы при построении ГРП,2020-02-07 00:00:00,МКМ,"ГРП по плану (+), 42 т. Выполнена стадия Запо...",-1_,NaN,Ю3,20.0,305.0,...,49.0,74.8,3.6,800.0,NaN,50.00000,35.0,NaN,145.0,2020
1044,1006,Проблемы при построении ГРП,2019-07-26 00:00:00,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,22.0,40.0,...,61.0,43.0,3.4,800.0,NaN,133.24063,NaN,5.0,73.0,2019
1045,1004,Проблемы при построении ГРП,2013-01-03 00:00:00,ШЛБ,По результатам МиниГРП масса пропанта по перво...,-1_,NaN,Ю3,40.0,34.0,...,200.0,32.0,3.8,890.0,NaN,NaN,110.0,367.3,NaN,2013
1046,10,NaN,2013-02-16 00:00:00,ШЛБ,При проведении работ по ГРП 16/02/2013 закачка...,-1_,NaN,Ю3,2.0,NaN,...,235.0,73.0,2.6,1056.0,NaN,NaN,14.0,100.0,NaN,2013
1047,1,Проблемы при построении ГРП,2016-02-23 00:00:00,КН,Мини ГРП проводился 23.02.2016 г. По результат...,-1_,NaN,Ю3,1.0,NaN,...,NaN,43.0,3.4,1200.0,NaN,85.00000,30.0,154.4,NaN,2016

In [56]:
grp_number_group = grp_number.groupby(by=['Номер скважины', 'месяц с грп']).agg(
            {'Наклон': lambda x:
            x.tolist()}
        )
grp_number_group.reset_index(inplace=True)
grp_number_group

    Номер скважины месяц с грп                          Наклон
0                1        2016                           [1.0]
1               10        2013                           [2.0]
2             1004        2013                          [40.0]
3             1006        2019                          [22.0]
4             1082        2020                          [20.0]
..             ...         ...                             ...
444            923        2011                          [20.0]
445            924        2012                          [15.1]
446            949        2021  [93.7, 93.7, 93.7, 93.7, 93.7]
447             96        2019                           [7.0]
448             99        2019                          [17.0]

[449 rows x 3 columns]

In [57]:
grp_number_group['число стадий'] = grp_number_group.apply(
            lambda x:
            len(x['Наклон']), axis=1)
grp_number_group = grp_number_group.drop('Наклон', axis=1)
blabla = grp_number_group['Номер скважины'].tolist()

grp_number_group['Скважина №'] = blabla
grp_number_group = grp_number_group.drop(['Номер скважины'], axis=1)
grp_number_group

    месяц с грп  число стадий Скважина №
0          2016             1          1
1          2013             1         10
2          2013             1       1004
3          2019             1       1006
4          2020             1       1082
..          ...           ...        ...
444        2011             1        923
445        2012             1        924
446        2021             5        949
447        2019             1         96
448        2019             1         99

[449 rows x 3 columns]

In [58]:
sotired_final = sotired_final.merge(grp_number_group, on=['месяц с грп', 'Скважина №'], how='left')
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,число стадий
0,1,0.0,1.0,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016,1.0
1,1,0.0,NaN,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016,1.0
2,10,0.0,0.0,100,4,100,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008,NaN
3,10,0.0,0.0,100,4,100,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008,NaN
4,10,0.0,1.0,100,4,100,2013-03-03 00:00:00,ННС+ГРП,ГРП,Ю3,2013,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1030,924,0.0,NaN,100,4,100,2012-09-19 00:00:00,ННС+ГРП,ГРП,Ю3,2012,1.0
1031,96,0.0,1.0,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
1032,96,0.0,NaN,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
1033,99,0.0,1.0,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
1034,99,0.0,NaN,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0

In [59]:
sotired_final=sotired_final.drop_duplicates(subset=['Скважина №'])

In [60]:
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,число стадий
0,1,0.00000,1.0,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016,1.0
2,10,0.00000,0.0,100,4,100,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008,NaN
6,1004,0.00000,1.0,100,4,100,2011-02-04 00:00:00,ННС+ГРП,ГРП,Ю3,2011,NaN
12,1006,0.00000,1.0,100,4,100,2019-08-16 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
14,11,0.00000,1.0,100,4,100,2009-04-01 00:00:00,ННС+ГРП,ГРП,Ю3,2009,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1021,911,686.38546,0.0,100,4,100,2011-01-27 00:00:00,ГС,ВНС,Ю3,2011,NaN
1023,923,0.00000,0.0,100,4,100,2010-12-10 00:00:00,ННС,ВНС,Ю3,2010,NaN
1027,924,0.00000,0.0,100,4,100,2010-11-28 00:00:00,ННС,ВНС,Ю3,2010,NaN
1031,96,0.00000,1.0,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
1033,99,0.00000,1.0,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0

In [61]:
milan = sotired_final['число стадий'].tolist()
sotired_final = sotired_final.drop(['Число стадий ГРП'], axis=1)
sotired_final['Число стадий ГРП'] = milan
sotired_final = sotired_final.drop(['число стадий'], axis=1)
sotired_final['Дата ВНР после'] = pd.to_datetime(sotired_final['Дата ВНР после'])
sotired_final = sotired_final.reindex(
columns=['Скважина №', 'Длина ГС, м', 'Число стадий ГРП', 'Полудлина трещины, м', 'Ширина трещины, мм',
                     'Проницаемость проппанта, Д', 'Дата ВНР после', 'ГС/ННС', 'Тип ГТМ', 'Пласт',
                     'месяц с грп'])
sotired_final = pd.concat([sotired_final, wells_GTM])
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Дата ВНР после ГС \ ГРП \ЗБГС
0,1,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3,2016,NaN
2,10,0.000000,NaN,100,4,100,2008-10-12,ННС,ВНС,Ю3,2008,NaN
6,1004,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3,2011,NaN
12,1006,0.000000,1.0,100,4,100,2019-08-16,ННС+ГРП,ГРП,Ю3,2019,NaN
14,11,0.000000,1.0,100,4,100,2009-04-01,ННС+ГРП,ГРП,Ю3,2009,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
228,927,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN
229,936,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN
230,942,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN
231,971,762.377859,0.0,0,0,0,NaT,ГС,ВНС,Ю3,NaN,NaN
232,971,762.377859,1.0,100,4,100,NaT,ГС+ГРП,ГРП,Ю3,NaN,NaN

In [62]:
sotired_final['Полудлина трещины, м'] = sotired_final.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Полудлина трещины, м']
            , axis=1)
sotired_final['Ширина трещины, мм'] = sotired_final.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Ширина трещины, мм']
            , axis=1)
sotired_final['Проницаемость проппанта, Д'] = sotired_final.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Проницаемость проппанта, Д']
            , axis=1)
        # ДОБАВИТЬ В ВНС
sotired_final['Число стадий ГРП'] = sotired_final.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Число стадий ГРП']
            , axis=1)
sotired_final.reset_index(drop=True)
sotired_final.reset_index(inplace=True)
        # sotired_final = sotired_final.drop(['level_0'], axis=1)
sotired_final = sotired_final.drop(['index'], axis=1)
sotired_final["is_duplicate"] = sotired_final.duplicated()
sotired_final = sotired_final.drop(sotired_final[sotired_final['is_duplicate'] == True].index)
sotired_final.reset_index(inplace=True)
sotired_final = sotired_final.drop(['index'], axis=1)
sotired_final['level_0'] = sotired_final.index
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Дата ВНР после ГС \ ГРП \ЗБГС,is_duplicate,level_0
0,1,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3,2016,NaN,False,0
1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3,2008,NaN,False,1
2,1004,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3,2011,NaN,False,2
3,1006,0.000000,1.0,100,4,100,2019-08-16,ННС+ГРП,ГРП,Ю3,2019,NaN,False,3
4,11,0.000000,1.0,100,4,100,2009-04-01,ННС+ГРП,ГРП,Ю3,2009,NaN,False,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,927,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN,False,549
550,936,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN,False,550
551,942,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN,False,551
552,971,762.377859,0.0,0,0,0,NaT,ГС,ВНС,Ю3,NaN,NaN,False,552
553,971,762.377859,1.0,100,4,100,NaT,ГС+ГРП,ГРП,Ю3,NaN,NaN,False,553

In [63]:
        # удаляем если в одном месяце
dele = copy.deepcopy(sotired_final)
dele['чек'] = dele.apply(
            lambda x:
            x['Скважина №'].partition('_')[0] if '_' in str(x['Скважина №'])
            else x['Скважина №'], axis=1)
dele['месяц'] = dele.apply(
            lambda x:
            str(x['Дата ВНР после ГС \ ГРП \ЗБГС'])[:7],
            axis=1
        )
dele = dele.groupby(by=['чек', 'месяц']).agg(
            {'level_0': lambda x:
            x.tolist()}
        )
dele['скока_их'] = dele.apply(
            lambda x: len(x['level_0'])
            , axis=1)
dele = dele.drop(dele[dele['скока_их'] < 2].index).reset_index(drop=True)
to_stay = []
all_wells = []
for i in dele['level_0']:
    all_wells += i
for i in dele['level_0']:
    to_stay.append(i[-1])
dele

       level_0  скока_их
0   [343, 344]         2
1   [354, 355]         2
2   [357, 358]         2
3   [359, 360]         2
4   [361, 362]         2
5   [365, 366]         2
6   [367, 368]         2
7   [379, 380]         2
8   [393, 394]         2
9   [411, 412]         2
10  [431, 432]         2
11  [440, 441]         2
12  [443, 444]         2
13  [454, 455]         2
14  [456, 457]         2
15  [463, 464]         2
16  [468, 469]         2
17  [473, 474]         2
18  [478, 479]         2
19  [481, 482]         2
20  [498, 499]         2
21  [514, 515]         2
22  [519, 520]         2
23  [521, 522]         2
24  [526, 527]         2
25  [528, 529]         2
26  [531, 532]         2
27  [533, 534]         2
28  [535, 536]         2
29  [538, 539]         2
30  [548, 549]         2
31  [552, 553]         2

In [64]:
alli = copy.deepcopy(sotired_final)
alli = alli[alli['level_0'].isin(all_wells)].reset_index(drop=True)
alli = alli.drop(alli[alli['Тип ГТМ'] == 'ВНС'].index).reset_index(drop=True)
alli = alli.groupby('Скважина №').agg(
            {'level_0': lambda x:
            x.tolist()[0]}
        )
definetely_stay = alli['level_0'].tolist()
array_3 = list(all_wells)
for x in definetely_stay:
    try:
        array_3.remove(x)
    except ValueError:
        pass
        # вот досюда
alli

            level_0
Скважина №
105             344
124             355
1260            358
1272            360
1291            362
1312            366
1334            368
1544            380
183             394
215Р            412
3820            432
413             441
419             444
438             455
439             457
456             464
466             469
473             474
499             479
501             482
609             499
707             515
734             520
735             522
754             527
758             529
79              532
83              534
85              536
901             539
927             549
971             553

In [65]:
sotired_final = sotired_final[~sotired_final['level_0'].isin(array_3)].reset_index(drop=True)
sotired_final = sotired_final.drop(['level_0'], axis=1)
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Дата ВНР после ГС \ ГРП \ЗБГС,is_duplicate
0,1,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3,2016,NaN,False
1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3,2008,NaN,False
2,1004,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3,2011,NaN,False
3,1006,0.000000,1.0,100,4,100,2019-08-16,ННС+ГРП,ГРП,Ю3,2019,NaN,False
4,11,0.000000,1.0,100,4,100,2009-04-01,ННС+ГРП,ГРП,Ю3,2009,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,926,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN,False
518,927,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN,False
519,936,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN,False
520,942,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN,False
521,971,762.377859,1.0,100,4,100,NaT,ГС+ГРП,ГРП,Ю3,NaN,NaN,False

In [66]:
        # проверяем ЗБС
grp_4 = copy.deepcopy(grp_gtm)

grp_4['Скважина'] = grp_4.apply(
            lambda x:
            str(x['Скважина']), axis=1)
grp_4 = grp_4[grp_4['Скважина'].isin(my_wells_no_repeat + my_wells_only_gtm)].reset_index(drop=True)
        # grp_4
grp_4

,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,Краткое описание мероприятий,...,Напор.1,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65
0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,КР9-5 Перевод скважин в добывающие,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,КР7-2 Проведение ГРП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,КР9-6 Перевод под нагнетание из других категор...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,Гидродинамические исследования,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4923,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4924,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4925,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4926,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4927,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
grp_zbs = grp_4.drop(grp_4[grp_4['Тип'] != '3БС'].index).reset_index(drop=True)
        # grp_zbs = grp_4.loc[grp_4['Тип'] == 'ЗБС']
grp_zbs = grp_zbs.groupby('Скважина').agg(
            {'Начало.1': lambda x:
            x.tolist()[1] if len(x.tolist()) > 1
            else x.tolist()[0]}
        )
grp_zbs

           Начало.1
Скважина
123      2019-07-13
1230     2014-07-12
1304     2014-07-09
1311     2011-12-05
133      2014-03-28
...             ...
890      2021-11-16
897      2012-04-26
906      2021-09-30
909      2014-07-03
949      2021-09-11

[79 rows x 1 columns]

In [68]:
grp_zbs.reset_index(drop=True)
grp_zbs.reset_index(inplace=True)
        # grp_zbs

vv = grp_zbs['Скважина'].tolist()

grp_zbs['Скважина №'] = vv
grp_zbs = grp_zbs.drop(['Скважина'], axis=1)
grp_zbs

     Начало.1 Скважина №
0  2019-07-13        123
1  2014-07-12       1230
2  2014-07-09       1304
3  2011-12-05       1311
4  2014-03-28        133
..        ...        ...
74 2021-11-16        890
75 2012-04-26        897
76 2021-09-30        906
77 2014-07-03        909
78 2021-09-11        949

[79 rows x 2 columns]

In [69]:
grp_zbs.loc[grp_zbs['Скважина №'] == '507']

     Начало.1 Скважина №
43 2011-06-15        507

In [70]:
sotired_final_zbs = sotired_final.merge(grp_zbs, on='Скважина №')
sotired_final_zbs

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Дата ВНР после ГС \ ГРП \ЗБГС,is_duplicate,Начало.1
0,123,313.336879,0.0,0,0,0,2009-01-20,ГС,ВНС,Ю3,2009,NaN,False,2019-07-13
1,1304,261.283371,3.0,100,4,100,2014-07-20,ГС+ГРП,ГРП,Ю3,2014,NaN,False,2014-07-09
2,1311,0.000000,0.0,0,0,0,2010-05-15,ННС,ВНС,Ю3,2010,NaN,False,2011-12-05
3,133,331.593124,NaN,100,4,100,2013-10-11,ГС+ГРП,ГРП,Ю3,2013,NaN,False,2014-03-28
4,14,0.000000,0.0,0,0,0,2006-10-29,ННС,ВНС,Ю3,2006,NaN,False,2014-10-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,5,346.101141,1.0,100,4,100,NaT,ГС+ГРП,ГРП,Ю3,NaN,NaN,False,2018-03-12
70,65,652.099686,0.0,0,0,0,NaT,ГС,ВНС,Ю3,NaN,NaN,False,2019-04-17
71,79,482.414759,1.0,100,4,100,NaT,ГС+ГРП,ГРП,Ю3,NaN,NaN,False,2011-08-21
72,85,439.829512,1.0,100,4,100,NaT,ГС+ГРП,ГРП,Ю3,NaN,NaN,False,2020-05-25
73,906,0.000000,1.0,100,4,100,NaT,ННС+ГРП,ГРП,Ю3,NaN,NaN,False,2021-09-30

In [71]:
abba = sotired_final_zbs['Скважина №'].tolist()

In [72]:
if sotired_final_zbs.shape[0] != 0:
    sotired_final_zbs['Длина ГС, м'] = sotired_final_zbs.apply(
            lambda x:
            0 if x['Дата ВНР после ГС \ ГРП \ЗБГС'] < x['Начало.1'] else x['Длина ГС, м'],
            axis=1
        )
    sotired_final_zbs['Число стадий ГРП'] = sotired_final_zbs.apply(
            lambda x:
            1 if x['Дата ВНР после ГС \ ГРП \ЗБГС'] < x['Начало.1'] else x['Число стадий ГРП'],
            axis=1
        )
    sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            str(x['Скважина №'])
            + ('_Л' if x['Длина ГС, м'] == 0 else ''),
            axis=1
        )
    sotired_final_zbs = sotired_final_zbs.drop(['Начало.1'], axis=1)
    sotired_final = sotired_final[~sotired_final['Скважина №'].isin(abba)].reset_index(drop=True)
sotired_final = pd.concat([sotired_final, sotired_final_zbs])
sotired_final

TypeError: '<' not supported between instances of 'float' and 'Timestamp'