In [1]:
import pandas as pd
import statistics
import copy
import datetime

In [2]:
merge_1 = pd.read_excel('first_merge.xlsx')
merge_2 = pd.read_excel('second_merge.xlsx')
merge_1['Скважина №'] = merge_1.apply(
    lambda x: 
    str(x['Скважина №']), axis=1)
merge_2['Скважина №'] = merge_2.apply(
    lambda x: 
    str(x['Скважина №']), axis=1)

In [3]:
merge_1

,Unnamed: 0,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после ГС \ ГРП \ЗБГС,ГС/ННС,Тип ГТМ,Пласт,месяц с грп
0,0,1028,369.891876,6,100,4,100,2019-04-05 00:00:00,ГС+ГРП,ГРП,Ю1,2019
1,1,1060,614.642172,0,100,4,100,2017-05-08 00:00:00,ГС,ВНС,Ю1,2017
2,2,1060,614.642172,7,100,4,100,2017-05-17 00:00:00,ГС+ГРП,ГРП,Ю1,2017
3,3,1138,0.000000,1,100,4,100,2001-12-30 00:00:00,ННС+ГРП,ГРП,Ю1,2001
4,4,1138,0.000000,1,100,4,100,2006-05-02 00:00:00,ННС+ГРП,ГРП,Ю1,2006
...,...,...,...,...,...,...,...,...,...,...,...,...
199,199,5358,651.659420,0,100,4,100,2015-06-10 00:00:00,ГС,ВНС,Ю1,2015
200,200,5358,651.659420,6,100,4,100,2015-06-20 00:00:00,ГС+ГРП,ГРП,Ю1,2015
201,201,822,478.806850,0,100,4,100,2014-03-14 00:00:00,ГС,ВНС,Ю1,2014
202,202,824,636.387461,0,100,4,100,2015-03-18 00:00:00,ГС,ВНС,Ю1,2015
203,203,824,636.387461,6,100,4,100,2015-03-31 00:00:00,ГС+ГРП,ГРП,Ю1,2015

In [4]:
merge_2

     Unnamed: 0  месяц с грп  число стадий Скважина №
0             0         2008             1       1003
1             1         2017             1       1003
2             2         2006             1        101
3             3         2015             3        101
4             4         2016             1        101
..          ...          ...           ...        ...
242         242         2015             4        827
243         243         2019             1        827
244         244         2007             1        974
245         245         2012             1        974
246         246         2018             1        974

[247 rows x 4 columns]

In [5]:
sotired_final = merge_1.merge(merge_2, on=['месяц с грп', 'Скважина №'],how='left')

In [6]:
milan = sotired_final['число стадий'].tolist()
sotired_final = sotired_final.drop(['Число стадий ГРП'], axis=1)
sotired_final['Число стадий ГРП'] = milan
sotired_final = sotired_final.drop(['число стадий'], axis=1)
sotired_final['Дата ВНР после ГС \ ГРП \ЗБГС']=pd.to_datetime(sotired_final['Дата ВНР после ГС \ ГРП \ЗБГС'])
sotired_final = sotired_final.reindex(
columns=['Скважина №', 'Длина ГС, м', 'Число стадий ГРП', 'Полудлина трещины, м', 'Ширина трещины, мм',
                     'Проницаемость проппанта, Д', 'Дата ВНР после ГС \ ГРП \ЗБГС', 'ГС/ННС', 'Тип ГТМ', 'Пласт',
                     'месяц с грп'])
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после ГС \ ГРП \ЗБГС,ГС/ННС,Тип ГТМ,Пласт,месяц с грп
0,1028,369.891876,6.0,100,4,100,2019-04-05,ГС+ГРП,ГРП,Ю1,2019
1,1060,614.642172,7.0,100,4,100,2017-05-08,ГС,ВНС,Ю1,2017
2,1060,614.642172,7.0,100,4,100,2017-05-17,ГС+ГРП,ГРП,Ю1,2017
3,1138,0.000000,NaN,100,4,100,2001-12-30,ННС+ГРП,ГРП,Ю1,2001
4,1138,0.000000,1.0,100,4,100,2006-05-02,ННС+ГРП,ГРП,Ю1,2006
...,...,...,...,...,...,...,...,...,...,...,...
199,5358,651.659420,6.0,100,4,100,2015-06-10,ГС,ВНС,Ю1,2015
200,5358,651.659420,6.0,100,4,100,2015-06-20,ГС+ГРП,ГРП,Ю1,2015
201,822,478.806850,NaN,100,4,100,2014-03-14,ГС,ВНС,Ю1,2014
202,824,636.387461,6.0,100,4,100,2015-03-18,ГС,ВНС,Ю1,2015
203,824,636.387461,6.0,100,4,100,2015-03-31,ГС+ГРП,ГРП,Ю1,2015

In [7]:
        # ставим нули для ВНС
        sotired_final['Полудлина трещины, м'] = sotired_final.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Полудлина трещины, м']
            , axis=1)
        sotired_final['Ширина трещины, мм'] = sotired_final.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Ширина трещины, мм']
            , axis=1)
        sotired_final['Проницаемость проппанта, Д'] = sotired_final.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Проницаемость проппанта, Д']
            , axis=1)
        # ДОБАВИТЬ В ВНС
        sotired_final['Число стадий ГРП'] = sotired_final.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Число стадий ГРП']
            , axis=1)
        sotired_final['index'] = sotired_final.index
        sotired_final
        #step.reset_index(inplace=True)

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после ГС \ ГРП \ЗБГС,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,index
0,1028,369.891876,6.0,100,4,100,2019-04-05,ГС+ГРП,ГРП,Ю1,2019,0
1,1060,614.642172,0.0,0,0,0,2017-05-08,ГС,ВНС,Ю1,2017,1
2,1060,614.642172,7.0,100,4,100,2017-05-17,ГС+ГРП,ГРП,Ю1,2017,2
3,1138,0.000000,NaN,100,4,100,2001-12-30,ННС+ГРП,ГРП,Ю1,2001,3
4,1138,0.000000,1.0,100,4,100,2006-05-02,ННС+ГРП,ГРП,Ю1,2006,4
...,...,...,...,...,...,...,...,...,...,...,...,...
199,5358,651.659420,0.0,0,0,0,2015-06-10,ГС,ВНС,Ю1,2015,199
200,5358,651.659420,6.0,100,4,100,2015-06-20,ГС+ГРП,ГРП,Ю1,2015,200
201,822,478.806850,0.0,0,0,0,2014-03-14,ГС,ВНС,Ю1,2014,201
202,824,636.387461,0.0,0,0,0,2015-03-18,ГС,ВНС,Ю1,2015,202
203,824,636.387461,6.0,100,4,100,2015-03-31,ГС+ГРП,ГРП,Ю1,2015,203

In [8]:
        #приставка ФРАК там где надо
        step = sotired_final.drop(
            sotired_final[(sotired_final['ГС/ННС'] == 'ГС') | (sotired_final['ГС/ННС'] == 'ННС')].index)
        step['index'] = step.index

        step

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после ГС \ ГРП \ЗБГС,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,index
0,1028,369.891876,6.0,100,4,100,2019-04-05,ГС+ГРП,ГРП,Ю1,2019,0
2,1060,614.642172,7.0,100,4,100,2017-05-17,ГС+ГРП,ГРП,Ю1,2017,2
3,1138,0.000000,NaN,100,4,100,2001-12-30,ННС+ГРП,ГРП,Ю1,2001,3
4,1138,0.000000,1.0,100,4,100,2006-05-02,ННС+ГРП,ГРП,Ю1,2006,4
5,1157,0.000000,NaN,100,4,100,1994-01-01,ННС+ГРП,ГРП,Ю1,1994,5
...,...,...,...,...,...,...,...,...,...,...,...,...
195,5235,0.000000,1.0,100,4,100,2017-09-08,ННС+ГРП,ГРП,Ю1,2017,195
196,5289,0.000000,1.0,100,4,100,2013-05-16,ННС+ГРП,ГРП,Ю1,2013,196
198,5316,0.000000,1.0,100,4,100,2005-01-22,ННС+ГРП,ГРП,Ю1,2005,198
200,5358,651.659420,6.0,100,4,100,2015-06-20,ГС+ГРП,ГРП,Ю1,2015,200
203,824,636.387461,6.0,100,4,100,2015-03-31,ГС+ГРП,ГРП,Ю1,2015,203

In [9]:

step = step.groupby(by=['Скважина №']).agg(
            {'index': lambda x:
            x.tolist()[1:]}
        )
step

                  index
Скважина №
1028                 []
1060                 []
1138                [4]
1157             [6, 7]
1165        [9, 10, 11]
...                 ...
5235              [195]
5289                 []
5316                 []
5358                 []
824                  []

[77 rows x 1 columns]

In [10]:
step.reset_index(inplace=True)
step.rename(columns={'Скважина №': 'список'}, inplace=True)

step

   список        index
0    1028           []
1    1060           []
2    1138          [4]
3    1157       [6, 7]
4    1165  [9, 10, 11]
..    ...          ...
72   5235        [195]
73   5289           []
74   5316           []
75   5358           []
76    824           []

[77 rows x 2 columns]

In [11]:

step['Length'] = step.apply(
lambda x: len(x['index'])
, axis=1)
step = step.drop(step[step['Length'] < 1].index)
step

   список                 index  Length
2    1138                   [4]       1
3    1157                [6, 7]       2
4    1165           [9, 10, 11]       3
5    1180  [13, 14, 15, 16, 17]       5
6    1183              [19, 20]       2
7    1185          [22, 23, 24]       3
8    1190      [26, 27, 28, 29]       4
9    1191          [31, 32, 33]       3
10   1211                  [35]       1
11   1217                  [37]       1
12   1218          [39, 40, 41]       3
13   1221              [43, 44]       2
14   1267  [46, 47, 48, 49, 50]       5
16   1271          [53, 54, 55]       3
17   1279                  [57]       1
18   1283                  [59]       1
19   1288              [61, 62]       2
20   1293      [65, 66, 67, 68]       4
21   1302                  [70]       1
22   1308          [72, 73, 74]       3
24   1320              [79, 80]       2
27   1342                  [87]       1
28   1416          [90, 91, 92]       3
29   1417                  [95]       1
43   1978            [124, 125]       2
47   2136       [134, 135, 136]       3
51   2296       [144, 145, 146]       3
53   3561            [150, 151]       2
56   3567            [157, 158]       2
57   3575                 [161]       1
58   3782            [163, 164]       2
59   3784                 [166]       1
60   3788                 [168]       1
62   4346            [171, 172]       2
67   5162                 [182]       1
69   5166                 [187]       1
70   5202       [189, 190, 191]       3
72   5235                 [195]       1

In [12]:

        gang1 = []
        gang2 = []
        gang3 = []
        gang4 = []
        gang5 = []
        gang6 = []
        gang7 = []
        gang8 = []
        gang9 = []
        gang10 = []

        for i in step['index']:
            if len(i) >= 1:
                gang1.append(i[0])
            if len(i) >= 2:
                gang2.append(i[1])
            if len(i) >= 3:
                gang3.append(i[2])
            if len(i) >= 4:
                gang4.append(i[3])
            if len(i) >= 5:
                gang5.append(i[4])
            if len(i) >= 6:
                gang6.append(i[5])
            if len(i) >= 7:
                gang7.append(i[6])
            if len(i) >= 8:
                gang8.append(i[7])
            if len(i) >= 9:
                gang9.append(i[8])
            if len(i) >= 10:
                gang10.append(i[9])
            else:
                pass
        gang4

[16, 29, 49, 68]

In [13]:

        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК' if x['index'] in gang1
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_1' if x['index'] in gang2
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_2' if x['index'] in gang3
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_3' if x['index'] in gang4
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_4' if x['index'] in gang5
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_5' if x['index'] in gang6
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_6' if x['index'] in gang7
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_7' if x['index'] in gang8
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_8' if x['index'] in gang9
            else x['Скважина №'], axis=1)
        sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_9' if x['index'] in gang10
            else x['Скважина №'], axis=1)
        sotired_final = sotired_final.drop(['index'], axis=1)
        sotired_final = sotired_final.drop(['месяц с грп'], axis=1)
        sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после ГС \ ГРП \ЗБГС,ГС/ННС,Тип ГТМ,Пласт
0,1028,369.891876,6.0,100,4,100,2019-04-05,ГС+ГРП,ГРП,Ю1
1,1060,614.642172,0.0,0,0,0,2017-05-08,ГС,ВНС,Ю1
2,1060,614.642172,7.0,100,4,100,2017-05-17,ГС+ГРП,ГРП,Ю1
3,1138,0.000000,NaN,100,4,100,2001-12-30,ННС+ГРП,ГРП,Ю1
4,1138_ФРАК,0.000000,1.0,100,4,100,2006-05-02,ННС+ГРП,ГРП,Ю1
...,...,...,...,...,...,...,...,...,...,...
199,5358,651.659420,0.0,0,0,0,2015-06-10,ГС,ВНС,Ю1
200,5358,651.659420,6.0,100,4,100,2015-06-20,ГС+ГРП,ГРП,Ю1
201,822,478.806850,0.0,0,0,0,2014-03-14,ГС,ВНС,Ю1
202,824,636.387461,0.0,0,0,0,2015-03-18,ГС,ВНС,Ю1
203,824,636.387461,6.0,100,4,100,2015-03-31,ГС+ГРП,ГРП,Ю1