In [1]:
import sys
import copy
import pandas as pd
import statistics
import datetime

In [2]:
grp_dad = pd.read_excel('one.xlsx',header=[1], index_col=[1])
print(grp_dad.head(20),grp_dad.shape)

C:\Users\USER\miniconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                                 Unnamed: 0       Дата Подрядчик  \
Номер скважины
99              Проблемы при построении ГРП 2019-10-20        КН
980             Проблемы при построении ГРП 2015-10-22        КН
980             Проблемы при построении ГРП 2015-10-21        КН
980             Проблемы при построении ГРП 2015-10-21        КН
980             Проблемы при построении ГРП 2015-10-20        КН
980             Проблемы при построении ГРП 2015-10-20        КН
980             Проблемы при построении ГРП 2015-10-11        КН
980             Проблемы при построении ГРП 2015-10-11        КН
98              Проблемы при построении ГРП 2019-07-31        КН
98              Проблемы при построении ГРП 2019-07-30        КН
98              Проблемы при построении ГРП 2019-07-30        КН
98              Проблемы при построении ГРП 2019-07-29        КН
98              Проблемы при построении ГРП 2019-07-29        КН
98              Проблемы при построении ГРП 2019-07-28        КН
98              Проблемы при построении ГРП 2019-07-28        КН
98              Проблемы при построении ГРП 2019-07-27        КН
98              Проблемы при построении ГРП 2019-07-27        КН
978             Проблемы при построении ГРП 2015-10-31        КН
977             Проблемы при построении ГРП 2015-08-29        КН
977             Проблемы при построении ГРП 2015-08-29        КН

                                                      Комментарии Страница  \
Номер скважины
99              Оборудование:  НКТ, ПРО, АМТ-  ООО "КАТКонефть...      -1_
980             Замещение проводилось 21.10.2015 г. По результ...      -1_
980             Замещение проводилось 21.10.2015 г. По результ...      -1_
980             По результатам замещения была проведена повтор...      -1_
980             Замещение проводилось 19.10.2015 г. По результ...      -1_
980             замещение проводилось 19.10.2015 г. По результ...      -1_
980             На стадии замещения при активации муфты ГРП №1...      -1_
980             По результату замещения принято решение о сокр...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
98              Оборудование:  НКТ, АМТ-  ООО "КАТКонефть"  Ст...      -1_
978             Мини ГРП проводился 31.10.2015 г. По результат...      -1_
977             По результатам замещения были внесены изменени...      -1_
977             По результату Мини ГРП были внесены изменения ...      -1_

                Unnamed: 6 Пласт  Наклон  Азимут     k  ...  \
Номер скважины                                          ...
99                     NaN    Ю3   17.00   245.0  24.6  ...
980                    NaN    Ю2   87.70   184.0  15.0  ...
980                    NaN    Ю2   90.90   184.0  15.0  ...
980                    NaN    Ю2   90.30   184.0  15.0  ...
980                    NaN    Ю2   89.90   183.0  15.0  ...
980                    NaN    Ю2   90.90   184.0  15.0  ...
980                    NaN    Ю2   90.90   184.0  15.0  ...
980                    NaN    Ю2   92.50   183.0  15.0  ...
98                     NaN    Ю2   76.83   312.0   7.7  ...
98                     NaN    Ю2   91.14   311.1   7.7  ...
98                     NaN    Ю2   93.64   310.9   7.7  ...
98                     NaN    Ю2   89.71   304.4   7.7  ...
98                     NaN    Ю2   87.69   302.4   7.7  ...
98                     NaN    Ю2   87.69   302.4   7.7  ...
98                     NaN    Ю2   88.70   300.3   7.7  ...
98                     NaN    Ю2   87.82    93.5   7.7  ...
98                     NaN    Ю2   90.14   298.9   7.7  ...
978                    NaN    Ю2    8.90   191.0  11.3  ...
977                    NaN    Ю2   88.40   160.0  23.3  ...
977                    NaN    Ю2   90.50   163.0  23.3  ...

                                                Проппант  Рпл Хорнер   Эфф  \
Номер скважины
99                             NIKA (Ptprop)+Fores+Fores        48.0  71.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  59.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  80.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  56.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  85.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  66.0
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN   NaN
980             Welltech 20/40+Welltech 16/20+Welltech 1         NaN  75.0
98                                    ForeProp+PT Prop+0        41.0  50.0
98                            ForeProp+PT Prop+PT Prop+0        33.0  52.0
98                                            ForeProp+0        32.0  37.0
98                                    ForeProp+PT Prop+0        32.0  43.0
98                                    ForeProp+PT Prop+0        35.0  48.0
98                                    ForeProp+PT Prop+0        32.0  51.0
98                                     ForeProp+PTProp+0        35.0  39.0
98                                   ForeProp+ForeProp+0        53.0  53.0
98                                   ForeProp+ForeProp+0        23.0  33.0
978              Bor 20/40+Welltech 16/20+Welltech 12/18         NaN  52.0
977              Bor 20/40+Welltech 16/20+Welltech 12/18         NaN  85.0
977              Bor 20/40+Welltech 16/20+Welltech 12/18         NaN  59.0

                Расход    Конц  Гель   М бр  V под   V без под  V гель
Номер скважины
99                 3.2   900.0   NaN   41.1    9.0         NaN    53.0
980                3.6   900.0   NaN  190.0   75.0  272.700000     NaN
980                3.6   900.0   NaN  182.0   65.0  260.400000     NaN
980                3.6   900.0   NaN  192.0   70.0  331.200000     NaN
980                3.6   900.0   NaN  183.0   65.0  262.000000     NaN
980                3.6   900.0   NaN  180.0   65.0  252.800000     NaN
980                NaN   800.0   NaN   15.0    NaN   30.042131     NaN
980                3.6   800.0   NaN  145.0   40.0  215.751469     NaN
98                 3.4   800.0   NaN  140.4    NaN   45.000000   151.0
98                 3.4   800.0   NaN  143.1    NaN   45.000000   151.0
98                 3.4   800.0   NaN  152.8    NaN   45.000000   151.0
98                 3.4   800.0   NaN  149.5    NaN   45.000000   151.0
98                 3.4   800.0   NaN  149.8    NaN   45.000000   151.0
98                 3.4   800.0   NaN  149.5    NaN   45.000000   151.0
98                 3.4   800.0   NaN  226.7    NaN   45.000000   120.0
98                 3.4   800.0   NaN  163.6    NaN   42.000000   144.0
98                 3.4   800.0   NaN  161.1    NaN   45.000000   151.0
978                3.4  1200.0   NaN  121.5   50.0  188.699945     NaN
977                3.6  1000.0   NaN  208.0   95.0  334.404409     NaN
977                3.4   900.0   NaN  165.0   63.0  267.207626     NaN

[20 rows x 35 columns] (2944, 35)

In [3]:
grp_gtm = pd.read_excel('two.xlsx',header=[1], index_col=[1])
print(grp_gtm.head(10),grp_gtm.shape)

C:\Users\USER\miniconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                   Unnamed: 0 Скважина Куст  \
Месторождение
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское   Нагнетательная        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN
Тайлаковское       Добывающая        1  NaN

                                                         Тип  \
Месторождение
Тайлаковское                                 ВНС из др. фонд
Тайлаковское                                             ГРП
Тайлаковское                                   Перевод в ППД
Тайлаковское   Выравнивание профиля притока или приёмистости
Тайлаковское                                 Проведение ГДИС
Тайлаковское   Выравнивание профиля притока или приёмистости
Тайлаковское                              Запуск без ремонта
Тайлаковское                              Запуск без ремонта
Тайлаковское                              Запуск без ремонта
Тайлаковское                          Промывка гибкой трубой

              Объект разработки до ГТМ  Объект разработки после ГТМ Страница  \
Месторождение
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_
Тайлаковское                        Ю3                          NaN      -1_

               Dэк                       Краткое описание мероприятий  \
Месторождение
Тайлаковское   NaN                 КР9-5 Перевод скважин в добывающие
Тайлаковское   NaN                               КР7-2 Проведение ГРП
Тайлаковское   NaN  КР9-6 Перевод под нагнетание из других категор...
Тайлаковское   NaN                                     Проведение ВПП
Тайлаковское   NaN                     Гидродинамические исследования
Тайлаковское   NaN                                     Проведение ВПП
Тайлаковское   NaN                        Запуск в работу без ремонта
Тайлаковское   NaN                        Запуск в работу без ремонта
Тайлаковское   NaN                        Запуск в работу без ремонта
Тайлаковское   NaN                             Промывка гибкой трубой

               Unnamed: 10  ...  Напор.1  Производительность.1  Комментарий  \
Месторождение               ...
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN
Тайлаковское           NaN  ...      NaN                   NaN          NaN

               План  Факт  Пл-ть нефти  Коб  В-ть жидк.  P нас  Unnamed: 65
Месторождение
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN
Тайлаковское    NaN   NaN          NaN  NaN         NaN    NaN          NaN

[10 rows x 65 columns] (17163, 65)

In [4]:
coordinates = pd.read_excel('three.xlsx')
print(coordinates.head(10),coordinates.shape)

  № скважины  Координата X  Координата Y  Координата забоя Х (по траектории)  \
0          1        430902       6562954                              430903
1         10        437823       6547130                              437826
2        100        434596       6559294                              434070
3       1000        435618       6555935                              435597
4       1004        455990       6565368                              456033
5       1005        455105       6565028                              455102
6       1006        456303       6565179                              456326
7       1007        455815       6565717                              455823
8      100ПЛ        434353       6559493                              434352
9        101        434378       6559105                              433680

   Координата забоя Y (по траектории)
0                             6562958
1                             6547128
2                             6559895
3                             6555955
4                             6565408
5                             6565045
6                             6565200
7                             6565751
8                             6559493
9                             6559690   (1560, 5)

In [5]:
grp_dad.reset_index(drop=True)
grp_dad.reset_index(inplace=True)

In [6]:
#вставка 22.02.22
grp_dad['Номер скважины'] = grp_dad.apply(
            lambda x:
            str(x['Номер скважины']), axis=1)
grp_gtm['Скважина'] = grp_gtm.apply(
            lambda x:
            str(x['Скважина']), axis=1)

        #вставка 22.02.22

In [7]:
plasttt = 'Ю3'
grp_dad['удалю'] = grp_dad.apply(
            lambda x:
            'нет' if plasttt in str(x['Пласт'])
            else 'да', axis=1)
grp_dad = grp_dad.drop(grp_dad[grp_dad['удалю'] == 'да'].index).reset_index(drop=True)
grp_dad = grp_dad.drop(['удалю'], axis=1)
grp_gtm.reset_index(drop=True)
grp_gtm.reset_index(inplace=True)
grp_gtm = grp_gtm[grp_gtm['Объект разработки до ГТМ'].notna()]
grp_dad.head(10)

,Номер скважины,Unnamed: 0,Дата,Подрядчик,Комментарии,Страница,Unnamed: 6,Пласт,Наклон,Азимут,...,Проппант,Рпл Хорнер,Эфф,Расход,Конц,Гель,М бр,V под,V без под,V гель
0,99,Проблемы при построении ГРП,2019-10-20,КН,"Оборудование: НКТ, ПРО, АМТ- ООО ""КАТКонефть...",-1_,NaN,Ю3,17.0,245.0,...,NIKA (Ptprop)+Fores+Fores,48.0,71.0,3.2,900.0,NaN,41.10000,9.0,NaN,53.0
1,96,Проблемы при построении ГРП,2019-06-20,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,7.0,152.0,...,НИК20/40+НИК16/20+НИК12/18,45.0,63.0,3.6,800.0,NaN,241.37000,32.0,NaN,165.0
2,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Fores+Nika+Nika+0+0,60.0,37.0,3.6,1000.0,NaN,45.95220,NaN,NaN,71.5
3,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Fores+Nika+Nika+0+0,62.0,31.5,3.6,1000.0,NaN,40.47128,NaN,NaN,54.8
4,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Fores+Nika+Nika+0+0,58.0,36.0,3.6,1000.0,NaN,41.01312,NaN,NaN,53.8
5,949,Проблемы при построении ГРП,2021-09-15,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Fores+Nika+0+0+0,42.5,48.7,3.4,1000.0,NaN,39.30424,NaN,NaN,50.8
6,949,Проблемы при построении ГРП,2021-09-14,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,Nika+Fores+Nika+0+0,44.5,56.6,3.4,800.0,NaN,70.37668,NaN,NaN,59.6
7,924,Проблемы при построении ГРП,2012-09-09,МКН,"По миниГРП: увеличили стадию ""подушка"" до 5...",-1_,NaN,Ю3,15.1,9.0,...,16/20+12/18+12/18,256.0,45.0,3.5,1200.0,NaN,NaN,52.0,210.9,NaN
8,923,NaN,2011-01-12,ШЛБ,NaN,-1_,NaN,Ю3,20.0,NaN,...,16/20Fore \n12/18Fore \n12/18ForeRCP,228.0,38.2,2.6,1024.0,NaN,NaN,60.0,216.3,NaN
9,911,Проблемы при построении ГРП,2015-03-11,КН,Мини ГРП проводился 12.03.2015 г. По результат...,-1_,NaN,Ю3,89.4,1.0,...,Bor 20/40+Welltech-Bor 16/20+Welltech-Bo,NaN,28.0,3.8,900.0,NaN,232.00000,100.0,392.4,NaN

In [8]:

grp_gtm = grp_gtm.drop(grp_gtm[grp_gtm['Объект разработки до ГТМ'] != plasttt].index).reset_index(drop=True)
grp_gtm.head(10)

,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,Краткое описание мероприятий,...,Напор.1,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65
0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,КР9-5 Перевод скважин в добывающие,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,КР7-2 Проведение ГРП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,КР9-6 Перевод под нагнетание из других категор...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,Гидродинамические исследования,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Тайлаковское,Добывающая,1,NaN,Промывка гибкой трубой,Ю3,NaN,-1_,NaN,Промывка гибкой трубой,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
coordinates['Length'] = coordinates.apply(
            lambda x: ((x['Координата забоя Х (по траектории)'] - x['Координата X']) ** (2) +
                       (x['Координата забоя Y (по траектории)'] - x['Координата Y']) ** (2)) ** (0.5)
            , axis=1)
coordinates['№ скважины'] = coordinates.apply(
            lambda x:
            str(x['№ скважины']), axis=1)
grp = copy.deepcopy(grp_dad)
coordinates.head(10)

,№ скважины,Координата X,Координата Y,Координата забоя Х (по траектории),Координата забоя Y (по траектории),Length
0,1,430902,6562954,430903,6562958,4.123106
1,10,437823,6547130,437826,6547128,3.605551
2,100,434596,6559294,434070,6559895,798.672023
3,1000,435618,6555935,435597,6555955,29.000000
4,1004,455990,6565368,456033,6565408,58.728187
5,1005,455105,6565028,455102,6565045,17.262677
6,1006,456303,6565179,456326,6565200,31.144823
7,1007,455815,6565717,455823,6565751,34.928498
8,100ПЛ,434353,6559493,434352,6559493,1.000000
9,101,434378,6559105,433680,6559690,910.729927

In [10]:
grp_now_we_go = copy.deepcopy(grp_gtm)
grp_now_we_go['Скважина'] = grp_now_we_go.apply(
            lambda x:
            str(x['Скважина']), axis=1)
grp_now_we_go.head(10)

,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,Краткое описание мероприятий,...,Напор.1,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65
0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,КР9-5 Перевод скважин в добывающие,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,КР7-2 Проведение ГРП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,КР9-6 Перевод под нагнетание из других категор...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,Гидродинамические исследования,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Тайлаковское,Добывающая,1,NaN,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Тайлаковское,Добывающая,1,NaN,Промывка гибкой трубой,Ю3,NaN,-1_,NaN,Промывка гибкой трубой,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
grp['Номер скважины'] = grp.apply(
            lambda x:
            str(x['Номер скважины']), axis=1)
        # координаты скважин для нашего объекта
my_wells = grp['Номер скважины'].tolist()
my_wells_no_repeat = []
for x in my_wells:
    if x not in my_wells_no_repeat:
        my_wells_no_repeat.append(x)
my_wells_no_repeat

['99',
 '96',
 '949',
 '924',
 '923',
 '911',
 '909',
 '906Л',
 '905',
 '9',
 '898',
 '897',
 '890',
 '883',
 '882',
 '881',
 '880',
 '878',
 '876',
 '874',
 '870',
 '87',
 '85Л1',
 '84',
 '820',
 '806',
 '80',
 '8',
 '773',
 '771',
 '770Л',
 '770',
 '77',
 '768',
 '767',
 '766',
 '764',
 '763Л',
 '763',
 '762',
 '761',
 '760',
 '76',
 '757',
 '755',
 '74',
 '739',
 '738Л2',
 '738',
 '737',
 '732',
 '731',
 '729',
 '728',
 '727',
 '726',
 '725',
 '724',
 '723',
 '722',
 '721',
 '720',
 '72',
 '714',
 '713',
 '711',
 '71',
 '708',
 '70',
 '7',
 '68Л',
 '686',
 '681',
 '680',
 '68',
 '679',
 '678',
 '675',
 '673',
 '665',
 '663',
 '662',
 '66',
 '655',
 '650',
 '649',
 '648',
 '647',
 '640',
 '637',
 '636',
 '635',
 '63',
 '629',
 '628',
 '627',
 '626',
 '622',
 '621',
 '620',
 '619Л2',
 '619',
 '617',
 '616',
 '613',
 '612',
 '61',
 '606',
 '604',
 '603',
 '602',
 '601',
 '60',
 '6',
 '5Л',
 '591',
 '585',
 '584',
 '582Л2',
 '582',
 '581',
 '577',
 '574',
 '573',
 '572',
 '571',
 '570',
 '57',
 '569',
 '567Л',
 '5676',
 '567',
 '56',
 '550',
 '549',
 '542',
 '541',
 '539',
 '537',
 '534',
 '53',
 '529',
 '527Л',
 '526',
 '515',
 '509',
 '507',
 '505',
 '503',
 '500',
 '498',
 '497',
 '496',
 '494',
 '492',
 '491',
 '489Л2',
 '489',
 '488',
 '487',
 '486',
 '485',
 '484',
 '483',
 '480',
 '48',
 '479',
 '478',
 '472',
 '471',
 '470',
 '469',
 '465',
 '464',
 '4630',
 '4627',
 '4625',
 '459',
 '458',
 '457',
 '455',
 '454',
 '451',
 '449',
 '441',
 '437',
 '436',
 '434',
 '433Л',
 '433',
 '431',
 '4306',
 '4305',
 '4302',
 '4301',
 '429',
 '428',
 '425',
 '424',
 '421',
 '415Л',
 '415',
 '412',
 '410',
 '40',
 '4',
 '39',
 '385',
 '383',
 '3825',
 '3821',
 '3781',
 '3780',
 '3742',
 '3702',
 '3701',
 '37',
 '3635',
 '3630',
 '36',
 '3552',
 '35',
 '33ПЛ',
 '31',
 '306',
 '300ПЛ',
 '30',
 '3',
 '2818Л',
 '28',
 '276',
 '27',
 '2640',
 '26',
 '258',
 '25',
 '24',
 '23Л',
 '2310',
 '2306',
 '2305',
 '2304',
 '2303',
 '2302',
 '2301',
 '2300',
 '23',
 '22',
 '21',
 '207',
 '202',
 '20',
 '1980',
 '1977',
 '1972',
 '197',
 '195',
 '194',
 '1910',
 '1909',
 '1908',
 '1906',
 '1903',
 '1902',
 '1901Л',
 '1901',
 '1900',
 '186',
 '18',
 '17Л',
 '1758',
 '1756',
 '173РЛ',
 '17',
 '1641',
 '1640',
 '1639',
 '1638',
 '1637Л',
 '1637',
 '1636',
 '1635Л',
 '1635',
 '1634',
 '1633',
 '1632',
 '1628',
 '1626',
 '1625',
 '1623',
 '1622Л',
 '1622',
 '1621',
 '1620',
 '162',
 '1610',
 '1608',
 '1607',
 '1606',
 '1605',
 '1603Л',
 '1602',
 '16',
 '158',
 '1562',
 '1561',
 '1560',
 '1559',
 '1557',
 '1556',
 '1551',
 '1549Л',
 '1549',
 '154',
 '153',
 '1523',
 '151Л',
 '1513',
 '1511',
 '151',
 '1507',
 '1503',
 '1502',
 '1501',
 '1500',
 '150',
 '15',
 '149',
 '148',
 '1468',
 '146',
 '144',
 '1433',
 '143',
 '142Л',
 '142',
 '141',
 '140',
 '14',
 '139',
 '1385',
 '1383',
 '1367',
 '1366',
 '1349',
 '1345',
 '1344',
 '1341',
 '133',
 '1320',
 '1311',
 '131',
 '1304',
 '1300',
 '130',
 '13',
 '128',
 '1259',
 '123Л',
 '123',
 '1223',
 '1220',
 '12',
 '119',
 '1160',
 '1129',
 '1128',
 '1126',
 '1124',
 '1123',
 '1122',
 '1114',
 '1113',
 '1112',
 '1111',
 '11',
 '1082',
 '1006',
 '1004',
 '10',
 '1']

In [12]:
my_wells_gtm = grp_now_we_go['Скважина'].tolist()
my_wells_no_repeat_gtm = []
for x in my_wells_gtm:
    if x not in my_wells_no_repeat_gtm:
        my_wells_no_repeat_gtm.append(x)

my_wells_no_repeat_gtm

['1',
 '10',
 '1004',
 '1005',
 '1006',
 '1007',
 '1018',
 '105',
 '1081',
 '1082',
 '1092',
 '11',
 '110',
 '1111',
 '1112',
 '1113',
 '1114',
 '1122',
 '1123',
 '1124',
 '1125',
 '1126',
 '1128',
 '1129',
 '1176',
 '119',
 '12',
 '122',
 '1220',
 '1221',
 '1223',
 '1224',
 '123',
 '1230',
 '1232',
 '124',
 '1259',
 '126',
 '1260',
 '1270',
 '1272',
 '1279',
 '128',
 '1289',
 '1290',
 '1291',
 '13',
 '130',
 '1300',
 '1302',
 '1303',
 '1304',
 '131',
 '1311',
 '1312',
 '1320',
 '133',
 '1334',
 '1341',
 '1344',
 '1345',
 '1349',
 '1366',
 '1367',
 '137',
 '1381',
 '1383',
 '1384',
 '1385',
 '1386',
 '139',
 '14',
 '140',
 '141',
 '142',
 '143',
 '1433',
 '144',
 '145',
 '146',
 '1468',
 '147',
 '148',
 '149',
 '15',
 '150',
 '1500',
 '1501',
 '1502',
 '1503',
 '1504',
 '1505',
 '1506',
 '1507',
 '1508',
 '151',
 '1511',
 '1513',
 '1521',
 '1522',
 '1523',
 '153',
 '154',
 '1544',
 '1549',
 '155',
 '1550',
 '1551',
 '1555',
 '1556',
 '1556Л',
 '1557',
 '1559',
 '1560',
 '1561',
 '1562',
 '1576',
 '158',
 '1595',
 '16',
 '1602',
 '1603',
 '1605',
 '1606',
 '1607',
 '1608',
 '1609',
 '1610',
 '1611',
 '162',
 '1620',
 '1621',
 '1622',
 '1623',
 '1625',
 '1626',
 '1628',
 '1630',
 '1631',
 '1632',
 '1633',
 '1634',
 '1635',
 '1636',
 '1637',
 '1638',
 '1639',
 '1640',
 '1641',
 '17',
 '173Р',
 '1756',
 '1758',
 '18',
 '181',
 '183',
 '186',
 '19',
 '190',
 '1900',
 '1901',
 '1902',
 '1903',
 '1906',
 '1908',
 '1909',
 '1910',
 '194',
 '195',
 '196',
 '197',
 '1970',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1978',
 '1979',
 '198',
 '1980',
 '199',
 '20',
 '201',
 '202',
 '204',
 '2056',
 '206',
 '207',
 '209',
 '21',
 '211Р',
 '215Р',
 '22',
 '23',
 '2300',
 '2301',
 '2302',
 '2303',
 '2304',
 '2305',
 '2306',
 '2309',
 '2310',
 '24',
 '25',
 '256Р',
 '258',
 '26',
 '2600',
 '2640',
 '2686',
 '2688',
 '27',
 '276',
 '28',
 '2818',
 '29',
 '2969',
 '3',
 '30',
 '300',
 '304',
 '306',
 '3093',
 '31',
 '32',
 '33',
 '34',
 '35',
 '3551',
 '3552',
 '36',
 '3630',
 '3632',
 '3633',
 '3635',
 '37',
 '3700',
 '3701',
 '3702',
 '3703',
 '3742',
 '3780',
 '3781',
 '38',
 '3817',
 '382',
 '3820',
 '3821',
 '3822',
 '3825',
 '3827',
 '3828',
 '3829',
 '383',
 '385',
 '3864',
 '39',
 '395',
 '4',
 '40',
 '405',
 '406',
 '410',
 '4100',
 '4101',
 '412',
 '413',
 '415',
 '417',
 '419',
 '42',
 '420',
 '421',
 '4221',
 '423',
 '424',
 '425',
 '426',
 '427',
 '428',
 '429',
 '430',
 '4300',
 '4301',
 '4302',
 '4305',
 '4306',
 '431',
 '432',
 '433',
 '434',
 '435',
 '436',
 '437',
 '438',
 '439',
 '440',
 '441',
 '444',
 '445',
 '446',
 '447',
 '449',
 '45',
 '450',
 '451',
 '453',
 '454',
 '455',
 '456',
 '457',
 '458',
 '459',
 '460',
 '462',
 '4625',
 '4627',
 '463',
 '4630',
 '464',
 '465',
 '466',
 '467',
 '468',
 '469',
 '47',
 '470',
 '471',
 '472',
 '473',
 '474',
 '475',
 '476',
 '477',
 '478',
 '479',
 '48',
 '480',
 '481',
 '482',
 '483',
 '484',
 '485',
 '486',
 '487',
 '488',
 '489',
 '490',
 '491',
 '492',
 '493',
 '494',
 '495',
 '496',
 '497',
 '498',
 '499',
 '5',
 '500',
 '501',
 '502',
 '503',
 '504',
 '505',
 '506',
 '507',
 '509',
 '515',
 '526',
 '527Л',
 '529',
 '53',
 '534',
 '537',
 '539',
 '540',
 '541',
 '542',
 '544',
 '549',
 '55',
 '550',
 '552',
 '554',
 '557',
 '56',
 '563',
 '567',
 '5676',
 '569',
 '57',
 '570',
 '571',
 '572',
 '573',
 '574',
 '575',
 '577',
 '578',
 '579',
 '580',
 '581',
 '582',
 '583',
 '584',
 '585',
 '588',
 '591',
 '596',
 '598',
 '599',
 '6',
 '60',
 '601',
 '602',
 '603',
 '604',
 '606',
 '608',
 '609',
 '61',
 '610',
 '611',
 '612',
 '613',
 '614',
 '615',
 '616',
 '617',
 '618',
 '619',
 '62',
 '620',
 '621',
 '622',
 '626',
 '627',
 '628',
 '629',
 '63',
 '632',
 '635',
 '636',
 '637',
 '638',
 '640',
 '641',
 '644',
 '647',
 '648',
 '649',
 '65',
 '650',
 '651',
 '655',
 '656',
 '66',
 '662',
 '663',
 '665',
 '667',
 '673',
 '675',
 '678',
 '679',
 '68',
 '680',
 '681',
 '682',
 '683',
 '686',
 '69',
 '7',
 '70',
 '705',
 '707',
 '708',
 '71',
 '710',
 '711',
 '712',
 '713',
 '714',
 '715',
 '72',
 '720',
 '721',
 '722',
 '723',
 '724',
 '725',
 '726',
 '727',
 '728',
 '729',
 '73',
 '730',
 '731',
 '732',
 '733',
 '734',
 '735',
 '737',
 '738',
 '739',
 '74',
 '741',
 '743',
 '748',
 '752',
 '754',
 '755',
 '756',
 '757',
 '758',
 '76',
 '760',
 '761',
 '762',
 '763',
 '764',
 '766',
 '767',
 '768',
 '769',
 '77',
 '770',
 '771',
 '773',
 '781',
 '79',
 '8',
 '80',
 '806',
 '820',
 '83',
 '84',
 '85',
 '86',
 '87',
 '870',
 '874',
 '876',
 '878',
 '880',
 '881',
 '882',
 '883',
 '890',
 '896',
 '897',
 '898',
 '9',
 '901',
 '904',
 '905',
 '906',
 '907',
 '908',
 '909',
 '910',
 '911',
 '916',
 '918',
 '919',
 '922',
 '923',
 '924',
 '926',
 '927',
 '936',
 '942',
 '949',
 '96',
 '971',
 '99']

In [13]:
my_wells_only_frak = []
for i in my_wells_no_repeat:
    if i not in my_wells_no_repeat_gtm:
            my_wells_only_frak.append(i)
my_wells_only_frak

['906Л',
 '85Л1',
 '770Л',
 '763Л',
 '738Л2',
 '68Л',
 '619Л2',
 '5Л',
 '582Л2',
 '567Л',
 '489Л2',
 '433Л',
 '415Л',
 '33ПЛ',
 '300ПЛ',
 '2818Л',
 '23Л',
 '1901Л',
 '17Л',
 '173РЛ',
 '1637Л',
 '1635Л',
 '1622Л',
 '1603Л',
 '1549Л',
 '151Л',
 '142Л',
 '123Л',
 '1160']

In [14]:
wells_GTM = pd.DataFrame({"Номер скважины": my_wells_no_repeat_gtm
                                  })
coordinates_f = coordinates[
            coordinates['№ скважины'].isin(my_wells_no_repeat_gtm)].reset_index(drop=True)
coordinates_f = coordinates_f.drop(['Координата X', 'Координата Y', 'Координата забоя Х (по траектории)',
                                            'Координата забоя Y (по траектории)'], axis=1)
new = coordinates_f['№ скважины'].tolist()
coordinates_f['Скважина'] = new
coordinates_f = coordinates_f.drop(['№ скважины'], axis=1)
final = grp_now_we_go.merge(coordinates_f, on='Скважина')
final

,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,Краткое описание мероприятий,...,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65,Length
0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,КР9-5 Перевод скважин в добывающие,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.123106
1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,КР7-2 Проведение ГРП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.123106
2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,КР9-6 Перевод под нагнетание из других категор...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.123106
3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.123106
4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,Гидродинамические исследования,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.123106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4923,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.365681
4924,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.365681
4925,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.365681
4926,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.365681
4927,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.365681

In [15]:
final['Длина ГС, м'] = final.apply(
        lambda x:
        x['Length'] if x['Length'] >= 110
        else 0, axis=1)
final = final.drop(['Length'], axis=1)
final

,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,Краткое описание мероприятий,...,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65,"Длина ГС, м"
0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,КР9-5 Перевод скважин в добывающие,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,КР7-2 Проведение ГРП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,КР9-6 Перевод под нагнетание из других категор...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,Гидродинамические исследования,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4923,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4924,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4925,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4926,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4927,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [16]:
final_number = final.groupby(by=['Скважина', 'ВНР.1','Тип','Объект разработки до ГТМ']).agg(
            {'Длина ГС, м': lambda x:
            x.tolist()[0]}
        )
final_number

                                                                                            Длина ГС, м
Скважина ВНР.1      Тип                                           Объект разработки до ГТМ
1        2016-03-12 ВНС из др. фонд                               Ю3                                0.0
                    ГРП                                           Ю3                                0.0
         2017-03-16 Перевод в ППД                                 Ю3                                0.0
         2018-12-03 Выравнивание профиля притока или приёмистости Ю3                                0.0
         2019-06-14 Проведение ГДИС                               Ю3                                0.0
...                                                                                                 ...
99       2020-09-02 Запуск без ремонта                            Ю3                                0.0
         2021-08-31 Запуск без ремонта                            Ю3                                0.0
         2021-09-02 Запуск без ремонта                            Ю3                                0.0
         2021-09-05 Запуск без ремонта                            Ю3                                0.0
         2021-11-27 Запуск без ремонта                            Ю3                                0.0

[4787 rows x 1 columns]

In [17]:
final_number.reset_index(inplace=True)

In [18]:
final_number

,Скважина,ВНР.1,Тип,Объект разработки до ГТМ,"Длина ГС, м"
0,1,2016-03-12,ВНС из др. фонд,Ю3,0.0
1,1,2016-03-12,ГРП,Ю3,0.0
2,1,2017-03-16,Перевод в ППД,Ю3,0.0
3,1,2018-12-03,Выравнивание профиля притока или приёмистости,Ю3,0.0
4,1,2019-06-14,Проведение ГДИС,Ю3,0.0
...,...,...,...,...,...
4782,99,2020-09-02,Запуск без ремонта,Ю3,0.0
4783,99,2021-08-31,Запуск без ремонта,Ю3,0.0
4784,99,2021-09-02,Запуск без ремонта,Ю3,0.0
4785,99,2021-09-05,Запуск без ремонта,Ю3,0.0
4786,99,2021-11-27,Запуск без ремонта,Ю3,0.0

In [19]:

final_number['Дата ВНР после'] = final_number.apply(
            lambda x:
            x['ВНР.1'] if 'ГРП' in str(x['Тип'])
            else x['ВНР.1'] if 'ВНС' in str(x['Тип'])
            
            else 'нет', axis=1)
final_number = final_number.drop(final_number[final_number['Дата ВНР после'] == 'нет'].index)
final_number

,Скважина,ВНР.1,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после
0,1,2016-03-12,ВНС из др. фонд,Ю3,0.000000,2016-03-12 00:00:00
1,1,2016-03-12,ГРП,Ю3,0.000000,2016-03-12 00:00:00
14,10,2008-10-12,ВНС,Ю3,0.000000,2008-10-12 00:00:00
15,10,2013-03-03,ГРП,Ю3,0.000000,2013-03-03 00:00:00
24,1004,2011-02-04,ВНС,Ю3,0.000000,2011-02-04 00:00:00
...,...,...,...,...,...,...
4773,96,2019-07-31,ГРП,Ю3,0.000000,2019-07-31 00:00:00
4776,971,2012-04-19,ВНС,Ю3,762.377859,2012-04-19 00:00:00
4777,971,2013-01-23,ГРП,Ю3,762.377859,2013-01-23 00:00:00
4778,99,2019-11-01,ВНС,Ю3,0.000000,2019-11-01 00:00:00
4779,99,2019-11-01,ГРП,Ю3,0.000000,2019-11-01 00:00:00

In [20]:
final_number.reset_index(inplace=True)
final_number

,index,Скважина,ВНР.1,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после
0,0,1,2016-03-12,ВНС из др. фонд,Ю3,0.000000,2016-03-12 00:00:00
1,1,1,2016-03-12,ГРП,Ю3,0.000000,2016-03-12 00:00:00
2,14,10,2008-10-12,ВНС,Ю3,0.000000,2008-10-12 00:00:00
3,15,10,2013-03-03,ГРП,Ю3,0.000000,2013-03-03 00:00:00
4,24,1004,2011-02-04,ВНС,Ю3,0.000000,2011-02-04 00:00:00
...,...,...,...,...,...,...,...
1092,4773,96,2019-07-31,ГРП,Ю3,0.000000,2019-07-31 00:00:00
1093,4776,971,2012-04-19,ВНС,Ю3,762.377859,2012-04-19 00:00:00
1094,4777,971,2013-01-23,ГРП,Ю3,762.377859,2013-01-23 00:00:00
1095,4778,99,2019-11-01,ВНС,Ю3,0.000000,2019-11-01 00:00:00
1096,4779,99,2019-11-01,ГРП,Ю3,0.000000,2019-11-01 00:00:00

In [21]:

final_number['Тип'] = final_number.apply(
            lambda x:
            'ВНС' if 'ВНС' in str(x['Тип'])
            else x['Тип'], axis=1)
final_number

,index,Скважина,ВНР.1,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после
0,0,1,2016-03-12,ВНС,Ю3,0.000000,2016-03-12 00:00:00
1,1,1,2016-03-12,ГРП,Ю3,0.000000,2016-03-12 00:00:00
2,14,10,2008-10-12,ВНС,Ю3,0.000000,2008-10-12 00:00:00
3,15,10,2013-03-03,ГРП,Ю3,0.000000,2013-03-03 00:00:00
4,24,1004,2011-02-04,ВНС,Ю3,0.000000,2011-02-04 00:00:00
...,...,...,...,...,...,...,...
1092,4773,96,2019-07-31,ГРП,Ю3,0.000000,2019-07-31 00:00:00
1093,4776,971,2012-04-19,ВНС,Ю3,762.377859,2012-04-19 00:00:00
1094,4777,971,2013-01-23,ГРП,Ю3,762.377859,2013-01-23 00:00:00
1095,4778,99,2019-11-01,ВНС,Ю3,0.000000,2019-11-01 00:00:00
1096,4779,99,2019-11-01,ГРП,Ю3,0.000000,2019-11-01 00:00:00

In [22]:
final_number['index'] = final_number.index
grp_vnski_double = final_number.drop(final_number[final_number['Тип'] != 'ВНС'].index)
grp_vnski_double['index'] = grp_vnski_double.index
grp_vnski_double = grp_vnski_double.groupby('Скважина').agg(
            {'index': lambda x:
            x.tolist()[1:]}
        )
sveta = []
for i in grp_vnski_double['index']:
    sveta += i
final_number = final_number[~final_number['index'].isin(sveta)].reset_index(drop=True)
final_number = final_number.drop(['index'], axis=1)
final_number

,Скважина,ВНР.1,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после
0,1,2016-03-12,ВНС,Ю3,0.000000,2016-03-12 00:00:00
1,1,2016-03-12,ГРП,Ю3,0.000000,2016-03-12 00:00:00
2,10,2008-10-12,ВНС,Ю3,0.000000,2008-10-12 00:00:00
3,10,2013-03-03,ГРП,Ю3,0.000000,2013-03-03 00:00:00
4,1004,2011-02-04,ВНС,Ю3,0.000000,2011-02-04 00:00:00
...,...,...,...,...,...,...
1082,96,2019-07-31,ГРП,Ю3,0.000000,2019-07-31 00:00:00
1083,971,2012-04-19,ВНС,Ю3,762.377859,2012-04-19 00:00:00
1084,971,2013-01-23,ГРП,Ю3,762.377859,2013-01-23 00:00:00
1085,99,2019-11-01,ВНС,Ю3,0.000000,2019-11-01 00:00:00
1086,99,2019-11-01,ГРП,Ю3,0.000000,2019-11-01 00:00:00

In [23]:
final_number = final_number.drop(['ВНР.1'], axis=1)
final_number.head()

  Скважина  Тип Объект разработки до ГТМ  Длина ГС, м       Дата ВНР после
0        1  ВНС                       Ю3          0.0  2016-03-12 00:00:00
1        1  ГРП                       Ю3          0.0  2016-03-12 00:00:00
2       10  ВНС                       Ю3          0.0  2008-10-12 00:00:00
3       10  ГРП                       Ю3          0.0  2013-03-03 00:00:00
4     1004  ВНС                       Ю3          0.0  2011-02-04 00:00:00

In [24]:
final_number['Полудлина трещины, м'] = final_number.apply(
            lambda x:
            100, axis=1)
final_number['Ширина трещины, мм'] = final_number.apply(
            lambda x:
            4, axis=1)
final_number['Проницаемость проппанта, Д'] = final_number.apply(
            lambda x:
            100, axis=1)
final_number['Полудлина трещины, м'] = final_number.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип'])
            else x['Полудлина трещины, м']
            , axis=1)
final_number['Ширина трещины, мм'] = final_number.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип'])
            else x['Ширина трещины, мм']
            , axis=1)
final_number['Проницаемость проппанта, Д'] = final_number.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип'])
            else x['Проницаемость проппанта, Д']
            , axis=1)
        # ДОБАВИТЬ В ВНС
final_number['Число стадий ГРП'] = final_number.apply(
            lambda x:
            1, axis=1)
final_number['Число стадий ГРП'] = final_number.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип'])
            else x['Число стадий ГРП']
            , axis=1)
final_number

,Скважина,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Число стадий ГРП
0,1,ВНС,Ю3,0.000000,2016-03-12 00:00:00,0,0,0,0
1,1,ГРП,Ю3,0.000000,2016-03-12 00:00:00,100,4,100,1
2,10,ВНС,Ю3,0.000000,2008-10-12 00:00:00,0,0,0,0
3,10,ГРП,Ю3,0.000000,2013-03-03 00:00:00,100,4,100,1
4,1004,ВНС,Ю3,0.000000,2011-02-04 00:00:00,0,0,0,0
...,...,...,...,...,...,...,...,...,...
1082,96,ГРП,Ю3,0.000000,2019-07-31 00:00:00,100,4,100,1
1083,971,ВНС,Ю3,762.377859,2012-04-19 00:00:00,0,0,0,0
1084,971,ГРП,Ю3,762.377859,2013-01-23 00:00:00,100,4,100,1
1085,99,ВНС,Ю3,0.000000,2019-11-01 00:00:00,0,0,0,0
1086,99,ГРП,Ю3,0.000000,2019-11-01 00:00:00,100,4,100,1

In [25]:
final_number['ГС/ННС'] = final_number.apply(
            lambda x:
            'ННС' if x['Длина ГС, м'] == 0
            else 'ГС', axis=1)
final_number

,Скважина,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Число стадий ГРП,ГС/ННС
0,1,ВНС,Ю3,0.000000,2016-03-12 00:00:00,0,0,0,0,ННС
1,1,ГРП,Ю3,0.000000,2016-03-12 00:00:00,100,4,100,1,ННС
2,10,ВНС,Ю3,0.000000,2008-10-12 00:00:00,0,0,0,0,ННС
3,10,ГРП,Ю3,0.000000,2013-03-03 00:00:00,100,4,100,1,ННС
4,1004,ВНС,Ю3,0.000000,2011-02-04 00:00:00,0,0,0,0,ННС
...,...,...,...,...,...,...,...,...,...,...
1082,96,ГРП,Ю3,0.000000,2019-07-31 00:00:00,100,4,100,1,ННС
1083,971,ВНС,Ю3,762.377859,2012-04-19 00:00:00,0,0,0,0,ГС
1084,971,ГРП,Ю3,762.377859,2013-01-23 00:00:00,100,4,100,1,ГС
1085,99,ВНС,Ю3,0.000000,2019-11-01 00:00:00,0,0,0,0,ННС
1086,99,ГРП,Ю3,0.000000,2019-11-01 00:00:00,100,4,100,1,ННС

In [26]:
final_number['index'] = final_number.index
final_number['index'] = final_number.apply(
            lambda x:
            str(x['index'])
            + ('_да' if x['Тип'] == 'ГРП' else ''),
            axis=1
        )

In [27]:
final_double = final_number.groupby(by=['Скважина', 'Дата ВНР после']).agg(
            {'index': lambda x:
            x.tolist()}
        )
final_double

                                   index
Скважина Дата ВНР после
1        2016-03-12            [0, 1_да]
10       2008-10-12                  [2]
         2013-03-03               [3_да]
1004     2011-02-04            [4, 5_да]
         2013-01-31               [6_да]
...                                  ...
942      2013-06-19            [1080_да]
96       2019-07-31      [1081, 1082_да]
971      2012-04-19               [1083]
         2013-01-23            [1084_да]
99       2019-11-01      [1085, 1086_да]

[870 rows x 1 columns]

In [28]:
final_double.reset_index(inplace=True)
final_double['длина'] = final_double.apply(
            lambda x:
            len(x['index']), axis=1)
final_double = final_double.drop(final_double[final_double['длина'] == 1].index)
final_double

    Скважина Дата ВНР после            index  длина
0          1     2016-03-12        [0, 1_да]      2
3       1004     2011-02-04        [4, 5_да]      2
6       1005     2011-08-31        [8, 9_да]      2
12      1092     2010-07-21      [15, 16_да]      2
13        11     2009-04-01      [17, 18_да]      2
..       ...            ...              ...    ...
855      922     2011-12-14  [1067, 1068_да]      2
860      926     2011-03-28  [1073, 1074_да]      2
864      936     2008-09-27  [1078, 1079_да]      2
866       96     2019-07-31  [1081, 1082_да]      2
869       99     2019-11-01  [1085, 1086_да]      2

[217 rows x 4 columns]

In [29]:
welles=[]
for i in final_double['index']:
    welles+=i
welles

['0',
 '1_да',
 '4',
 '5_да',
 '8',
 '9_да',
 '15',
 '16_да',
 '17',
 '18_да',
 '20',
 '21_да',
 '22',
 '23_да',
 '24',
 '25_да',
 '26',
 '27_да',
 '28',
 '29_да',
 '30',
 '31_да',
 '33',
 '34_да',
 '35',
 '36_да',
 '37',
 '38_да',
 '45',
 '46_да',
 '47',
 '48_да',
 '50',
 '51_да',
 '55',
 '56_да',
 '65',
 '66_да',
 '72',
 '73_да',
 '82',
 '83_да',
 '85',
 '86_да',
 '95',
 '96_да',
 '103',
 '104_да',
 '120',
 '121_да',
 '122',
 '123_да',
 '126',
 '127_да',
 '129',
 '130_да',
 '143',
 '144_да',
 '151',
 '152_да',
 '156',
 '157_да',
 '163',
 '164_да',
 '168',
 '169_да',
 '170',
 '171_да',
 '180',
 '181_да',
 '184',
 '185_да',
 '186',
 '187_да',
 '191',
 '192_да',
 '200',
 '201_да',
 '208',
 '209_да',
 '211',
 '212_да',
 '213',
 '214_да',
 '215',
 '216_да',
 '217',
 '218_да',
 '219',
 '220_да',
 '221',
 '222_да',
 '229',
 '230_да',
 '231',
 '232_да',
 '233',
 '234_да',
 '235',
 '236_да',
 '237',
 '238_да',
 '239',
 '240_да',
 '241',
 '242_да',
 '243',
 '244_да',
 '245',
 '246_да',
 '249',
 '250_да',
 '251',
 '252_да',
 '253',
 '254_да',
 '256',
 '257_да',
 '258',
 '259_да',
 '260',
 '261_да',
 '262',
 '263_да',
 '264',
 '265_да',
 '266',
 '267_да',
 '268',
 '269_да',
 '270',
 '271_да',
 '272',
 '273_да',
 '274',
 '275_да',
 '277',
 '278_да',
 '279',
 '280_да',
 '282',
 '283_да',
 '285',
 '286_да',
 '287',
 '288_да',
 '289',
 '290_да',
 '291',
 '292_да',
 '294',
 '295_да',
 '296',
 '297_да',
 '298',
 '299_да',
 '307',
 '308_да',
 '310',
 '311_да',
 '314',
 '315_да',
 '316',
 '317_да',
 '319',
 '320_да',
 '321',
 '322_да',
 '323',
 '324_да',
 '326',
 '327_да',
 '329',
 '330_да',
 '332',
 '333_да',
 '334',
 '335_да',
 '338',
 '339_да',
 '348',
 '349_да',
 '358',
 '359_да',
 '376',
 '377_да',
 '389',
 '390_да',
 '391',
 '392_да',
 '399',
 '400_да',
 '401',
 '402_да',
 '409',
 '410_да',
 '411',
 '412_да',
 '416',
 '417_да',
 '420',
 '421_да',
 '422',
 '423_да',
 '424',
 '425_да',
 '429',
 '430_да',
 '436',
 '437_да',
 '444',
 '445_да',
 '447',
 '448_да',
 '449',
 '450_да',
 '453',
 '454_да',
 '455',
 '456_да',
 '457',
 '458_да',
 '459',
 '460_да',
 '463',
 '464_да',
 '469',
 '470_да',
 '474',
 '475_да',
 '477',
 '478_да',
 '481',
 '482_да',
 '483',
 '484_да',
 '491',
 '492_да',
 '493',
 '494_да',
 '510',
 '511_да',
 '514',
 '515_да',
 '519',
 '520_да',
 '523',
 '524_да',
 '525',
 '526_да',
 '527',
 '528_да',
 '532',
 '533_да',
 '554',
 '555_да',
 '557',
 '558_да',
 '583',
 '584_да',
 '585',
 '586_да',
 '588',
 '589_да',
 '590',
 '591_да',
 '601',
 '602_да',
 '603',
 '604_да',
 '605',
 '606_да',
 '609',
 '610_да',
 '633',
 '634_да',
 '641',
 '642_да',
 '645',
 '646_да',
 '648',
 '649_да',
 '657',
 '658_да',
 '666',
 '667_да',
 '676',
 '677_да',
 '685',
 '686_да',
 '687',
 '688_да',
 '689',
 '690_да',
 '693',
 '694_да',
 '706',
 '707_да',
 '712',
 '713_да',
 '719',
 '720_да',
 '721',
 '722_да',
 '723',
 '724_да',
 '726',
 '727_да',
 '730',
 '731_да',
 '732',
 '733_да',
 '737',
 '738_да',
 '740',
 '741_да',
 '752',
 '753_да',
 '756',
 '757_да',
 '764',
 '765_да',
 '774',
 '775_да',
 '779',
 '780_да',
 '809',
 '810_да',
 '812',
 '813_да',
 '815',
 '816_да',
 '825',
 '826_да',
 '830',
 '831_да',
 '833',
 '834_да',
 '835',
 '836_да',
 '837',
 '838_да',
 '839',
 '840_да',
 '845',
 '846_да',
 '847',
 '848_да',
 '851',
 '852_да',
 '853',
 '854_да',
 '855',
 '856_да',
 '857',
 '858_да',
 '859',
 '860_да',
 '864',
 '865_да',
 '867',
 '868_да',
 '872',
 '873_да',
 '875',
 '876_да',
 '891',
 '892_да',
 '893',
 '894_да',
 '895',
 '896_да',
 '903',
 '904_да',
 '909',
 '910_да',
 '913',
 '914_да',
 '915',
 '916_да',
 '918',
 '919_да',
 '928',
 '929_да',
 '931',
 '932_да',
 '938',
 '939_да',
 '941',
 '942_да',
 '944',
 '945_да',
 '952',
 '953_да',
 '959',
 '960_да',
 '979',
 '980_да',
 '983',
 '984_да',
 '991',
 '992_да',
 '996',
 '997_да',
 '1008',
 '1009_да',
 '1014',
 '1015_да',
 '1024',
 '1025_да',
 '1028',
 '1029_да',
 '1037',
 '1038_да',
 '1044',
 '1045_да',
 '1047',
 '1048_да',
 '1055',
 '1056_да',
 '1057',
 '1058_да',
 '1061',
 '1062_да',
 '1067',
 '1068_да',
 '1073',
 '1074_да',
 '1078',
 '1079_да',
 '1081',
 '1082_да',
 '1085',
 '1086_да']

In [30]:
welles_corr=[]
for i in welles:
    if 'да' in i:
        welles_corr.append(i)
welles_corr

['1_да',
 '5_да',
 '9_да',
 '16_да',
 '18_да',
 '21_да',
 '23_да',
 '25_да',
 '27_да',
 '29_да',
 '31_да',
 '34_да',
 '36_да',
 '38_да',
 '46_да',
 '48_да',
 '51_да',
 '56_да',
 '66_да',
 '73_да',
 '83_да',
 '86_да',
 '96_да',
 '104_да',
 '121_да',
 '123_да',
 '127_да',
 '130_да',
 '144_да',
 '152_да',
 '157_да',
 '164_да',
 '169_да',
 '171_да',
 '181_да',
 '185_да',
 '187_да',
 '192_да',
 '201_да',
 '209_да',
 '212_да',
 '214_да',
 '216_да',
 '218_да',
 '220_да',
 '222_да',
 '230_да',
 '232_да',
 '234_да',
 '236_да',
 '238_да',
 '240_да',
 '242_да',
 '244_да',
 '246_да',
 '250_да',
 '252_да',
 '254_да',
 '257_да',
 '259_да',
 '261_да',
 '263_да',
 '265_да',
 '267_да',
 '269_да',
 '271_да',
 '273_да',
 '275_да',
 '278_да',
 '280_да',
 '283_да',
 '286_да',
 '288_да',
 '290_да',
 '292_да',
 '295_да',
 '297_да',
 '299_да',
 '308_да',
 '311_да',
 '315_да',
 '317_да',
 '320_да',
 '322_да',
 '324_да',
 '327_да',
 '330_да',
 '333_да',
 '335_да',
 '339_да',
 '349_да',
 '359_да',
 '377_да',
 '390_да',
 '392_да',
 '400_да',
 '402_да',
 '410_да',
 '412_да',
 '417_да',
 '421_да',
 '423_да',
 '425_да',
 '430_да',
 '437_да',
 '445_да',
 '448_да',
 '450_да',
 '454_да',
 '456_да',
 '458_да',
 '460_да',
 '464_да',
 '470_да',
 '475_да',
 '478_да',
 '482_да',
 '484_да',
 '492_да',
 '494_да',
 '511_да',
 '515_да',
 '520_да',
 '524_да',
 '526_да',
 '528_да',
 '533_да',
 '555_да',
 '558_да',
 '584_да',
 '586_да',
 '589_да',
 '591_да',
 '602_да',
 '604_да',
 '606_да',
 '610_да',
 '634_да',
 '642_да',
 '646_да',
 '649_да',
 '658_да',
 '667_да',
 '677_да',
 '686_да',
 '688_да',
 '690_да',
 '694_да',
 '707_да',
 '713_да',
 '720_да',
 '722_да',
 '724_да',
 '727_да',
 '731_да',
 '733_да',
 '738_да',
 '741_да',
 '753_да',
 '757_да',
 '765_да',
 '775_да',
 '780_да',
 '810_да',
 '813_да',
 '816_да',
 '826_да',
 '831_да',
 '834_да',
 '836_да',
 '838_да',
 '840_да',
 '846_да',
 '848_да',
 '852_да',
 '854_да',
 '856_да',
 '858_да',
 '860_да',
 '865_да',
 '868_да',
 '873_да',
 '876_да',
 '892_да',
 '894_да',
 '896_да',
 '904_да',
 '910_да',
 '914_да',
 '916_да',
 '919_да',
 '929_да',
 '932_да',
 '939_да',
 '942_да',
 '945_да',
 '953_да',
 '960_да',
 '980_да',
 '984_да',
 '992_да',
 '997_да',
 '1009_да',
 '1015_да',
 '1025_да',
 '1029_да',
 '1038_да',
 '1045_да',
 '1048_да',
 '1056_да',
 '1058_да',
 '1062_да',
 '1068_да',
 '1074_да',
 '1079_да',
 '1082_да',
 '1086_да']

In [31]:
welles_incorr=[]
for i in welles:
    if 'да' not in i:
        welles_incorr.append(i)
welles_incorr

['0',
 '4',
 '8',
 '15',
 '17',
 '20',
 '22',
 '24',
 '26',
 '28',
 '30',
 '33',
 '35',
 '37',
 '45',
 '47',
 '50',
 '55',
 '65',
 '72',
 '82',
 '85',
 '95',
 '103',
 '120',
 '122',
 '126',
 '129',
 '143',
 '151',
 '156',
 '163',
 '168',
 '170',
 '180',
 '184',
 '186',
 '191',
 '200',
 '208',
 '211',
 '213',
 '215',
 '217',
 '219',
 '221',
 '229',
 '231',
 '233',
 '235',
 '237',
 '239',
 '241',
 '243',
 '245',
 '249',
 '251',
 '253',
 '256',
 '258',
 '260',
 '262',
 '264',
 '266',
 '268',
 '270',
 '272',
 '274',
 '277',
 '279',
 '282',
 '285',
 '287',
 '289',
 '291',
 '294',
 '296',
 '298',
 '307',
 '310',
 '314',
 '316',
 '319',
 '321',
 '323',
 '326',
 '329',
 '332',
 '334',
 '338',
 '348',
 '358',
 '376',
 '389',
 '391',
 '399',
 '401',
 '409',
 '411',
 '416',
 '420',
 '422',
 '424',
 '429',
 '436',
 '444',
 '447',
 '449',
 '453',
 '455',
 '457',
 '459',
 '463',
 '469',
 '474',
 '477',
 '481',
 '483',
 '491',
 '493',
 '510',
 '514',
 '519',
 '523',
 '525',
 '527',
 '532',
 '554',
 '557',
 '583',
 '585',
 '588',
 '590',
 '601',
 '603',
 '605',
 '609',
 '633',
 '641',
 '645',
 '648',
 '657',
 '666',
 '676',
 '685',
 '687',
 '689',
 '693',
 '706',
 '712',
 '719',
 '721',
 '723',
 '726',
 '730',
 '732',
 '737',
 '740',
 '752',
 '756',
 '764',
 '774',
 '779',
 '809',
 '812',
 '815',
 '825',
 '830',
 '833',
 '835',
 '837',
 '839',
 '845',
 '847',
 '851',
 '853',
 '855',
 '857',
 '859',
 '864',
 '867',
 '872',
 '875',
 '891',
 '893',
 '895',
 '903',
 '909',
 '913',
 '915',
 '918',
 '928',
 '931',
 '938',
 '941',
 '944',
 '952',
 '959',
 '979',
 '983',
 '991',
 '996',
 '1008',
 '1014',
 '1024',
 '1028',
 '1037',
 '1044',
 '1047',
 '1055',
 '1057',
 '1061',
 '1067',
 '1073',
 '1078',
 '1081',
 '1085']

In [32]:
final_number = final_number[~final_number['index'].isin(welles_corr)].reset_index(drop=True)
final_number

,Скважина,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Число стадий ГРП,ГС/ННС,index
0,1,ВНС,Ю3,0.000000,2016-03-12 00:00:00,0,0,0,0,ННС,0
1,10,ВНС,Ю3,0.000000,2008-10-12 00:00:00,0,0,0,0,ННС,2
2,10,ГРП,Ю3,0.000000,2013-03-03 00:00:00,100,4,100,1,ННС,3_да
3,1004,ВНС,Ю3,0.000000,2011-02-04 00:00:00,0,0,0,0,ННС,4
4,1004,ГРП,Ю3,0.000000,2013-01-31 00:00:00,100,4,100,1,ННС,6_да
...,...,...,...,...,...,...,...,...,...,...,...
865,942,ГРП,Ю3,0.000000,2013-06-19 00:00:00,100,4,100,1,ННС,1080_да
866,96,ВНС,Ю3,0.000000,2019-07-31 00:00:00,0,0,0,0,ННС,1081
867,971,ВНС,Ю3,762.377859,2012-04-19 00:00:00,0,0,0,0,ГС,1083
868,971,ГРП,Ю3,762.377859,2013-01-23 00:00:00,100,4,100,1,ГС,1084_да
869,99,ВНС,Ю3,0.000000,2019-11-01 00:00:00,0,0,0,0,ННС,1085

In [33]:
final_number['ГС/ННС'] = final_number.apply(
            lambda x:
            str(x['ГС/ННС'])
            + ('+ГРП' if x['index'] in welles_incorr else ''),
            axis=1
        )
final_number

,Скважина,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Число стадий ГРП,ГС/ННС,index
0,1,ВНС,Ю3,0.000000,2016-03-12 00:00:00,0,0,0,0,ННС+ГРП,0
1,10,ВНС,Ю3,0.000000,2008-10-12 00:00:00,0,0,0,0,ННС,2
2,10,ГРП,Ю3,0.000000,2013-03-03 00:00:00,100,4,100,1,ННС,3_да
3,1004,ВНС,Ю3,0.000000,2011-02-04 00:00:00,0,0,0,0,ННС+ГРП,4
4,1004,ГРП,Ю3,0.000000,2013-01-31 00:00:00,100,4,100,1,ННС,6_да
...,...,...,...,...,...,...,...,...,...,...,...
865,942,ГРП,Ю3,0.000000,2013-06-19 00:00:00,100,4,100,1,ННС,1080_да
866,96,ВНС,Ю3,0.000000,2019-07-31 00:00:00,0,0,0,0,ННС+ГРП,1081
867,971,ВНС,Ю3,762.377859,2012-04-19 00:00:00,0,0,0,0,ГС,1083
868,971,ГРП,Ю3,762.377859,2013-01-23 00:00:00,100,4,100,1,ГС,1084_да
869,99,ВНС,Ю3,0.000000,2019-11-01 00:00:00,0,0,0,0,ННС+ГРП,1085

In [34]:
final_number['Полудлина трещины, м'] = final_number.apply(
            lambda x:
            100 if 'ГРП' in str(x['ГС/ННС'])
            else x['Полудлина трещины, м']
            , axis=1)
final_number['Ширина трещины, мм'] = final_number.apply(
            lambda x:
            4 if 'ГРП' in str(x['ГС/ННС'])
            else x['Ширина трещины, мм']
            , axis=1)
final_number['Проницаемость проппанта, Д'] = final_number.apply(
            lambda x:
            100 if 'ГРП' in str(x['ГС/ННС'])
            else x['Проницаемость проппанта, Д']
            , axis=1)
final_number['Число стадий ГРП'] = final_number.apply(
            lambda x:
            1 if 'ГРП' in str(x['ГС/ННС'])
            else x['Число стадий ГРП']
            , axis=1)
final_number

,Скважина,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Число стадий ГРП,ГС/ННС,index
0,1,ВНС,Ю3,0.000000,2016-03-12 00:00:00,100,4,100,1,ННС+ГРП,0
1,10,ВНС,Ю3,0.000000,2008-10-12 00:00:00,0,0,0,0,ННС,2
2,10,ГРП,Ю3,0.000000,2013-03-03 00:00:00,100,4,100,1,ННС,3_да
3,1004,ВНС,Ю3,0.000000,2011-02-04 00:00:00,100,4,100,1,ННС+ГРП,4
4,1004,ГРП,Ю3,0.000000,2013-01-31 00:00:00,100,4,100,1,ННС,6_да
...,...,...,...,...,...,...,...,...,...,...,...
865,942,ГРП,Ю3,0.000000,2013-06-19 00:00:00,100,4,100,1,ННС,1080_да
866,96,ВНС,Ю3,0.000000,2019-07-31 00:00:00,100,4,100,1,ННС+ГРП,1081
867,971,ВНС,Ю3,762.377859,2012-04-19 00:00:00,0,0,0,0,ГС,1083
868,971,ГРП,Ю3,762.377859,2013-01-23 00:00:00,100,4,100,1,ГС,1084_да
869,99,ВНС,Ю3,0.000000,2019-11-01 00:00:00,100,4,100,1,ННС+ГРП,1085

In [35]:
final_number['Тип'] = final_number.apply(
            lambda x:
            'ГРП' if 'ГРП' in str(x['ГС/ННС'])
            else x['Тип']
            , axis=1)
final_number

,Скважина,Тип,Объект разработки до ГТМ,"Длина ГС, м",Дата ВНР после,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Число стадий ГРП,ГС/ННС,index
0,1,ГРП,Ю3,0.000000,2016-03-12 00:00:00,100,4,100,1,ННС+ГРП,0
1,10,ВНС,Ю3,0.000000,2008-10-12 00:00:00,0,0,0,0,ННС,2
2,10,ГРП,Ю3,0.000000,2013-03-03 00:00:00,100,4,100,1,ННС,3_да
3,1004,ГРП,Ю3,0.000000,2011-02-04 00:00:00,100,4,100,1,ННС+ГРП,4
4,1004,ГРП,Ю3,0.000000,2013-01-31 00:00:00,100,4,100,1,ННС,6_да
...,...,...,...,...,...,...,...,...,...,...,...
865,942,ГРП,Ю3,0.000000,2013-06-19 00:00:00,100,4,100,1,ННС,1080_да
866,96,ГРП,Ю3,0.000000,2019-07-31 00:00:00,100,4,100,1,ННС+ГРП,1081
867,971,ВНС,Ю3,762.377859,2012-04-19 00:00:00,0,0,0,0,ГС,1083
868,971,ГРП,Ю3,762.377859,2013-01-23 00:00:00,100,4,100,1,ГС,1084_да
869,99,ГРП,Ю3,0.000000,2019-11-01 00:00:00,100,4,100,1,ННС+ГРП,1085

In [36]:
new_400 = final_number['Скважина'].tolist()
final_number['Скважина №'] = new_400
final_number = final_number.drop(['Скважина'], axis=1)
final_number = final_number.drop(['index'], axis=1)
new_300 = final_number['Тип'].tolist()
final_number['Тип ГТМ'] = new_300
final_number = final_number.drop(['Тип'], axis=1)
new_200 = final_number['Объект разработки до ГТМ'].tolist()
final_number['Пласт'] = new_200
final_number = final_number.drop(['Объект разработки до ГТМ'], axis=1)
final_number = final_number.reindex(
            columns=['Скважина №', 'Длина ГС, м', 'Число стадий ГРП', 'Полудлина трещины, м', 'Ширина трещины, мм',
                     'Проницаемость проппанта, Д', 'Дата ВНР после','ГС/ННС','Тип ГТМ', 'Пласт'])
final_number

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.000000,1,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3
1,10,0.000000,0,0,0,0,2008-10-12 00:00:00,ННС,ВНС,Ю3
2,10,0.000000,1,100,4,100,2013-03-03 00:00:00,ННС,ГРП,Ю3
3,1004,0.000000,1,100,4,100,2011-02-04 00:00:00,ННС+ГРП,ГРП,Ю3
4,1004,0.000000,1,100,4,100,2013-01-31 00:00:00,ННС,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,1,100,4,100,2013-06-19 00:00:00,ННС,ГРП,Ю3
866,96,0.000000,1,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3
867,971,762.377859,0,0,0,0,2012-04-19 00:00:00,ГС,ВНС,Ю3
868,971,762.377859,1,100,4,100,2013-01-23 00:00:00,ГС,ГРП,Ю3
869,99,0.000000,1,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3

In [37]:
final_number.head(30)

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.000000,1,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3
1,10,0.000000,0,0,0,0,2008-10-12 00:00:00,ННС,ВНС,Ю3
2,10,0.000000,1,100,4,100,2013-03-03 00:00:00,ННС,ГРП,Ю3
3,1004,0.000000,1,100,4,100,2011-02-04 00:00:00,ННС+ГРП,ГРП,Ю3
4,1004,0.000000,1,100,4,100,2013-01-31 00:00:00,ННС,ГРП,Ю3
5,1004,0.000000,1,100,4,100,2013-03-03 00:00:00,ННС,ГРП,Ю3
6,1005,0.000000,1,100,4,100,2011-08-31 00:00:00,ННС+ГРП,ГРП,Ю3
7,1006,0.000000,1,100,4,100,2019-08-16 00:00:00,ННС,ГРП,Ю3
8,1007,0.000000,0,0,0,0,2010-10-28 00:00:00,ННС,ВНС,Ю3
9,105,0.000000,0,0,0,0,2008-08-27 00:00:00,ННС,ВНС,Ю3
10,105,0.000000,1,100,4,100,2010-10-23 00:00:00,ННС,ГРП,Ю3
11,105,0.000000,1,100,4,100,2013-02-03 00:00:00,ННС,ГРП,Ю3
12,1092,0.000000,1,100,4,100,2010-07-21 00:00:00,ННС+ГРП,ГРП,Ю3
13,11,0.000000,1,100,4,100,2009-04-01 00:00:00,ННС+ГРП,ГРП,Ю3
14,110,817.866126,0,0,0,0,2020-02-17 00:00:00,ГС,ВНС,Ю3
15,1111,626.258732,1,100,4,100,2015-03-27 00:00:00,ГС+ГРП,ГРП,Ю3
16,1112,530.136775,1,100,4,100,2015-05-07 00:00:00,ГС+ГРП,ГРП,Ю3
17,1113,649.148673,1,100,4,100,2015-06-16 00:00:00,ГС+ГРП,ГРП,Ю3
18,1122,782.218000,1,100,4,100,2020-03-03 00:00:00,ГС+ГРП,ГРП,Ю3
19,1123,760.906039,1,100,4,100,2020-03-31 00:00:00,ГС+ГРП,ГРП,Ю3
20,1124,505.466122,1,100,4,100,2020-03-17 00:00:00,ГС+ГРП,ГРП,Ю3
21,1125,0.000000,0,0,0,0,2020-01-30 00:00:00,ННС,ВНС,Ю3
22,1126,847.651461,1,100,4,100,2019-10-05 00:00:00,ГС+ГРП,ГРП,Ю3
23,1128,636.704013,1,100,4,100,2019-11-08 00:00:00,ГС+ГРП,ГРП,Ю3
24,1129,616.370019,1,100,4,100,2020-01-02 00:00:00,ГС+ГРП,ГРП,Ю3
25,1176,0.000000,0,0,0,0,2021-07-16 00:00:00,ННС,ВНС,Ю3
26,119,0.000000,0,0,0,0,2009-11-03 00:00:00,ННС,ВНС,Ю3
27,119,0.000000,1,100,4,100,2010-03-31 00:00:00,ННС,ГРП,Ю3
28,12,0.000000,0,0,0,0,2007-10-09 00:00:00,ННС,ВНС,Ю3
29,12,0.000000,1,100,4,100,2008-01-09 00:00:00,ННС,ГРП,Ю3

In [38]:
#final_number.loc[final_number['Тип'] == 'ЗБС']

In [39]:
final_number

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.000000,1,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3
1,10,0.000000,0,0,0,0,2008-10-12 00:00:00,ННС,ВНС,Ю3
2,10,0.000000,1,100,4,100,2013-03-03 00:00:00,ННС,ГРП,Ю3
3,1004,0.000000,1,100,4,100,2011-02-04 00:00:00,ННС+ГРП,ГРП,Ю3
4,1004,0.000000,1,100,4,100,2013-01-31 00:00:00,ННС,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,1,100,4,100,2013-06-19 00:00:00,ННС,ГРП,Ю3
866,96,0.000000,1,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3
867,971,762.377859,0,0,0,0,2012-04-19 00:00:00,ГС,ВНС,Ю3
868,971,762.377859,1,100,4,100,2013-01-23 00:00:00,ГС,ГРП,Ю3
869,99,0.000000,1,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3

In [40]:
final_number['Дата ВНР после'] = final_number.apply(
            lambda x:
            str(x['Дата ВНР после']), axis=1)
final_number['месяц с грп'] = final_number.apply(
            lambda x:
            x['Дата ВНР после'][:4],
            axis=1
        )
final_number

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп
0,1,0.000000,1,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016
1,10,0.000000,0,0,0,0,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008
2,10,0.000000,1,100,4,100,2013-03-03 00:00:00,ННС,ГРП,Ю3,2013
3,1004,0.000000,1,100,4,100,2011-02-04 00:00:00,ННС+ГРП,ГРП,Ю3,2011
4,1004,0.000000,1,100,4,100,2013-01-31 00:00:00,ННС,ГРП,Ю3,2013
...,...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,1,100,4,100,2013-06-19 00:00:00,ННС,ГРП,Ю3,2013
866,96,0.000000,1,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019
867,971,762.377859,0,0,0,0,2012-04-19 00:00:00,ГС,ВНС,Ю3,2012
868,971,762.377859,1,100,4,100,2013-01-23 00:00:00,ГС,ГРП,Ю3,2013
869,99,0.000000,1,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019

In [41]:
grp = copy.deepcopy(grp_dad)
grp['Дата'] = grp.apply(
            lambda x:
            str(x['Дата']), axis=1)
grp['месяц с грп'] = grp.apply(
            lambda x:
            x['Дата'][:4],
            axis=1
        )
grp

,Номер скважины,Unnamed: 0,Дата,Подрядчик,Комментарии,Страница,Unnamed: 6,Пласт,Наклон,Азимут,...,Рпл Хорнер,Эфф,Расход,Конц,Гель,М бр,V под,V без под,V гель,месяц с грп
0,99,Проблемы при построении ГРП,2019-10-20 00:00:00,КН,"Оборудование: НКТ, ПРО, АМТ- ООО ""КАТКонефть...",-1_,NaN,Ю3,17.0,245.0,...,48.0,71.0,3.2,900.0,NaN,41.10000,9.0,NaN,53.0,2019
1,96,Проблемы при построении ГРП,2019-06-20 00:00:00,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,7.0,152.0,...,45.0,63.0,3.6,800.0,NaN,241.37000,32.0,NaN,165.0,2019
2,949,Проблемы при построении ГРП,2021-09-15 00:00:00,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,60.0,37.0,3.6,1000.0,NaN,45.95220,NaN,NaN,71.5,2021
3,949,Проблемы при построении ГРП,2021-09-15 00:00:00,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,62.0,31.5,3.6,1000.0,NaN,40.47128,NaN,NaN,54.8,2021
4,949,Проблемы при построении ГРП,2021-09-15 00:00:00,КН,"Оборудование: НКТ, АМТ- ООО ""КАТКонефть"" Сти...",-1_,NaN,Ю3,93.7,305.1,...,58.0,36.0,3.6,1000.0,NaN,41.01312,NaN,NaN,53.8,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,1082,Проблемы при построении ГРП,2020-02-07 00:00:00,МКМ,"ГРП по плану (+), 42 т. Выполнена стадия Запо...",-1_,NaN,Ю3,20.0,305.0,...,49.0,74.8,3.6,800.0,NaN,50.00000,35.0,NaN,145.0,2020
1044,1006,Проблемы при построении ГРП,2019-07-26 00:00:00,SLB,По согласованию с представителями Заказчика пр...,-1_,NaN,Ю3,22.0,40.0,...,61.0,43.0,3.4,800.0,NaN,133.24063,NaN,5.0,73.0,2019
1045,1004,Проблемы при построении ГРП,2013-01-03 00:00:00,ШЛБ,По результатам МиниГРП масса пропанта по перво...,-1_,NaN,Ю3,40.0,34.0,...,200.0,32.0,3.8,890.0,NaN,NaN,110.0,367.3,NaN,2013
1046,10,NaN,2013-02-16 00:00:00,ШЛБ,При проведении работ по ГРП 16/02/2013 закачка...,-1_,NaN,Ю3,2.0,NaN,...,235.0,73.0,2.6,1056.0,NaN,NaN,14.0,100.0,NaN,2013
1047,1,Проблемы при построении ГРП,2016-02-23 00:00:00,КН,Мини ГРП проводился 23.02.2016 г. По результат...,-1_,NaN,Ю3,1.0,NaN,...,NaN,43.0,3.4,1200.0,NaN,85.00000,30.0,154.4,NaN,2016

In [42]:
grp = grp.groupby(by=['Номер скважины', 'месяц с грп']).agg(
            {'Пласт': lambda x:
            x.tolist()}
        )
grp

                                           Пласт
Номер скважины месяц с грп
1              2016                         [Ю3]
10             2013                         [Ю3]
1004           2013                         [Ю3]
1006           2019                         [Ю3]
1082           2020                         [Ю3]
...                                          ...
923            2011                         [Ю3]
924            2012                         [Ю3]
949            2021         [Ю3, Ю3, Ю3, Ю3, Ю3]
96             2019                         [Ю3]
99             2019                         [Ю3]

[449 rows x 1 columns]

In [43]:
grp['Количество'] = grp.apply(
            lambda x:
            len(x['Пласт'])
            , axis=1)
grp

                                           Пласт  Количество
Номер скважины месяц с грп
1              2016                         [Ю3]           1
10             2013                         [Ю3]           1
1004           2013                         [Ю3]           1
1006           2019                         [Ю3]           1
1082           2020                         [Ю3]           1
...                                          ...         ...
923            2011                         [Ю3]           1
924            2012                         [Ю3]           1
949            2021         [Ю3, Ю3, Ю3, Ю3, Ю3]           5
96             2019                         [Ю3]           1
99             2019                         [Ю3]           1

[449 rows x 2 columns]

In [44]:
grp.reset_index(inplace=True)
grp

    Номер скважины месяц с грп                 Пласт  Количество
0                1        2016                  [Ю3]           1
1               10        2013                  [Ю3]           1
2             1004        2013                  [Ю3]           1
3             1006        2019                  [Ю3]           1
4             1082        2020                  [Ю3]           1
..             ...         ...                   ...         ...
444            923        2011                  [Ю3]           1
445            924        2012                  [Ю3]           1
446            949        2021  [Ю3, Ю3, Ю3, Ю3, Ю3]           5
447             96        2019                  [Ю3]           1
448             99        2019                  [Ю3]           1

[449 rows x 4 columns]

In [45]:
new_100 = grp['Номер скважины'].tolist()
grp['Скважина №'] = new_100
grp = grp.drop(['Номер скважины'], axis=1)
grp

    месяц с грп                 Пласт  Количество Скважина №
0          2016                  [Ю3]           1          1
1          2013                  [Ю3]           1         10
2          2013                  [Ю3]           1       1004
3          2019                  [Ю3]           1       1006
4          2020                  [Ю3]           1       1082
..          ...                   ...         ...        ...
444        2011                  [Ю3]           1        923
445        2012                  [Ю3]           1        924
446        2021  [Ю3, Ю3, Ю3, Ю3, Ю3]           5        949
447        2019                  [Ю3]           1         96
448        2019                  [Ю3]           1         99

[449 rows x 4 columns]

In [46]:
grp = grp.drop(['Пласт'], axis=1)
grp

    месяц с грп  Количество Скважина №
0          2016           1          1
1          2013           1         10
2          2013           1       1004
3          2019           1       1006
4          2020           1       1082
..          ...         ...        ...
444        2011           1        923
445        2012           1        924
446        2021           5        949
447        2019           1         96
448        2019           1         99

[449 rows x 3 columns]

In [47]:
sotired = final_number.merge(grp, on=['месяц с грп', 'Скважина №'],how='left')
sotired

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Количество
0,1,0.000000,1,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016,1.0
1,10,0.000000,0,0,0,0,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008,NaN
2,10,0.000000,1,100,4,100,2013-03-03 00:00:00,ННС,ГРП,Ю3,2013,1.0
3,1004,0.000000,1,100,4,100,2011-02-04 00:00:00,ННС+ГРП,ГРП,Ю3,2011,NaN
4,1004,0.000000,1,100,4,100,2013-01-31 00:00:00,ННС,ГРП,Ю3,2013,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,1,100,4,100,2013-06-19 00:00:00,ННС,ГРП,Ю3,2013,NaN
866,96,0.000000,1,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
867,971,762.377859,0,0,0,0,2012-04-19 00:00:00,ГС,ВНС,Ю3,2012,NaN
868,971,762.377859,1,100,4,100,2013-01-23 00:00:00,ГС,ГРП,Ю3,2013,NaN
869,99,0.000000,1,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0

In [48]:

sotired = sotired.drop(['Число стадий ГРП'], axis=1)
sotired

,Скважина №,"Длина ГС, м","Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Количество
0,1,0.000000,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016,1.0
1,10,0.000000,0,0,0,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008,NaN
2,10,0.000000,100,4,100,2013-03-03 00:00:00,ННС,ГРП,Ю3,2013,1.0
3,1004,0.000000,100,4,100,2011-02-04 00:00:00,ННС+ГРП,ГРП,Ю3,2011,NaN
4,1004,0.000000,100,4,100,2013-01-31 00:00:00,ННС,ГРП,Ю3,2013,1.0
...,...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,100,4,100,2013-06-19 00:00:00,ННС,ГРП,Ю3,2013,NaN
866,96,0.000000,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
867,971,762.377859,0,0,0,2012-04-19 00:00:00,ГС,ВНС,Ю3,2012,NaN
868,971,762.377859,100,4,100,2013-01-23 00:00:00,ГС,ГРП,Ю3,2013,NaN
869,99,0.000000,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0

In [49]:
new_50 = sotired['Количество'].tolist()
sotired['Число стадий ГРП'] = new_50
sotired = sotired.drop(['Количество'], axis=1)
sotired['Число стадий ГРП'] = sotired.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Число стадий ГРП']
            , axis=1)
sotired

,Скважина №,"Длина ГС, м","Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Число стадий ГРП
0,1,0.000000,100,4,100,2016-03-12 00:00:00,ННС+ГРП,ГРП,Ю3,2016,1.0
1,10,0.000000,0,0,0,2008-10-12 00:00:00,ННС,ВНС,Ю3,2008,0.0
2,10,0.000000,100,4,100,2013-03-03 00:00:00,ННС,ГРП,Ю3,2013,1.0
3,1004,0.000000,100,4,100,2011-02-04 00:00:00,ННС+ГРП,ГРП,Ю3,2011,NaN
4,1004,0.000000,100,4,100,2013-01-31 00:00:00,ННС,ГРП,Ю3,2013,1.0
...,...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,100,4,100,2013-06-19 00:00:00,ННС,ГРП,Ю3,2013,NaN
866,96,0.000000,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
867,971,762.377859,0,0,0,2012-04-19 00:00:00,ГС,ВНС,Ю3,2012,0.0
868,971,762.377859,100,4,100,2013-01-23 00:00:00,ГС,ГРП,Ю3,2013,NaN
869,99,0.000000,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0

In [50]:
sotired.tail(30)

,Скважина №,"Длина ГС, м","Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Число стадий ГРП
840,9,0.000000,0,0,0,2007-06-21 00:00:00,ННС,ВНС,Ю3,2007,0.0
841,9,0.000000,100,4,100,2007-08-19 00:00:00,ННС,ГРП,Ю3,2007,NaN
842,9,0.000000,100,4,100,2008-02-20 00:00:00,ННС,ГРП,Ю3,2008,1.0
843,901,0.000000,0,0,0,2010-09-24 00:00:00,ННС,ВНС,Ю3,2010,0.0
844,901,0.000000,100,4,100,2010-11-10 00:00:00,ННС,ГРП,Ю3,2010,NaN
845,904,0.000000,0,0,0,2010-11-11 00:00:00,ННС,ВНС,Ю3,2010,0.0
846,905,0.000000,100,4,100,2010-10-28 00:00:00,ННС+ГРП,ГРП,Ю3,2010,1.0
847,906,0.000000,100,4,100,2010-11-26 00:00:00,ННС+ГРП,ГРП,Ю3,2010,NaN
848,907,417.579932,0,0,0,2011-05-22 00:00:00,ГС,ВНС,Ю3,2011,0.0
849,908,621.097416,0,0,0,2011-03-21 00:00:00,ГС,ВНС,Ю3,2011,0.0
850,909,294.803324,100,4,100,2011-01-10 00:00:00,ГС+ГРП,ГРП,Ю3,2011,NaN
851,909,294.803324,100,4,100,2014-07-03 00:00:00,ГС,ГРП,Ю3,2014,4.0
852,911,686.385460,0,0,0,2011-01-27 00:00:00,ГС,ВНС,Ю3,2011,0.0
853,911,686.385460,100,4,100,2015-03-18 00:00:00,ГС,ГРП,Ю3,2015,1.0
854,919,624.759954,0,0,0,2011-06-17 00:00:00,ГС,ВНС,Ю3,2011,0.0
855,922,0.000000,100,4,100,2011-12-14 00:00:00,ННС+ГРП,ГРП,Ю3,2011,NaN
856,923,0.000000,0,0,0,2010-12-10 00:00:00,ННС,ВНС,Ю3,2010,0.0
857,923,0.000000,100,4,100,2011-01-22 00:00:00,ННС,ГРП,Ю3,2011,1.0
858,924,0.000000,0,0,0,2010-11-28 00:00:00,ННС,ВНС,Ю3,2010,0.0
859,924,0.000000,100,4,100,2012-09-19 00:00:00,ННС,ГРП,Ю3,2012,1.0
860,926,0.000000,100,4,100,2011-03-28 00:00:00,ННС+ГРП,ГРП,Ю3,2011,NaN
861,927,0.000000,0,0,0,2011-11-14 00:00:00,ННС,ВНС,Ю3,2011,0.0
862,927,0.000000,100,4,100,2012-03-08 00:00:00,ННС,ГРП,Ю3,2012,NaN
863,927,0.000000,100,4,100,2014-10-26 00:00:00,ННС,ГРП,Ю3,2014,NaN
864,936,0.000000,100,4,100,2008-09-27 00:00:00,ННС+ГРП,ГРП,Ю3,2008,NaN
865,942,0.000000,100,4,100,2013-06-19 00:00:00,ННС,ГРП,Ю3,2013,NaN
866,96,0.000000,100,4,100,2019-07-31 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0
867,971,762.377859,0,0,0,2012-04-19 00:00:00,ГС,ВНС,Ю3,2012,0.0
868,971,762.377859,100,4,100,2013-01-23 00:00:00,ГС,ГРП,Ю3,2013,NaN
869,99,0.000000,100,4,100,2019-11-01 00:00:00,ННС+ГРП,ГРП,Ю3,2019,1.0

In [51]:
sotired['Дата ВНР после'] = pd.to_datetime(sotired['Дата ВНР после'])

sotired

,Скважина №,"Длина ГС, м","Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Число стадий ГРП
0,1,0.000000,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3,2016,1.0
1,10,0.000000,0,0,0,2008-10-12,ННС,ВНС,Ю3,2008,0.0
2,10,0.000000,100,4,100,2013-03-03,ННС,ГРП,Ю3,2013,1.0
3,1004,0.000000,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3,2011,NaN
4,1004,0.000000,100,4,100,2013-01-31,ННС,ГРП,Ю3,2013,1.0
...,...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,100,4,100,2013-06-19,ННС,ГРП,Ю3,2013,NaN
866,96,0.000000,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3,2019,1.0
867,971,762.377859,0,0,0,2012-04-19,ГС,ВНС,Ю3,2012,0.0
868,971,762.377859,100,4,100,2013-01-23,ГС,ГРП,Ю3,2013,NaN
869,99,0.000000,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3,2019,1.0

In [52]:
sotired['ГС/ННС'] = sotired.apply(
            lambda x:
            str(x['ГС/ННС']) + '+ГРП' if str(x['Тип ГТМ']) == 'ГРП' and 'ГРП' not in str(x['ГС/ННС'])
            else x['ГС/ННС'], axis=1)
sotired

,Скважина №,"Длина ГС, м","Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,месяц с грп,Число стадий ГРП
0,1,0.000000,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3,2016,1.0
1,10,0.000000,0,0,0,2008-10-12,ННС,ВНС,Ю3,2008,0.0
2,10,0.000000,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3,2013,1.0
3,1004,0.000000,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3,2011,NaN
4,1004,0.000000,100,4,100,2013-01-31,ННС+ГРП,ГРП,Ю3,2013,1.0
...,...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,100,4,100,2013-06-19,ННС+ГРП,ГРП,Ю3,2013,NaN
866,96,0.000000,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3,2019,1.0
867,971,762.377859,0,0,0,2012-04-19,ГС,ВНС,Ю3,2012,0.0
868,971,762.377859,100,4,100,2013-01-23,ГС+ГРП,ГРП,Ю3,2013,NaN
869,99,0.000000,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3,2019,1.0

In [53]:
sotired = sotired.reindex(
            columns=['Скважина №', 'Длина ГС, м', 'Число стадий ГРП', 'Полудлина трещины, м', 'Ширина трещины, мм',
                     'Проницаемость проппанта, Д', 'Дата ВНР после', 'ГС/ННС', 'Тип ГТМ', 'Пласт'])
sotired['Число стадий ГРП'] = sotired.apply(
            lambda x:
            0 if str(x['Тип ГТМ']) == 'ВНС'
            else x['Число стадий ГРП'], axis=1)
sotired

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3
2,10,0.000000,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
3,1004,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3
4,1004,0.000000,1.0,100,4,100,2013-01-31,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,NaN,100,4,100,2013-06-19,ННС+ГРП,ГРП,Ю3
866,96,0.000000,1.0,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
867,971,762.377859,0.0,0,0,0,2012-04-19,ГС,ВНС,Ю3
868,971,762.377859,NaN,100,4,100,2013-01-23,ГС+ГРП,ГРП,Ю3
869,99,0.000000,1.0,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3

In [54]:
sotired['Полудлина трещины, м'] = sotired.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Полудлина трещины, м']
            , axis=1)
sotired['Ширина трещины, мм'] = sotired.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Ширина трещины, мм']
            , axis=1)
sotired['Проницаемость проппанта, Д'] = sotired.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Проницаемость проппанта, Д']
            , axis=1)
        # ДОБАВИТЬ В ВНС
sotired['Число стадий ГРП'] = sotired.apply(
            lambda x:
            0 if 'ВНС' in str(x['Тип ГТМ'])
            else x['Число стадий ГРП']
            , axis=1)
sotired

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3
2,10,0.000000,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
3,1004,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3
4,1004,0.000000,1.0,100,4,100,2013-01-31,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
865,942,0.000000,NaN,100,4,100,2013-06-19,ННС+ГРП,ГРП,Ю3
866,96,0.000000,1.0,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
867,971,762.377859,0.0,0,0,0,2012-04-19,ГС,ВНС,Ю3
868,971,762.377859,NaN,100,4,100,2013-01-23,ГС+ГРП,ГРП,Ю3
869,99,0.000000,1.0,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3

In [55]:
        # удаляем если в одном месяце
sotired['index']=sotired.index
dele = copy.deepcopy(sotired)
dele['чек'] = dele.apply(
            lambda x:
            x['Скважина №'].partition('_')[0] if '_' in str(x['Скважина №'])
            else x['Скважина №'], axis=1)
dele['месяц'] = dele.apply(
            lambda x:
            str(x['Дата ВНР после'])[:7],
            axis=1
        )
dele = dele.groupby(by=['чек', 'месяц']).agg(
            {'index': lambda x:
            x.tolist()}
        )
dele['скока_их'] = dele.apply(
            lambda x: len(x['index'])
            , axis=1)
dele = dele.drop(dele[dele['скока_их'] < 2].index).reset_index(drop=True)
to_stay = []
all_wells = []
for i in dele['index']:
    all_wells += i
for i in dele['index']:
    to_stay.append(i[-1])
dele

              index  скока_их
0          [85, 86]         2
1        [275, 276]         2
2        [286, 287]         2
3        [333, 334]         2
4        [337, 338]         2
5        [386, 387]         2
6   [578, 579, 580]         3
7   [587, 588, 589]         3
8        [592, 593]         2
9        [720, 721]         2
10       [825, 826]         2
11       [827, 828]         2
12       [829, 830]         2
13       [832, 833]         2
14       [834, 835]         2

In [56]:
alli = copy.deepcopy(sotired)
alli = alli[alli['index'].isin(all_wells)].reset_index(drop=True)
alli = alli.drop(alli[alli['Тип ГТМ'] == 'ВНС'].index).reset_index(drop=True)
alli = alli.groupby('Скважина №').agg(
            {'index': lambda x:
            x.tolist()[0]}
        )
definetely_stay = alli['index'].tolist()
array_3 = list(all_wells)
for x in definetely_stay:
    try:
        array_3.remove(x)
    except ValueError:
        pass
        # вот досюда
alli

            index
Скважина №
1349           85
21            275
2300          286
3630          334
3635          337
419           387
573           578
581           587
720           720
876           826
878           828
880           829
882           833
883           835

In [57]:
sotired = sotired[~sotired['index'].isin(array_3)].reset_index(drop=True)
sotired = sotired.drop(['index'], axis=1)
sotired

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3
2,10,0.000000,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
3,1004,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3
4,1004,0.000000,1.0,100,4,100,2013-01-31,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
847,942,0.000000,NaN,100,4,100,2013-06-19,ННС+ГРП,ГРП,Ю3
848,96,0.000000,1.0,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
849,971,762.377859,0.0,0,0,0,2012-04-19,ГС,ВНС,Ю3
850,971,762.377859,NaN,100,4,100,2013-01-23,ГС+ГРП,ГРП,Ю3
851,99,0.000000,1.0,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3

In [58]:
        # проверяем ЗБС
grp_4 = copy.deepcopy(grp_gtm)

grp_4['Скважина'] = grp_4.apply(
            lambda x:
            str(x['Скважина']), axis=1)

grp_4

,Месторождение,Unnamed: 0,Скважина,Куст,Тип,Объект разработки до ГТМ,Объект разработки после ГТМ,Страница,Dэк,Краткое описание мероприятий,...,Напор.1,Производительность.1,Комментарий,План,Факт,Пл-ть нефти,Коб,В-ть жидк.,P нас,Unnamed: 65
0,Тайлаковское,Добывающая,1,NaN,ВНС из др. фонд,Ю3,NaN,-1_,NaN,КР9-5 Перевод скважин в добывающие,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Тайлаковское,Добывающая,1,NaN,ГРП,Ю3,NaN,-1_,NaN,КР7-2 Проведение ГРП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Тайлаковское,Нагнетательная,1,NaN,Перевод в ППД,Ю3,NaN,-1_,NaN,КР9-6 Перевод под нагнетание из других категор...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Тайлаковское,Добывающая,1,NaN,Выравнивание профиля притока или приёмистости,Ю3,NaN,-1_,NaN,Проведение ВПП,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Тайлаковское,Добывающая,1,NaN,Проведение ГДИС,Ю3,NaN,-1_,NaN,Гидродинамические исследования,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4923,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4924,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4925,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4926,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4927,Тайлаковское,Добывающая,99,КУСТ-96,Запуск без ремонта,Ю3,NaN,-1_,NaN,Запуск в работу без ремонта,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
grp_zbs = grp_4.drop(grp_4[grp_4['Тип'] != '3БС'].index).reset_index(drop=True)
        # grp_zbs = grp_4.loc[grp_4['Тип'] == 'ЗБС']
grp_zbs = grp_zbs.groupby('Скважина').agg(
            {'Начало.1': lambda x:
            x.tolist()[1] if len(x.tolist()) > 1
            else x.tolist()[0]}
        )
grp_zbs

           Начало.1
Скважина
123      2019-07-13
1230     2014-07-12
1304     2014-07-09
1311     2011-12-05
133      2014-03-28
...             ...
890      2021-11-16
897      2012-04-26
906      2021-09-30
909      2014-07-03
949      2021-09-11

[79 rows x 1 columns]

In [60]:
grp_zbs.reset_index(drop=True)
grp_zbs.reset_index(inplace=True)
        # grp_zbs

vv = grp_zbs['Скважина'].tolist()

grp_zbs['Скважина №'] = vv
grp_zbs = grp_zbs.drop(['Скважина'], axis=1)
grp_zbs

     Начало.1 Скважина №
0  2019-07-13        123
1  2014-07-12       1230
2  2014-07-09       1304
3  2011-12-05       1311
4  2014-03-28        133
..        ...        ...
74 2021-11-16        890
75 2012-04-26        897
76 2021-09-30        906
77 2014-07-03        909
78 2021-09-11        949

[79 rows x 2 columns]

In [61]:
grp_zbs.loc[grp_zbs['Скважина №'] == '507']

     Начало.1 Скважина №
43 2011-06-15        507

In [62]:
sotired_final_zbs = sotired.merge(grp_zbs, on='Скважина №')
sotired_final_zbs

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,Начало.1
0,123,313.336879,0.0,0,0,0,2009-01-20,ГС,ВНС,Ю3,2019-07-13
1,123,313.336879,NaN,100,4,100,2009-03-16,ГС+ГРП,ГРП,Ю3,2019-07-13
2,123,313.336879,NaN,100,4,100,2012-07-15,ГС+ГРП,ГРП,Ю3,2019-07-13
3,123,313.336879,6.0,100,4,100,2019-08-29,ГС+ГРП,ГРП,Ю3,2019-07-13
4,1230,381.848137,NaN,100,4,100,2013-09-09,ГС+ГРП,ГРП,Ю3,2014-07-12
...,...,...,...,...,...,...,...,...,...,...,...
178,897,0.000000,NaN,100,4,100,2011-01-17,ННС+ГРП,ГРП,Ю3,2012-04-26
179,897,0.000000,1.0,100,4,100,2019-05-11,ННС+ГРП,ГРП,Ю3,2012-04-26
180,906,0.000000,NaN,100,4,100,2010-11-26,ННС+ГРП,ГРП,Ю3,2021-09-30
181,909,294.803324,NaN,100,4,100,2011-01-10,ГС+ГРП,ГРП,Ю3,2014-07-03
182,909,294.803324,4.0,100,4,100,2014-07-03,ГС+ГРП,ГРП,Ю3,2014-07-03

In [63]:
abba = sotired_final_zbs['Скважина №'].tolist()

arura=[]
for i in abba:
    if i not in arura:
        arura.append(i)
arura

['123',
 '1230',
 '1304',
 '1311',
 '133',
 '14',
 '142',
 '1501',
 '1503',
 '151',
 '1549',
 '1556',
 '1562',
 '1622',
 '1635',
 '1637',
 '17',
 '173Р',
 '1901',
 '1977',
 '21',
 '23',
 '256Р',
 '2818',
 '35',
 '3552',
 '3821',
 '3825',
 '4100',
 '415',
 '433',
 '449',
 '454',
 '459',
 '463',
 '485',
 '489',
 '491',
 '494',
 '5',
 '500',
 '507',
 '515',
 '541',
 '567',
 '569',
 '582',
 '6',
 '603',
 '619',
 '626',
 '636',
 '65',
 '675',
 '68',
 '71',
 '720',
 '724',
 '726',
 '729',
 '738',
 '739',
 '762',
 '763',
 '766',
 '770',
 '79',
 '8',
 '806',
 '84',
 '85',
 '87',
 '897',
 '906',
 '909']

In [64]:
a=sotired_final_zbs['Дата ВНР после'][0]
type(a)

pandas._libs.tslibs.timestamps.Timestamp

In [65]:
b=sotired_final_zbs['Начало.1'][0]
type(b)

pandas._libs.tslibs.timestamps.Timestamp

In [66]:
if sotired_final_zbs.shape[0] != 0:
    sotired_final_zbs['Длина ГС, м'] = sotired_final_zbs.apply(
            lambda x:
            0 if x['Дата ВНР после'] < x['Начало.1'] else x['Длина ГС, м'],
            axis=1
            )
    sotired_final_zbs['Число стадий ГРП'] = sotired_final_zbs.apply(
            lambda x:
            1 if x['Дата ВНР после'] < x['Начало.1'] else x['Число стадий ГРП'],
            axis=1
            )
    sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            str(x['Скважина №'])
            + ('_Л' if x['Длина ГС, м'] == 0 else ''),
            axis=1
            )
    sotired_final_zbs['L'] = sotired_final_zbs.apply(
                lambda x:
                1 if 'Л' in str(x['Скважина №'])
                else 0, axis=1)
    sotired_final_zbs['ГС/ННС'] = sotired_final_zbs.apply(
                lambda x:
                str(x['ГС/ННС']).replace('ГС', 'ННС') if x['L'] == 1 else str(x['ГС/ННС']),
                axis=1
            )
    sotired_final_zbs = sotired_final_zbs.drop(['L'], axis=1)
    sotired_final_zbs = sotired_final_zbs.drop(['Начало.1'], axis=1)
    sotired_final = sotired[~sotired['Скважина №'].isin(arura)].reset_index(drop=True)
sotired_final1 = pd.concat([sotired_final, sotired_final_zbs])
sotired_final1.reset_index(drop=True)
sotired_final1.reset_index(inplace=True)
sotired_final1

,index,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,0,1,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3
2,2,10,0.000000,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
3,3,1004,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3
4,4,1004,0.000000,1.0,100,4,100,2013-01-31,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...,...
847,178,897_Л,0.000000,1.0,100,4,100,2011-01-17,ННС+ГРП,ГРП,Ю3
848,179,897_Л,0.000000,1.0,100,4,100,2019-05-11,ННС+ГРП,ГРП,Ю3
849,180,906_Л,0.000000,1.0,100,4,100,2010-11-26,ННС+ГРП,ГРП,Ю3
850,181,909_Л,0.000000,1.0,100,4,100,2011-01-10,ННС+ГРП,ГРП,Ю3
851,182,909,294.803324,4.0,100,4,100,2014-07-03,ГС+ГРП,ГРП,Ю3

In [67]:
sotired_final_zbs

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,123_Л,0.000000,1.0,0,0,0,2009-01-20,ННС,ВНС,Ю3
1,123_Л,0.000000,1.0,100,4,100,2009-03-16,ННС+ГРП,ГРП,Ю3
2,123_Л,0.000000,1.0,100,4,100,2012-07-15,ННС+ГРП,ГРП,Ю3
3,123,313.336879,6.0,100,4,100,2019-08-29,ГС+ГРП,ГРП,Ю3
4,1230_Л,0.000000,1.0,100,4,100,2013-09-09,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
178,897_Л,0.000000,1.0,100,4,100,2011-01-17,ННС+ГРП,ГРП,Ю3
179,897_Л,0.000000,1.0,100,4,100,2019-05-11,ННС+ГРП,ГРП,Ю3
180,906_Л,0.000000,1.0,100,4,100,2010-11-26,ННС+ГРП,ГРП,Ю3
181,909_Л,0.000000,1.0,100,4,100,2011-01-10,ННС+ГРП,ГРП,Ю3
182,909,294.803324,4.0,100,4,100,2014-07-03,ГС+ГРП,ГРП,Ю3

In [68]:
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3
2,10,0.000000,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
3,1004,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3
4,1004,0.000000,1.0,100,4,100,2013-01-31,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
664,942,0.000000,NaN,100,4,100,2013-06-19,ННС+ГРП,ГРП,Ю3
665,96,0.000000,1.0,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
666,971,762.377859,0.0,0,0,0,2012-04-19,ГС,ВНС,Ю3
667,971,762.377859,NaN,100,4,100,2013-01-23,ГС+ГРП,ГРП,Ю3
668,99,0.000000,1.0,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3

In [69]:
        # приставка ФРАК там где надо
sotired_final.reset_index(drop=True)
sotired_final.reset_index(inplace=True)
sotired_final['index']=sotired_final.index
step = sotired_final.drop(
            sotired_final[(sotired_final['ГС/ННС'] == 'ГС') | (sotired_final['ГС/ННС'] == 'ННС')].index)
step['для_фрак'] = step.apply(
            lambda x:
            x['Скважина №'].partition('_')[0] if '_' in str(x['Скважина №'])
            else x['Скважина №'], axis=1)
step = step.groupby(by=['для_фрак']).agg(
            {'index': lambda x:
            x.tolist()}
        )
step

              index
для_фрак
1               [0]
10              [2]
1004      [3, 4, 5]
1005            [6]
1006            [7]
...             ...
936           [663]
942           [664]
96            [665]
971           [667]
99            [668]

[338 rows x 1 columns]

In [70]:

step.reset_index(inplace=True)
step.rename(columns={'для_фрак': 'список'}, inplace=True)

step['Length'] = step.apply(
            lambda x: len(x['index'])
            , axis=1)
step = step.drop(step[step['Length'] < 1].index)
gang1 = []
gang2 = []
gang3 = []
gang4 = []
gang5 = []
gang6 = []
gang7 = []
gang8 = []
gang9 = []
gang10 = []
gang1

[]

In [71]:

for i in step['index']:
    if len(i) >= 1:
        gang1.append(i[0])
    if len(i) >= 2:
        gang2.append(i[1])
    if len(i) >= 3:
        gang3.append(i[2])
    if len(i) >= 4:
        gang4.append(i[3])
    if len(i) >= 5:
        gang5.append(i[4])
    if len(i) >= 6:
        gang6.append(i[5])
    if len(i) >= 7:
        gang7.append(i[6])
    if len(i) >= 8:
        gang8.append(i[7])
    if len(i) >= 9:
        gang9.append(i[8])
    if len(i) >= 10:
        gang10.append(i[9])
    else:
        pass
gang1

[0,
 2,
 3,
 6,
 7,
 10,
 12,
 13,
 15,
 16,
 17,
 18,
 19,
 20,
 22,
 23,
 24,
 27,
 29,
 31,
 32,
 34,
 36,
 38,
 41,
 42,
 47,
 48,
 50,
 52,
 54,
 57,
 58,
 63,
 66,
 67,
 69,
 70,
 72,
 74,
 76,
 79,
 82,
 83,
 86,
 88,
 91,
 94,
 95,
 98,
 102,
 105,
 106,
 108,
 110,
 111,
 112,
 113,
 116,
 118,
 121,
 122,
 125,
 126,
 129,
 132,
 135,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 146,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 173,
 174,
 175,
 176,
 177,
 178,
 181,
 183,
 186,
 188,
 189,
 191,
 192,
 193,
 195,
 197,
 199,
 200,
 203,
 210,
 212,
 215,
 219,
 223,
 226,
 229,
 231,
 232,
 241,
 242,
 246,
 247,
 248,
 249,
 251,
 254,
 255,
 257,
 258,
 260,
 261,
 262,
 263,
 268,
 269,
 272,
 273,
 275,
 276,
 279,
 280,
 281,
 282,
 285,
 287,
 290,
 292,
 295,
 296,
 298,
 300,
 302,
 303,
 304,
 305,
 306,
 307,
 310,
 313,
 314,
 316,
 318,
 320,
 323,
 324,
 325,
 328,
 329,
 334,
 339,
 341,
 344,
 346,
 347,
 348,
 349,
 353,
 356,
 358,
 361,
 363,
 366,
 367,
 368,
 370,
 372,
 376,
 378,
 379,
 380,
 382,
 383,
 386,
 388,
 391,
 393,
 395,
 399,
 402,
 404,
 407,
 409,
 412,
 415,
 418,
 420,
 422,
 426,
 430,
 431,
 432,
 433,
 435,
 436,
 439,
 443,
 446,
 448,
 452,
 454,
 456,
 458,
 459,
 460,
 462,
 464,
 467,
 472,
 474,
 475,
 477,
 479,
 481,
 483,
 485,
 487,
 489,
 492,
 494,
 498,
 502,
 507,
 509,
 512,
 514,
 515,
 517,
 519,
 521,
 523,
 524,
 527,
 528,
 530,
 531,
 532,
 533,
 535,
 537,
 538,
 540,
 541,
 542,
 543,
 544,
 545,
 547,
 548,
 550,
 553,
 555,
 557,
 559,
 561,
 563,
 564,
 565,
 571,
 572,
 574,
 575,
 577,
 580,
 582,
 584,
 587,
 589,
 590,
 593,
 595,
 596,
 598,
 600,
 602,
 604,
 606,
 608,
 610,
 613,
 614,
 617,
 618,
 620,
 621,
 622,
 624,
 628,
 631,
 632,
 634,
 635,
 636,
 637,
 638,
 639,
 641,
 643,
 646,
 648,
 652,
 654,
 656,
 658,
 659,
 661,
 663,
 664,
 665,
 667,
 668]

In [72]:

sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ГРП' if x['index'] in gang1
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_1' if x['index'] in gang2
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_2' if x['index'] in gang3
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_3' if x['index'] in gang4
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_4' if x['index'] in gang5
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_5' if x['index'] in gang6
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_6' if x['index'] in gang7
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_7' if x['index'] in gang8
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_8' if x['index'] in gang9
            else x['Скважина №'], axis=1)
sotired_final['Скважина №'] = sotired_final.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_9' if x['index'] in gang10
            else x['Скважина №'], axis=1)
sotired_final = sotired_final.drop(['index'], axis=1)
sotired_final

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт
0,1_ГРП,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3
1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3
2,10_ГРП,0.000000,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3
3,1004_ГРП,0.000000,NaN,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3
4,1004_ФРАК_1,0.000000,1.0,100,4,100,2013-01-31,ННС+ГРП,ГРП,Ю3
...,...,...,...,...,...,...,...,...,...,...
664,942_ГРП,0.000000,NaN,100,4,100,2013-06-19,ННС+ГРП,ГРП,Ю3
665,96_ГРП,0.000000,1.0,100,4,100,2019-07-31,ННС+ГРП,ГРП,Ю3
666,971,762.377859,0.0,0,0,0,2012-04-19,ГС,ВНС,Ю3
667,971_ГРП,762.377859,NaN,100,4,100,2013-01-23,ГС+ГРП,ГРП,Ю3
668,99_ГРП,0.000000,1.0,100,4,100,2019-11-01,ННС+ГРП,ГРП,Ю3

In [73]:

        # sotired_final = sotired_final.drop(['месяц с грп'], axis=1)


sotired_final.reset_index(drop=True)
sotired_final.reset_index(inplace=True)
sotired_final = sotired_final.drop(['index'], axis=1)
sotired_final['Число стадий ГРП'] = sotired_final.apply(
            lambda x:
            1 if x['Длина ГС, м'] == 0 and 'ГРП' in x['ГС/ННС']
            else x['Число стадий ГРП'], axis=1)
sotired_final_zbs['index']=sotired_final_zbs.index
sotired_final_zbs.reset_index(drop=True)
sotired_final_zbs.reset_index(inplace=True)
step1 = sotired_final_zbs.drop(
            sotired_final_zbs[(sotired_final_zbs['ГС/ННС'] == 'ГС') | (sotired_final_zbs['ГС/ННС'] == 'ННС')].index)
step1 = step1.groupby(by=['Скважина №']).agg(
            {'index': lambda x:
            x.tolist()}
        )
step1.reset_index(inplace=True)
step1['Length'] = step1.apply(
            lambda x: len(x['index'])
            , axis=1)
step1 = step1.drop(step1[step1['Length'] < 1].index)
gang11 = []
gang21 = []
gang31 = []
gang41 = []
gang51 = []
gang61 = []
gang71 = []
gang81 = []
gang91 = []
gang101 = []
gang11

[]

In [74]:

for i in step1['index']:
    if len(i) >= 1:
        gang11.append(i[0])
    if len(i) >= 2:
        gang21.append(i[1])
    if len(i) >= 3:
        gang31.append(i[2])
    if len(i) >= 4:
        gang41.append(i[3])
    if len(i) >= 5:
        gang51.append(i[4])
    if len(i) >= 6:
        gang61.append(i[5])
    if len(i) >= 7:
        gang71.append(i[6])
    if len(i) >= 8:
        gang81.append(i[7])
    if len(i) >= 9:
        gang91.append(i[8])
    if len(i) >= 10:
        gang101.append(i[9])
    else:
        pass
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ГРП' if x['index'] in gang11
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_1' if x['index'] in gang21
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_2' if x['index'] in gang31
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_3' if x['index'] in gang41
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_4' if x['index'] in gang51
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_5' if x['index'] in gang61
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_6' if x['index'] in gang71
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_7' if x['index'] in gang81
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_8' if x['index'] in gang91
            else x['Скважина №'], axis=1)
sotired_final_zbs['Скважина №'] = sotired_final_zbs.apply(
            lambda x:
            x['Скважина №'] + '_ФРАК_9' if x['index'] in gang101
            else x['Скважина №'], axis=1)
sotired_final_zbs = sotired_final_zbs.drop(['index'], axis=1)

        
sotired_final_zbs.reset_index(drop=True)
sotired_final_zbs.reset_index(inplace=True)
sotired_final_zbs = sotired_final_zbs.drop(['index'], axis=1)
sotired_final_zbs['Число стадий ГРП'] = sotired_final_zbs.apply(
            lambda x:
            1 if x['Длина ГС, м'] == 0 and 'ГРП' in x['ГС/ННС']
            else x['Число стадий ГРП'], axis=1)
we_here = pd.concat([sotired_final, sotired_final_zbs])
we_here['Число стадий ГРП'] = we_here.apply(
            lambda x:
            1 if 'ФРАК' in str(x['Скважина №'])
            else x['Число стадий ГРП'], axis=1)
we_here['Число стадий ГРП'] = we_here.apply(
            lambda x:
            0 if 'ГС' == str(x['ГС/ННС'])
            else x['Число стадий ГРП'], axis=1)
we_here['Число стадий ГРП'] = we_here.apply(
            lambda x:
            0 if 'ННС' == str(x['ГС/ННС'])
            else x['Число стадий ГРП'], axis=1)
we_here['Скважина №'] = we_here.apply(
            lambda x:
            str(x['Скважина №']).replace('_Л', 'Л') if '_Л' in str(x['Скважина №']) else str(x['Скважина №']),
            axis=1
        )
we_here

,Скважина №,"Длина ГС, м",Число стадий ГРП,"Полудлина трещины, м","Ширина трещины, мм","Проницаемость проппанта, Д",Дата ВНР после,ГС/ННС,Тип ГТМ,Пласт,level_0
0,1_ГРП,0.000000,1.0,100,4,100,2016-03-12,ННС+ГРП,ГРП,Ю3,NaN
1,10,0.000000,0.0,0,0,0,2008-10-12,ННС,ВНС,Ю3,NaN
2,10_ГРП,0.000000,1.0,100,4,100,2013-03-03,ННС+ГРП,ГРП,Ю3,NaN
3,1004_ГРП,0.000000,1.0,100,4,100,2011-02-04,ННС+ГРП,ГРП,Ю3,NaN
4,1004_ФРАК_1,0.000000,1.0,100,4,100,2013-01-31,ННС+ГРП,ГРП,Ю3,NaN
...,...,...,...,...,...,...,...,...,...,...,...
178,897Л_ГРП,0.000000,1.0,100,4,100,2011-01-17,ННС+ГРП,ГРП,Ю3,178.0
179,897Л_ФРАК_1,0.000000,1.0,100,4,100,2019-05-11,ННС+ГРП,ГРП,Ю3,179.0
180,906Л_ГРП,0.000000,1.0,100,4,100,2010-11-26,ННС+ГРП,ГРП,Ю3,180.0
181,909Л_ГРП,0.000000,1.0,100,4,100,2011-01-10,ННС+ГРП,ГРП,Ю3,181.0
182,909_ГРП,294.803324,4.0,100,4,100,2014-07-03,ГС+ГРП,ГРП,Ю3,182.0

In [75]:
we_here.to_excel('googles.xlsx')